// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package joblog

import (
	"context"
	"sync"
	"time"

	"github.com/goharbor/harbor/src/pkg/joblog/models"
)

// Manager is a mock implementation of joblog.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked joblog.Manager
//		mockedManager := &Manager{
//			CreateFunc: func(ctx context.Context, jobLog *models.JobLog) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteBeforeFunc: func(ctx context.Context, t time.Time) (int64, error) {
//				panic("mock out the DeleteBefore method")
//			},
//			GetFunc: func(ctx context.Context, uuid string) (*models.JobLog, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedManager in code that requires joblog.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, jobLog *models.JobLog) (int64, error)

	// DeleteBeforeFunc mocks the DeleteBefore method.
	DeleteBeforeFunc func(ctx context.Context, t time.Time) (int64, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, uuid string) (*models.JobLog, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobLog is the jobLog argument value.
			JobLog *models.JobLog
		}
		// DeleteBefore holds details about calls to the DeleteBefore method.
		DeleteBefore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T time.Time
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UUID is the uuid argument value.
			UUID string
		}
	}
	lockCreate       sync.RWMutex
	lockDeleteBefore sync.RWMutex
	lockGet          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, jobLog *models.JobLog) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		JobLog *models.JobLog
	}{
		Ctx:    ctx,
		JobLog: jobLog,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, jobLog)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx    context.Context
	JobLog *models.JobLog
} {
	var calls []struct {
		Ctx    context.Context
		JobLog *models.JobLog
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// DeleteBefore calls DeleteBeforeFunc.
func (mock *Manager) DeleteBefore(ctx context.Context, t time.Time) (int64, error) {
	callInfo := struct {
		Ctx context.Context
		T   time.Time
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockDeleteBefore.Lock()
	mock.calls.DeleteBefore = append(mock.calls.DeleteBefore, callInfo)
	mock.lockDeleteBefore.Unlock()
	if mock.DeleteBeforeFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.DeleteBeforeFunc(ctx, t)
}

// DeleteBeforeCalls gets all the calls that were made to DeleteBefore.
// Check the length with:
//
//	len(mockedManager.DeleteBeforeCalls())
func (mock *Manager) DeleteBeforeCalls() []struct {
	Ctx context.Context
	T   time.Time
} {
	var calls []struct {
		Ctx context.Context
		T   time.Time
	}
	mock.lockDeleteBefore.RLock()
	calls = mock.calls.DeleteBefore
	mock.lockDeleteBefore.RUnlock()
	return calls
}

// ResetDeleteBeforeCalls reset all the calls that were made to DeleteBefore.
func (mock *Manager) ResetDeleteBeforeCalls() {
	mock.lockDeleteBefore.Lock()
	mock.calls.DeleteBefore = nil
	mock.lockDeleteBefore.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, uuid string) (*models.JobLog, error) {
	callInfo := struct {
		Ctx  context.Context
		UUID string
	}{
		Ctx:  ctx,
		UUID: uuid,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			jobLog *models.JobLog
			err    error
		)
		return jobLog, err
	}
	return mock.GetFunc(ctx, uuid)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx  context.Context
	UUID string
} {
	var calls []struct {
		Ctx  context.Context
		UUID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDeleteBefore.Lock()
	mock.calls.DeleteBefore = nil
	mock.lockDeleteBefore.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}
