// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package jobmonitor

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/pkg/jobmonitor"
)

// PoolManager is a mock implementation of jobmonitor.PoolManager.
//
//	func TestSomethingThatUsesPoolManager(t *testing.T) {
//
//		// make and configure a mocked jobmonitor.PoolManager
//		mockedPoolManager := &PoolManager{
//			ListFunc: func(ctx context.Context, monitorClient jobmonitor.JobServiceMonitorClient) ([]*jobmonitor.WorkerPool, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedPoolManager in code that requires jobmonitor.PoolManager
//		// and then make assertions.
//
//	}
type PoolManager struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, monitorClient jobmonitor.JobServiceMonitorClient) ([]*jobmonitor.WorkerPool, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MonitorClient is the monitorClient argument value.
			MonitorClient jobmonitor.JobServiceMonitorClient
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *PoolManager) List(ctx context.Context, monitorClient jobmonitor.JobServiceMonitorClient) ([]*jobmonitor.WorkerPool, error) {
	callInfo := struct {
		Ctx           context.Context
		MonitorClient jobmonitor.JobServiceMonitorClient
	}{
		Ctx:           ctx,
		MonitorClient: monitorClient,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			workerPools []*jobmonitor.WorkerPool
			err         error
		)
		return workerPools, err
	}
	return mock.ListFunc(ctx, monitorClient)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedPoolManager.ListCalls())
func (mock *PoolManager) ListCalls() []struct {
	Ctx           context.Context
	MonitorClient jobmonitor.JobServiceMonitorClient
} {
	var calls []struct {
		Ctx           context.Context
		MonitorClient jobmonitor.JobServiceMonitorClient
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *PoolManager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *PoolManager) ResetCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}
