// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package project

import (
	"context"
	"sync"

	models0 "github.com/goharbor/harbor/src/common/models"
	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/project/models"
)

// Manager is a mock implementation of project.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked project.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, project *models.Project) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, idOrName any) (*models.Project, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*models.Project, error) {
//				panic("mock out the List method")
//			},
//			ListAdminRolesOfUserFunc: func(ctx context.Context, user models0.User) ([]models.Member, error) {
//				panic("mock out the ListAdminRolesOfUser method")
//			},
//			ListRolesFunc: func(ctx context.Context, projectID int64, userID int, groupIDs ...int) ([]int, error) {
//				panic("mock out the ListRoles method")
//			},
//		}
//
//		// use mockedManager in code that requires project.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, project *models.Project) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, idOrName any) (*models.Project, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*models.Project, error)

	// ListAdminRolesOfUserFunc mocks the ListAdminRolesOfUser method.
	ListAdminRolesOfUserFunc func(ctx context.Context, user models0.User) ([]models.Member, error)

	// ListRolesFunc mocks the ListRoles method.
	ListRolesFunc func(ctx context.Context, projectID int64, userID int, groupIDs ...int) ([]int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Project is the project argument value.
			Project *models.Project
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IdOrName is the idOrName argument value.
			IdOrName any
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListAdminRolesOfUser holds details about calls to the ListAdminRolesOfUser method.
		ListAdminRolesOfUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User models0.User
		}
		// ListRoles holds details about calls to the ListRoles method.
		ListRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// UserID is the userID argument value.
			UserID int
			// GroupIDs is the groupIDs argument value.
			GroupIDs []int
		}
	}
	lockCount                sync.RWMutex
	lockCreate               sync.RWMutex
	lockDelete               sync.RWMutex
	lockGet                  sync.RWMutex
	lockList                 sync.RWMutex
	lockListAdminRolesOfUser sync.RWMutex
	lockListRoles            sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, project *models.Project) (int64, error) {
	callInfo := struct {
		Ctx     context.Context
		Project *models.Project
	}{
		Ctx:     ctx,
		Project: project,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CreateFunc(ctx, project)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx     context.Context
	Project *models.Project
} {
	var calls []struct {
		Ctx     context.Context
		Project *models.Project
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, idOrName any) (*models.Project, error) {
	callInfo := struct {
		Ctx      context.Context
		IdOrName any
	}{
		Ctx:      ctx,
		IdOrName: idOrName,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			project *models.Project
			err     error
		)
		return project, err
	}
	return mock.GetFunc(ctx, idOrName)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx      context.Context
	IdOrName any
} {
	var calls []struct {
		Ctx      context.Context
		IdOrName any
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*models.Project, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			projects []*models.Project
			err      error
		)
		return projects, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ListAdminRolesOfUser calls ListAdminRolesOfUserFunc.
func (mock *Manager) ListAdminRolesOfUser(ctx context.Context, user models0.User) ([]models.Member, error) {
	callInfo := struct {
		Ctx  context.Context
		User models0.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockListAdminRolesOfUser.Lock()
	mock.calls.ListAdminRolesOfUser = append(mock.calls.ListAdminRolesOfUser, callInfo)
	mock.lockListAdminRolesOfUser.Unlock()
	if mock.ListAdminRolesOfUserFunc == nil {
		var (
			members []models.Member
			err     error
		)
		return members, err
	}
	return mock.ListAdminRolesOfUserFunc(ctx, user)
}

// ListAdminRolesOfUserCalls gets all the calls that were made to ListAdminRolesOfUser.
// Check the length with:
//
//	len(mockedManager.ListAdminRolesOfUserCalls())
func (mock *Manager) ListAdminRolesOfUserCalls() []struct {
	Ctx  context.Context
	User models0.User
} {
	var calls []struct {
		Ctx  context.Context
		User models0.User
	}
	mock.lockListAdminRolesOfUser.RLock()
	calls = mock.calls.ListAdminRolesOfUser
	mock.lockListAdminRolesOfUser.RUnlock()
	return calls
}

// ResetListAdminRolesOfUserCalls reset all the calls that were made to ListAdminRolesOfUser.
func (mock *Manager) ResetListAdminRolesOfUserCalls() {
	mock.lockListAdminRolesOfUser.Lock()
	mock.calls.ListAdminRolesOfUser = nil
	mock.lockListAdminRolesOfUser.Unlock()
}

// ListRoles calls ListRolesFunc.
func (mock *Manager) ListRoles(ctx context.Context, projectID int64, userID int, groupIDs ...int) ([]int, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		UserID    int
		GroupIDs  []int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		UserID:    userID,
		GroupIDs:  groupIDs,
	}
	mock.lockListRoles.Lock()
	mock.calls.ListRoles = append(mock.calls.ListRoles, callInfo)
	mock.lockListRoles.Unlock()
	if mock.ListRolesFunc == nil {
		var (
			ints []int
			err  error
		)
		return ints, err
	}
	return mock.ListRolesFunc(ctx, projectID, userID, groupIDs...)
}

// ListRolesCalls gets all the calls that were made to ListRoles.
// Check the length with:
//
//	len(mockedManager.ListRolesCalls())
func (mock *Manager) ListRolesCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	UserID    int
	GroupIDs  []int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		UserID    int
		GroupIDs  []int
	}
	mock.lockListRoles.RLock()
	calls = mock.calls.ListRoles
	mock.lockListRoles.RUnlock()
	return calls
}

// ResetListRolesCalls reset all the calls that were made to ListRoles.
func (mock *Manager) ResetListRolesCalls() {
	mock.lockListRoles.Lock()
	mock.calls.ListRoles = nil
	mock.lockListRoles.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockListAdminRolesOfUser.Lock()
	mock.calls.ListAdminRolesOfUser = nil
	mock.lockListAdminRolesOfUser.Unlock()

	mock.lockListRoles.Lock()
	mock.calls.ListRoles = nil
	mock.lockListRoles.Unlock()
}
