// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package policy

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/notification/policy/model"
)

// Manager is a mock implementation of policy.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked policy.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, policy *model.Policy) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, policyID int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*model.Policy, error) {
//				panic("mock out the Get method")
//			},
//			GetRelatedPolicesFunc: func(ctx context.Context, projectID int64, eventType string) ([]*model.Policy, error) {
//				panic("mock out the GetRelatedPolices method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*model.Policy, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, policy *model.Policy) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedManager in code that requires policy.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, policy *model.Policy) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, policyID int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*model.Policy, error)

	// GetRelatedPolicesFunc mocks the GetRelatedPolices method.
	GetRelatedPolicesFunc func(ctx context.Context, projectID int64, eventType string) ([]*model.Policy, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*model.Policy, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, policy *model.Policy) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Policy is the policy argument value.
			Policy *model.Policy
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetRelatedPolices holds details about calls to the GetRelatedPolices method.
		GetRelatedPolices []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// EventType is the eventType argument value.
			EventType string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Policy is the policy argument value.
			Policy *model.Policy
		}
	}
	lockCount             sync.RWMutex
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockGet               sync.RWMutex
	lockGetRelatedPolices sync.RWMutex
	lockList              sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, policy *model.Policy) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		Policy *model.Policy
	}{
		Ctx:    ctx,
		Policy: policy,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CreateFunc(ctx, policy)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx    context.Context
	Policy *model.Policy
} {
	var calls []struct {
		Ctx    context.Context
		Policy *model.Policy
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, policyID int64) error {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
	}{
		Ctx:      ctx,
		PolicyID: policyID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, policyID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx      context.Context
	PolicyID int64
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*model.Policy, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			policy *model.Policy
			err    error
		)
		return policy, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetRelatedPolices calls GetRelatedPolicesFunc.
func (mock *Manager) GetRelatedPolices(ctx context.Context, projectID int64, eventType string) ([]*model.Policy, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		EventType string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		EventType: eventType,
	}
	mock.lockGetRelatedPolices.Lock()
	mock.calls.GetRelatedPolices = append(mock.calls.GetRelatedPolices, callInfo)
	mock.lockGetRelatedPolices.Unlock()
	if mock.GetRelatedPolicesFunc == nil {
		var (
			policys []*model.Policy
			err     error
		)
		return policys, err
	}
	return mock.GetRelatedPolicesFunc(ctx, projectID, eventType)
}

// GetRelatedPolicesCalls gets all the calls that were made to GetRelatedPolices.
// Check the length with:
//
//	len(mockedManager.GetRelatedPolicesCalls())
func (mock *Manager) GetRelatedPolicesCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	EventType string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		EventType string
	}
	mock.lockGetRelatedPolices.RLock()
	calls = mock.calls.GetRelatedPolices
	mock.lockGetRelatedPolices.RUnlock()
	return calls
}

// ResetGetRelatedPolicesCalls reset all the calls that were made to GetRelatedPolices.
func (mock *Manager) ResetGetRelatedPolicesCalls() {
	mock.lockGetRelatedPolices.Lock()
	mock.calls.GetRelatedPolices = nil
	mock.lockGetRelatedPolices.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*model.Policy, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			policys []*model.Policy
			err     error
		)
		return policys, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, policy *model.Policy) error {
	callInfo := struct {
		Ctx    context.Context
		Policy *model.Policy
	}{
		Ctx:    ctx,
		Policy: policy,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, policy)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx    context.Context
	Policy *model.Policy
} {
	var calls []struct {
		Ctx    context.Context
		Policy *model.Policy
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetRelatedPolices.Lock()
	mock.calls.GetRelatedPolices = nil
	mock.lockGetRelatedPolices.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
