apiVersion: v2
name: Harbor Next
description: A modern, production-ready Helm chart for [Harbor Next](https://github.com/container-registry/harbor-next) - the cloud native container registry for Kubernetes.
type: application
version: 3.0.0
appVersion: "v2.14.1"
kubeVersion: ">=1.28.0-0"

home: https://github.com/container-registry/harbor-next
icon: https://raw.githubusercontent.com/container-registry/harbor-next/refs/heads/main/docs/img/harbor-next-logo.svg
sources:
  - https://github.com/container-registry/harbor-next

keywords:
  - harbor
  - container-registry
  - registry
  - oci
  - docker
  - artifacts
  - vulnerability-scanning
  - image-registry
  - cloud-native
  - cncf
  - helm

maintainers:
  - name: Harbor Next Authors
    url: https://github.com/container-registry/harbor-next

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/container-registry/harbor-next
    - name: Source Helm Chart
      url: https://github.com/container-registry/harbor-next/deploy/chart/
    - name: Upstream Harbor
      url: https://goharbor.io
  artifacthub.io/screenshots: |
    - title: Harbor Next
      url: https://raw.githubusercontent.com/container-registry/harbor-next/refs/heads/main/docs/img/harbor-next-logo.svg

dependencies:
  - name: valkey
    version: "0.9.3"
    repository: "oci://ghcr.io/valkey-io/valkey-helm"
    condition: valkey.enabled
