// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package label

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/label/model"
)

// Manager is a mock implementation of label.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked label.Manager
//		mockedManager := &Manager{
//			AddToFunc: func(ctx context.Context, labelID int64, artifactID int64) error {
//				panic("mock out the AddTo method")
//			},
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, label *model.Label) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*model.Label, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*model.Label, error) {
//				panic("mock out the List method")
//			},
//			ListByArtifactFunc: func(ctx context.Context, artifactID int64) ([]*model.Label, error) {
//				panic("mock out the ListByArtifact method")
//			},
//			RemoveAllFromFunc: func(ctx context.Context, artifactID int64) error {
//				panic("mock out the RemoveAllFrom method")
//			},
//			RemoveFromFunc: func(ctx context.Context, labelID int64, artifactID int64) error {
//				panic("mock out the RemoveFrom method")
//			},
//			RemoveFromAllArtifactsFunc: func(ctx context.Context, labelID int64) error {
//				panic("mock out the RemoveFromAllArtifacts method")
//			},
//			UpdateFunc: func(ctx context.Context, label *model.Label) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedManager in code that requires label.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// AddToFunc mocks the AddTo method.
	AddToFunc func(ctx context.Context, labelID int64, artifactID int64) error

	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, label *model.Label) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*model.Label, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*model.Label, error)

	// ListByArtifactFunc mocks the ListByArtifact method.
	ListByArtifactFunc func(ctx context.Context, artifactID int64) ([]*model.Label, error)

	// RemoveAllFromFunc mocks the RemoveAllFrom method.
	RemoveAllFromFunc func(ctx context.Context, artifactID int64) error

	// RemoveFromFunc mocks the RemoveFrom method.
	RemoveFromFunc func(ctx context.Context, labelID int64, artifactID int64) error

	// RemoveFromAllArtifactsFunc mocks the RemoveFromAllArtifacts method.
	RemoveFromAllArtifactsFunc func(ctx context.Context, labelID int64) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, label *model.Label) error

	// calls tracks calls to the methods.
	calls struct {
		// AddTo holds details about calls to the AddTo method.
		AddTo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LabelID is the labelID argument value.
			LabelID int64
			// ArtifactID is the artifactID argument value.
			ArtifactID int64
		}
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Label is the label argument value.
			Label *model.Label
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListByArtifact holds details about calls to the ListByArtifact method.
		ListByArtifact []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArtifactID is the artifactID argument value.
			ArtifactID int64
		}
		// RemoveAllFrom holds details about calls to the RemoveAllFrom method.
		RemoveAllFrom []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ArtifactID is the artifactID argument value.
			ArtifactID int64
		}
		// RemoveFrom holds details about calls to the RemoveFrom method.
		RemoveFrom []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LabelID is the labelID argument value.
			LabelID int64
			// ArtifactID is the artifactID argument value.
			ArtifactID int64
		}
		// RemoveFromAllArtifacts holds details about calls to the RemoveFromAllArtifacts method.
		RemoveFromAllArtifacts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LabelID is the labelID argument value.
			LabelID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Label is the label argument value.
			Label *model.Label
		}
	}
	lockAddTo                  sync.RWMutex
	lockCount                  sync.RWMutex
	lockCreate                 sync.RWMutex
	lockDelete                 sync.RWMutex
	lockGet                    sync.RWMutex
	lockList                   sync.RWMutex
	lockListByArtifact         sync.RWMutex
	lockRemoveAllFrom          sync.RWMutex
	lockRemoveFrom             sync.RWMutex
	lockRemoveFromAllArtifacts sync.RWMutex
	lockUpdate                 sync.RWMutex
}

// AddTo calls AddToFunc.
func (mock *Manager) AddTo(ctx context.Context, labelID int64, artifactID int64) error {
	callInfo := struct {
		Ctx        context.Context
		LabelID    int64
		ArtifactID int64
	}{
		Ctx:        ctx,
		LabelID:    labelID,
		ArtifactID: artifactID,
	}
	mock.lockAddTo.Lock()
	mock.calls.AddTo = append(mock.calls.AddTo, callInfo)
	mock.lockAddTo.Unlock()
	if mock.AddToFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AddToFunc(ctx, labelID, artifactID)
}

// AddToCalls gets all the calls that were made to AddTo.
// Check the length with:
//
//	len(mockedManager.AddToCalls())
func (mock *Manager) AddToCalls() []struct {
	Ctx        context.Context
	LabelID    int64
	ArtifactID int64
} {
	var calls []struct {
		Ctx        context.Context
		LabelID    int64
		ArtifactID int64
	}
	mock.lockAddTo.RLock()
	calls = mock.calls.AddTo
	mock.lockAddTo.RUnlock()
	return calls
}

// ResetAddToCalls reset all the calls that were made to AddTo.
func (mock *Manager) ResetAddToCalls() {
	mock.lockAddTo.Lock()
	mock.calls.AddTo = nil
	mock.lockAddTo.Unlock()
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, label *model.Label) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Label *model.Label
	}{
		Ctx:   ctx,
		Label: label,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, label)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx   context.Context
	Label *model.Label
} {
	var calls []struct {
		Ctx   context.Context
		Label *model.Label
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*model.Label, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			label *model.Label
			err   error
		)
		return label, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*model.Label, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			labels []*model.Label
			err    error
		)
		return labels, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ListByArtifact calls ListByArtifactFunc.
func (mock *Manager) ListByArtifact(ctx context.Context, artifactID int64) ([]*model.Label, error) {
	callInfo := struct {
		Ctx        context.Context
		ArtifactID int64
	}{
		Ctx:        ctx,
		ArtifactID: artifactID,
	}
	mock.lockListByArtifact.Lock()
	mock.calls.ListByArtifact = append(mock.calls.ListByArtifact, callInfo)
	mock.lockListByArtifact.Unlock()
	if mock.ListByArtifactFunc == nil {
		var (
			labels []*model.Label
			err    error
		)
		return labels, err
	}
	return mock.ListByArtifactFunc(ctx, artifactID)
}

// ListByArtifactCalls gets all the calls that were made to ListByArtifact.
// Check the length with:
//
//	len(mockedManager.ListByArtifactCalls())
func (mock *Manager) ListByArtifactCalls() []struct {
	Ctx        context.Context
	ArtifactID int64
} {
	var calls []struct {
		Ctx        context.Context
		ArtifactID int64
	}
	mock.lockListByArtifact.RLock()
	calls = mock.calls.ListByArtifact
	mock.lockListByArtifact.RUnlock()
	return calls
}

// ResetListByArtifactCalls reset all the calls that were made to ListByArtifact.
func (mock *Manager) ResetListByArtifactCalls() {
	mock.lockListByArtifact.Lock()
	mock.calls.ListByArtifact = nil
	mock.lockListByArtifact.Unlock()
}

// RemoveAllFrom calls RemoveAllFromFunc.
func (mock *Manager) RemoveAllFrom(ctx context.Context, artifactID int64) error {
	callInfo := struct {
		Ctx        context.Context
		ArtifactID int64
	}{
		Ctx:        ctx,
		ArtifactID: artifactID,
	}
	mock.lockRemoveAllFrom.Lock()
	mock.calls.RemoveAllFrom = append(mock.calls.RemoveAllFrom, callInfo)
	mock.lockRemoveAllFrom.Unlock()
	if mock.RemoveAllFromFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.RemoveAllFromFunc(ctx, artifactID)
}

// RemoveAllFromCalls gets all the calls that were made to RemoveAllFrom.
// Check the length with:
//
//	len(mockedManager.RemoveAllFromCalls())
func (mock *Manager) RemoveAllFromCalls() []struct {
	Ctx        context.Context
	ArtifactID int64
} {
	var calls []struct {
		Ctx        context.Context
		ArtifactID int64
	}
	mock.lockRemoveAllFrom.RLock()
	calls = mock.calls.RemoveAllFrom
	mock.lockRemoveAllFrom.RUnlock()
	return calls
}

// ResetRemoveAllFromCalls reset all the calls that were made to RemoveAllFrom.
func (mock *Manager) ResetRemoveAllFromCalls() {
	mock.lockRemoveAllFrom.Lock()
	mock.calls.RemoveAllFrom = nil
	mock.lockRemoveAllFrom.Unlock()
}

// RemoveFrom calls RemoveFromFunc.
func (mock *Manager) RemoveFrom(ctx context.Context, labelID int64, artifactID int64) error {
	callInfo := struct {
		Ctx        context.Context
		LabelID    int64
		ArtifactID int64
	}{
		Ctx:        ctx,
		LabelID:    labelID,
		ArtifactID: artifactID,
	}
	mock.lockRemoveFrom.Lock()
	mock.calls.RemoveFrom = append(mock.calls.RemoveFrom, callInfo)
	mock.lockRemoveFrom.Unlock()
	if mock.RemoveFromFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.RemoveFromFunc(ctx, labelID, artifactID)
}

// RemoveFromCalls gets all the calls that were made to RemoveFrom.
// Check the length with:
//
//	len(mockedManager.RemoveFromCalls())
func (mock *Manager) RemoveFromCalls() []struct {
	Ctx        context.Context
	LabelID    int64
	ArtifactID int64
} {
	var calls []struct {
		Ctx        context.Context
		LabelID    int64
		ArtifactID int64
	}
	mock.lockRemoveFrom.RLock()
	calls = mock.calls.RemoveFrom
	mock.lockRemoveFrom.RUnlock()
	return calls
}

// ResetRemoveFromCalls reset all the calls that were made to RemoveFrom.
func (mock *Manager) ResetRemoveFromCalls() {
	mock.lockRemoveFrom.Lock()
	mock.calls.RemoveFrom = nil
	mock.lockRemoveFrom.Unlock()
}

// RemoveFromAllArtifacts calls RemoveFromAllArtifactsFunc.
func (mock *Manager) RemoveFromAllArtifacts(ctx context.Context, labelID int64) error {
	callInfo := struct {
		Ctx     context.Context
		LabelID int64
	}{
		Ctx:     ctx,
		LabelID: labelID,
	}
	mock.lockRemoveFromAllArtifacts.Lock()
	mock.calls.RemoveFromAllArtifacts = append(mock.calls.RemoveFromAllArtifacts, callInfo)
	mock.lockRemoveFromAllArtifacts.Unlock()
	if mock.RemoveFromAllArtifactsFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.RemoveFromAllArtifactsFunc(ctx, labelID)
}

// RemoveFromAllArtifactsCalls gets all the calls that were made to RemoveFromAllArtifacts.
// Check the length with:
//
//	len(mockedManager.RemoveFromAllArtifactsCalls())
func (mock *Manager) RemoveFromAllArtifactsCalls() []struct {
	Ctx     context.Context
	LabelID int64
} {
	var calls []struct {
		Ctx     context.Context
		LabelID int64
	}
	mock.lockRemoveFromAllArtifacts.RLock()
	calls = mock.calls.RemoveFromAllArtifacts
	mock.lockRemoveFromAllArtifacts.RUnlock()
	return calls
}

// ResetRemoveFromAllArtifactsCalls reset all the calls that were made to RemoveFromAllArtifacts.
func (mock *Manager) ResetRemoveFromAllArtifactsCalls() {
	mock.lockRemoveFromAllArtifacts.Lock()
	mock.calls.RemoveFromAllArtifacts = nil
	mock.lockRemoveFromAllArtifacts.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, label *model.Label) error {
	callInfo := struct {
		Ctx   context.Context
		Label *model.Label
	}{
		Ctx:   ctx,
		Label: label,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, label)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx   context.Context
	Label *model.Label
} {
	var calls []struct {
		Ctx   context.Context
		Label *model.Label
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockAddTo.Lock()
	mock.calls.AddTo = nil
	mock.lockAddTo.Unlock()

	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockListByArtifact.Lock()
	mock.calls.ListByArtifact = nil
	mock.lockListByArtifact.Unlock()

	mock.lockRemoveAllFrom.Lock()
	mock.calls.RemoveAllFrom = nil
	mock.lockRemoveAllFrom.Unlock()

	mock.lockRemoveFrom.Lock()
	mock.calls.RemoveFrom = nil
	mock.lockRemoveFrom.Unlock()

	mock.lockRemoveFromAllArtifacts.Lock()
	mock.calls.RemoveFromAllArtifacts = nil
	mock.lockRemoveFromAllArtifacts.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
