// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package reg

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/reg/adapter"
	"github.com/goharbor/harbor/src/pkg/reg/model"
)

// Manager is a mock implementation of reg.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked reg.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, registry *model.Registry) (int64, error) {
//				panic("mock out the Create method")
//			},
//			CreateAdapterFunc: func(ctx context.Context, registry *model.Registry) (adapter.Adapter, error) {
//				panic("mock out the CreateAdapter method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*model.Registry, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*model.Registry, error) {
//				panic("mock out the List method")
//			},
//			ListRegistryProviderInfosFunc: func(ctx context.Context) (map[string]*model.AdapterPattern, error) {
//				panic("mock out the ListRegistryProviderInfos method")
//			},
//			ListRegistryProviderTypesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the ListRegistryProviderTypes method")
//			},
//			UpdateFunc: func(ctx context.Context, registry *model.Registry, props ...string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedManager in code that requires reg.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, registry *model.Registry) (int64, error)

	// CreateAdapterFunc mocks the CreateAdapter method.
	CreateAdapterFunc func(ctx context.Context, registry *model.Registry) (adapter.Adapter, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*model.Registry, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*model.Registry, error)

	// ListRegistryProviderInfosFunc mocks the ListRegistryProviderInfos method.
	ListRegistryProviderInfosFunc func(ctx context.Context) (map[string]*model.AdapterPattern, error)

	// ListRegistryProviderTypesFunc mocks the ListRegistryProviderTypes method.
	ListRegistryProviderTypesFunc func(ctx context.Context) ([]string, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, registry *model.Registry, props ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Registry is the registry argument value.
			Registry *model.Registry
		}
		// CreateAdapter holds details about calls to the CreateAdapter method.
		CreateAdapter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Registry is the registry argument value.
			Registry *model.Registry
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListRegistryProviderInfos holds details about calls to the ListRegistryProviderInfos method.
		ListRegistryProviderInfos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListRegistryProviderTypes holds details about calls to the ListRegistryProviderTypes method.
		ListRegistryProviderTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Registry is the registry argument value.
			Registry *model.Registry
			// Props is the props argument value.
			Props []string
		}
	}
	lockCount                     sync.RWMutex
	lockCreate                    sync.RWMutex
	lockCreateAdapter             sync.RWMutex
	lockDelete                    sync.RWMutex
	lockGet                       sync.RWMutex
	lockList                      sync.RWMutex
	lockListRegistryProviderInfos sync.RWMutex
	lockListRegistryProviderTypes sync.RWMutex
	lockUpdate                    sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			count int64
			err   error
		)
		return count, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, registry *model.Registry) (int64, error) {
	callInfo := struct {
		Ctx      context.Context
		Registry *model.Registry
	}{
		Ctx:      ctx,
		Registry: registry,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, registry)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx      context.Context
	Registry *model.Registry
} {
	var calls []struct {
		Ctx      context.Context
		Registry *model.Registry
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// CreateAdapter calls CreateAdapterFunc.
func (mock *Manager) CreateAdapter(ctx context.Context, registry *model.Registry) (adapter.Adapter, error) {
	callInfo := struct {
		Ctx      context.Context
		Registry *model.Registry
	}{
		Ctx:      ctx,
		Registry: registry,
	}
	mock.lockCreateAdapter.Lock()
	mock.calls.CreateAdapter = append(mock.calls.CreateAdapter, callInfo)
	mock.lockCreateAdapter.Unlock()
	if mock.CreateAdapterFunc == nil {
		var (
			adapter1 adapter.Adapter
			err      error
		)
		return adapter1, err
	}
	return mock.CreateAdapterFunc(ctx, registry)
}

// CreateAdapterCalls gets all the calls that were made to CreateAdapter.
// Check the length with:
//
//	len(mockedManager.CreateAdapterCalls())
func (mock *Manager) CreateAdapterCalls() []struct {
	Ctx      context.Context
	Registry *model.Registry
} {
	var calls []struct {
		Ctx      context.Context
		Registry *model.Registry
	}
	mock.lockCreateAdapter.RLock()
	calls = mock.calls.CreateAdapter
	mock.lockCreateAdapter.RUnlock()
	return calls
}

// ResetCreateAdapterCalls reset all the calls that were made to CreateAdapter.
func (mock *Manager) ResetCreateAdapterCalls() {
	mock.lockCreateAdapter.Lock()
	mock.calls.CreateAdapter = nil
	mock.lockCreateAdapter.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*model.Registry, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			registry *model.Registry
			err      error
		)
		return registry, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*model.Registry, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			registries []*model.Registry
			err        error
		)
		return registries, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ListRegistryProviderInfos calls ListRegistryProviderInfosFunc.
func (mock *Manager) ListRegistryProviderInfos(ctx context.Context) (map[string]*model.AdapterPattern, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRegistryProviderInfos.Lock()
	mock.calls.ListRegistryProviderInfos = append(mock.calls.ListRegistryProviderInfos, callInfo)
	mock.lockListRegistryProviderInfos.Unlock()
	if mock.ListRegistryProviderInfosFunc == nil {
		var (
			infos map[string]*model.AdapterPattern
			err   error
		)
		return infos, err
	}
	return mock.ListRegistryProviderInfosFunc(ctx)
}

// ListRegistryProviderInfosCalls gets all the calls that were made to ListRegistryProviderInfos.
// Check the length with:
//
//	len(mockedManager.ListRegistryProviderInfosCalls())
func (mock *Manager) ListRegistryProviderInfosCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRegistryProviderInfos.RLock()
	calls = mock.calls.ListRegistryProviderInfos
	mock.lockListRegistryProviderInfos.RUnlock()
	return calls
}

// ResetListRegistryProviderInfosCalls reset all the calls that were made to ListRegistryProviderInfos.
func (mock *Manager) ResetListRegistryProviderInfosCalls() {
	mock.lockListRegistryProviderInfos.Lock()
	mock.calls.ListRegistryProviderInfos = nil
	mock.lockListRegistryProviderInfos.Unlock()
}

// ListRegistryProviderTypes calls ListRegistryProviderTypesFunc.
func (mock *Manager) ListRegistryProviderTypes(ctx context.Context) ([]string, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRegistryProviderTypes.Lock()
	mock.calls.ListRegistryProviderTypes = append(mock.calls.ListRegistryProviderTypes, callInfo)
	mock.lockListRegistryProviderTypes.Unlock()
	if mock.ListRegistryProviderTypesFunc == nil {
		var (
			types []string
			err   error
		)
		return types, err
	}
	return mock.ListRegistryProviderTypesFunc(ctx)
}

// ListRegistryProviderTypesCalls gets all the calls that were made to ListRegistryProviderTypes.
// Check the length with:
//
//	len(mockedManager.ListRegistryProviderTypesCalls())
func (mock *Manager) ListRegistryProviderTypesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRegistryProviderTypes.RLock()
	calls = mock.calls.ListRegistryProviderTypes
	mock.lockListRegistryProviderTypes.RUnlock()
	return calls
}

// ResetListRegistryProviderTypesCalls reset all the calls that were made to ListRegistryProviderTypes.
func (mock *Manager) ResetListRegistryProviderTypesCalls() {
	mock.lockListRegistryProviderTypes.Lock()
	mock.calls.ListRegistryProviderTypes = nil
	mock.lockListRegistryProviderTypes.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, registry *model.Registry, props ...string) error {
	callInfo := struct {
		Ctx      context.Context
		Registry *model.Registry
		Props    []string
	}{
		Ctx:      ctx,
		Registry: registry,
		Props:    props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, registry, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx      context.Context
	Registry *model.Registry
	Props    []string
} {
	var calls []struct {
		Ctx      context.Context
		Registry *model.Registry
		Props    []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockCreateAdapter.Lock()
	mock.calls.CreateAdapter = nil
	mock.lockCreateAdapter.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockListRegistryProviderInfos.Lock()
	mock.calls.ListRegistryProviderInfos = nil
	mock.lockListRegistryProviderInfos.Unlock()

	mock.lockListRegistryProviderTypes.Lock()
	mock.calls.ListRegistryProviderTypes = nil
	mock.lockListRegistryProviderTypes.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
