// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package retention

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/retention"
	"github.com/goharbor/harbor/src/pkg/retention/policy"
)

// Controller is a mock implementation of retention.Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked retention.Controller
//		mockedController := &Controller{
//			CreateRetentionFunc: func(ctx context.Context, p *policy.Metadata) (int64, error) {
//				panic("mock out the CreateRetention method")
//			},
//			DeleteRetentionFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRetention method")
//			},
//			DeleteRetentionByProjectFunc: func(ctx context.Context, projectID int64) error {
//				panic("mock out the DeleteRetentionByProject method")
//			},
//			GetRetentionFunc: func(ctx context.Context, id int64) (*policy.Metadata, error) {
//				panic("mock out the GetRetention method")
//			},
//			GetRetentionExecFunc: func(ctx context.Context, eid int64) (*retention.Execution, error) {
//				panic("mock out the GetRetentionExec method")
//			},
//			GetRetentionExecTaskFunc: func(ctx context.Context, taskID int64) (*retention.Task, error) {
//				panic("mock out the GetRetentionExecTask method")
//			},
//			GetRetentionExecTaskLogFunc: func(ctx context.Context, taskID int64) ([]byte, error) {
//				panic("mock out the GetRetentionExecTaskLog method")
//			},
//			GetTotalOfRetentionExecTasksFunc: func(ctx context.Context, executionID int64) (int64, error) {
//				panic("mock out the GetTotalOfRetentionExecTasks method")
//			},
//			GetTotalOfRetentionExecsFunc: func(ctx context.Context, policyID int64) (int64, error) {
//				panic("mock out the GetTotalOfRetentionExecs method")
//			},
//			ListRetentionExecTasksFunc: func(ctx context.Context, executionID int64, query *q.Query) ([]*retention.Task, error) {
//				panic("mock out the ListRetentionExecTasks method")
//			},
//			ListRetentionExecsFunc: func(ctx context.Context, policyID int64, query *q.Query) ([]*retention.Execution, error) {
//				panic("mock out the ListRetentionExecs method")
//			},
//			OperateRetentionExecFunc: func(ctx context.Context, eid int64, action string) error {
//				panic("mock out the OperateRetentionExec method")
//			},
//			TriggerRetentionExecFunc: func(ctx context.Context, policyID int64, trigger string, dryRun bool) (int64, error) {
//				panic("mock out the TriggerRetentionExec method")
//			},
//			UpdateRetentionFunc: func(ctx context.Context, p *policy.Metadata) error {
//				panic("mock out the UpdateRetention method")
//			},
//		}
//
//		// use mockedController in code that requires retention.Controller
//		// and then make assertions.
//
//	}
type Controller struct {
	// CreateRetentionFunc mocks the CreateRetention method.
	CreateRetentionFunc func(ctx context.Context, p *policy.Metadata) (int64, error)

	// DeleteRetentionFunc mocks the DeleteRetention method.
	DeleteRetentionFunc func(ctx context.Context, id int64) error

	// DeleteRetentionByProjectFunc mocks the DeleteRetentionByProject method.
	DeleteRetentionByProjectFunc func(ctx context.Context, projectID int64) error

	// GetRetentionFunc mocks the GetRetention method.
	GetRetentionFunc func(ctx context.Context, id int64) (*policy.Metadata, error)

	// GetRetentionExecFunc mocks the GetRetentionExec method.
	GetRetentionExecFunc func(ctx context.Context, eid int64) (*retention.Execution, error)

	// GetRetentionExecTaskFunc mocks the GetRetentionExecTask method.
	GetRetentionExecTaskFunc func(ctx context.Context, taskID int64) (*retention.Task, error)

	// GetRetentionExecTaskLogFunc mocks the GetRetentionExecTaskLog method.
	GetRetentionExecTaskLogFunc func(ctx context.Context, taskID int64) ([]byte, error)

	// GetTotalOfRetentionExecTasksFunc mocks the GetTotalOfRetentionExecTasks method.
	GetTotalOfRetentionExecTasksFunc func(ctx context.Context, executionID int64) (int64, error)

	// GetTotalOfRetentionExecsFunc mocks the GetTotalOfRetentionExecs method.
	GetTotalOfRetentionExecsFunc func(ctx context.Context, policyID int64) (int64, error)

	// ListRetentionExecTasksFunc mocks the ListRetentionExecTasks method.
	ListRetentionExecTasksFunc func(ctx context.Context, executionID int64, query *q.Query) ([]*retention.Task, error)

	// ListRetentionExecsFunc mocks the ListRetentionExecs method.
	ListRetentionExecsFunc func(ctx context.Context, policyID int64, query *q.Query) ([]*retention.Execution, error)

	// OperateRetentionExecFunc mocks the OperateRetentionExec method.
	OperateRetentionExecFunc func(ctx context.Context, eid int64, action string) error

	// TriggerRetentionExecFunc mocks the TriggerRetentionExec method.
	TriggerRetentionExecFunc func(ctx context.Context, policyID int64, trigger string, dryRun bool) (int64, error)

	// UpdateRetentionFunc mocks the UpdateRetention method.
	UpdateRetentionFunc func(ctx context.Context, p *policy.Metadata) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateRetention holds details about calls to the CreateRetention method.
		CreateRetention []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *policy.Metadata
		}
		// DeleteRetention holds details about calls to the DeleteRetention method.
		DeleteRetention []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteRetentionByProject holds details about calls to the DeleteRetentionByProject method.
		DeleteRetentionByProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// GetRetention holds details about calls to the GetRetention method.
		GetRetention []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetRetentionExec holds details about calls to the GetRetentionExec method.
		GetRetentionExec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Eid is the eid argument value.
			Eid int64
		}
		// GetRetentionExecTask holds details about calls to the GetRetentionExecTask method.
		GetRetentionExecTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TaskID is the taskID argument value.
			TaskID int64
		}
		// GetRetentionExecTaskLog holds details about calls to the GetRetentionExecTaskLog method.
		GetRetentionExecTaskLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TaskID is the taskID argument value.
			TaskID int64
		}
		// GetTotalOfRetentionExecTasks holds details about calls to the GetTotalOfRetentionExecTasks method.
		GetTotalOfRetentionExecTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExecutionID is the executionID argument value.
			ExecutionID int64
		}
		// GetTotalOfRetentionExecs holds details about calls to the GetTotalOfRetentionExecs method.
		GetTotalOfRetentionExecs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
		}
		// ListRetentionExecTasks holds details about calls to the ListRetentionExecTasks method.
		ListRetentionExecTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExecutionID is the executionID argument value.
			ExecutionID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// ListRetentionExecs holds details about calls to the ListRetentionExecs method.
		ListRetentionExecs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// OperateRetentionExec holds details about calls to the OperateRetentionExec method.
		OperateRetentionExec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Eid is the eid argument value.
			Eid int64
			// Action is the action argument value.
			Action string
		}
		// TriggerRetentionExec holds details about calls to the TriggerRetentionExec method.
		TriggerRetentionExec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
			// Trigger is the trigger argument value.
			Trigger string
			// DryRun is the dryRun argument value.
			DryRun bool
		}
		// UpdateRetention holds details about calls to the UpdateRetention method.
		UpdateRetention []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P *policy.Metadata
		}
	}
	lockCreateRetention              sync.RWMutex
	lockDeleteRetention              sync.RWMutex
	lockDeleteRetentionByProject     sync.RWMutex
	lockGetRetention                 sync.RWMutex
	lockGetRetentionExec             sync.RWMutex
	lockGetRetentionExecTask         sync.RWMutex
	lockGetRetentionExecTaskLog      sync.RWMutex
	lockGetTotalOfRetentionExecTasks sync.RWMutex
	lockGetTotalOfRetentionExecs     sync.RWMutex
	lockListRetentionExecTasks       sync.RWMutex
	lockListRetentionExecs           sync.RWMutex
	lockOperateRetentionExec         sync.RWMutex
	lockTriggerRetentionExec         sync.RWMutex
	lockUpdateRetention              sync.RWMutex
}

// CreateRetention calls CreateRetentionFunc.
func (mock *Controller) CreateRetention(ctx context.Context, p *policy.Metadata) (int64, error) {
	callInfo := struct {
		Ctx context.Context
		P   *policy.Metadata
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockCreateRetention.Lock()
	mock.calls.CreateRetention = append(mock.calls.CreateRetention, callInfo)
	mock.lockCreateRetention.Unlock()
	if mock.CreateRetentionFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CreateRetentionFunc(ctx, p)
}

// CreateRetentionCalls gets all the calls that were made to CreateRetention.
// Check the length with:
//
//	len(mockedController.CreateRetentionCalls())
func (mock *Controller) CreateRetentionCalls() []struct {
	Ctx context.Context
	P   *policy.Metadata
} {
	var calls []struct {
		Ctx context.Context
		P   *policy.Metadata
	}
	mock.lockCreateRetention.RLock()
	calls = mock.calls.CreateRetention
	mock.lockCreateRetention.RUnlock()
	return calls
}

// ResetCreateRetentionCalls reset all the calls that were made to CreateRetention.
func (mock *Controller) ResetCreateRetentionCalls() {
	mock.lockCreateRetention.Lock()
	mock.calls.CreateRetention = nil
	mock.lockCreateRetention.Unlock()
}

// DeleteRetention calls DeleteRetentionFunc.
func (mock *Controller) DeleteRetention(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRetention.Lock()
	mock.calls.DeleteRetention = append(mock.calls.DeleteRetention, callInfo)
	mock.lockDeleteRetention.Unlock()
	if mock.DeleteRetentionFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteRetentionFunc(ctx, id)
}

// DeleteRetentionCalls gets all the calls that were made to DeleteRetention.
// Check the length with:
//
//	len(mockedController.DeleteRetentionCalls())
func (mock *Controller) DeleteRetentionCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRetention.RLock()
	calls = mock.calls.DeleteRetention
	mock.lockDeleteRetention.RUnlock()
	return calls
}

// ResetDeleteRetentionCalls reset all the calls that were made to DeleteRetention.
func (mock *Controller) ResetDeleteRetentionCalls() {
	mock.lockDeleteRetention.Lock()
	mock.calls.DeleteRetention = nil
	mock.lockDeleteRetention.Unlock()
}

// DeleteRetentionByProject calls DeleteRetentionByProjectFunc.
func (mock *Controller) DeleteRetentionByProject(ctx context.Context, projectID int64) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockDeleteRetentionByProject.Lock()
	mock.calls.DeleteRetentionByProject = append(mock.calls.DeleteRetentionByProject, callInfo)
	mock.lockDeleteRetentionByProject.Unlock()
	if mock.DeleteRetentionByProjectFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteRetentionByProjectFunc(ctx, projectID)
}

// DeleteRetentionByProjectCalls gets all the calls that were made to DeleteRetentionByProject.
// Check the length with:
//
//	len(mockedController.DeleteRetentionByProjectCalls())
func (mock *Controller) DeleteRetentionByProjectCalls() []struct {
	Ctx       context.Context
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
	}
	mock.lockDeleteRetentionByProject.RLock()
	calls = mock.calls.DeleteRetentionByProject
	mock.lockDeleteRetentionByProject.RUnlock()
	return calls
}

// ResetDeleteRetentionByProjectCalls reset all the calls that were made to DeleteRetentionByProject.
func (mock *Controller) ResetDeleteRetentionByProjectCalls() {
	mock.lockDeleteRetentionByProject.Lock()
	mock.calls.DeleteRetentionByProject = nil
	mock.lockDeleteRetentionByProject.Unlock()
}

// GetRetention calls GetRetentionFunc.
func (mock *Controller) GetRetention(ctx context.Context, id int64) (*policy.Metadata, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRetention.Lock()
	mock.calls.GetRetention = append(mock.calls.GetRetention, callInfo)
	mock.lockGetRetention.Unlock()
	if mock.GetRetentionFunc == nil {
		var (
			metadata *policy.Metadata
			err      error
		)
		return metadata, err
	}
	return mock.GetRetentionFunc(ctx, id)
}

// GetRetentionCalls gets all the calls that were made to GetRetention.
// Check the length with:
//
//	len(mockedController.GetRetentionCalls())
func (mock *Controller) GetRetentionCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetRetention.RLock()
	calls = mock.calls.GetRetention
	mock.lockGetRetention.RUnlock()
	return calls
}

// ResetGetRetentionCalls reset all the calls that were made to GetRetention.
func (mock *Controller) ResetGetRetentionCalls() {
	mock.lockGetRetention.Lock()
	mock.calls.GetRetention = nil
	mock.lockGetRetention.Unlock()
}

// GetRetentionExec calls GetRetentionExecFunc.
func (mock *Controller) GetRetentionExec(ctx context.Context, eid int64) (*retention.Execution, error) {
	callInfo := struct {
		Ctx context.Context
		Eid int64
	}{
		Ctx: ctx,
		Eid: eid,
	}
	mock.lockGetRetentionExec.Lock()
	mock.calls.GetRetentionExec = append(mock.calls.GetRetentionExec, callInfo)
	mock.lockGetRetentionExec.Unlock()
	if mock.GetRetentionExecFunc == nil {
		var (
			execution *retention.Execution
			err       error
		)
		return execution, err
	}
	return mock.GetRetentionExecFunc(ctx, eid)
}

// GetRetentionExecCalls gets all the calls that were made to GetRetentionExec.
// Check the length with:
//
//	len(mockedController.GetRetentionExecCalls())
func (mock *Controller) GetRetentionExecCalls() []struct {
	Ctx context.Context
	Eid int64
} {
	var calls []struct {
		Ctx context.Context
		Eid int64
	}
	mock.lockGetRetentionExec.RLock()
	calls = mock.calls.GetRetentionExec
	mock.lockGetRetentionExec.RUnlock()
	return calls
}

// ResetGetRetentionExecCalls reset all the calls that were made to GetRetentionExec.
func (mock *Controller) ResetGetRetentionExecCalls() {
	mock.lockGetRetentionExec.Lock()
	mock.calls.GetRetentionExec = nil
	mock.lockGetRetentionExec.Unlock()
}

// GetRetentionExecTask calls GetRetentionExecTaskFunc.
func (mock *Controller) GetRetentionExecTask(ctx context.Context, taskID int64) (*retention.Task, error) {
	callInfo := struct {
		Ctx    context.Context
		TaskID int64
	}{
		Ctx:    ctx,
		TaskID: taskID,
	}
	mock.lockGetRetentionExecTask.Lock()
	mock.calls.GetRetentionExecTask = append(mock.calls.GetRetentionExecTask, callInfo)
	mock.lockGetRetentionExecTask.Unlock()
	if mock.GetRetentionExecTaskFunc == nil {
		var (
			task *retention.Task
			err  error
		)
		return task, err
	}
	return mock.GetRetentionExecTaskFunc(ctx, taskID)
}

// GetRetentionExecTaskCalls gets all the calls that were made to GetRetentionExecTask.
// Check the length with:
//
//	len(mockedController.GetRetentionExecTaskCalls())
func (mock *Controller) GetRetentionExecTaskCalls() []struct {
	Ctx    context.Context
	TaskID int64
} {
	var calls []struct {
		Ctx    context.Context
		TaskID int64
	}
	mock.lockGetRetentionExecTask.RLock()
	calls = mock.calls.GetRetentionExecTask
	mock.lockGetRetentionExecTask.RUnlock()
	return calls
}

// ResetGetRetentionExecTaskCalls reset all the calls that were made to GetRetentionExecTask.
func (mock *Controller) ResetGetRetentionExecTaskCalls() {
	mock.lockGetRetentionExecTask.Lock()
	mock.calls.GetRetentionExecTask = nil
	mock.lockGetRetentionExecTask.Unlock()
}

// GetRetentionExecTaskLog calls GetRetentionExecTaskLogFunc.
func (mock *Controller) GetRetentionExecTaskLog(ctx context.Context, taskID int64) ([]byte, error) {
	callInfo := struct {
		Ctx    context.Context
		TaskID int64
	}{
		Ctx:    ctx,
		TaskID: taskID,
	}
	mock.lockGetRetentionExecTaskLog.Lock()
	mock.calls.GetRetentionExecTaskLog = append(mock.calls.GetRetentionExecTaskLog, callInfo)
	mock.lockGetRetentionExecTaskLog.Unlock()
	if mock.GetRetentionExecTaskLogFunc == nil {
		var (
			bytes []byte
			err   error
		)
		return bytes, err
	}
	return mock.GetRetentionExecTaskLogFunc(ctx, taskID)
}

// GetRetentionExecTaskLogCalls gets all the calls that were made to GetRetentionExecTaskLog.
// Check the length with:
//
//	len(mockedController.GetRetentionExecTaskLogCalls())
func (mock *Controller) GetRetentionExecTaskLogCalls() []struct {
	Ctx    context.Context
	TaskID int64
} {
	var calls []struct {
		Ctx    context.Context
		TaskID int64
	}
	mock.lockGetRetentionExecTaskLog.RLock()
	calls = mock.calls.GetRetentionExecTaskLog
	mock.lockGetRetentionExecTaskLog.RUnlock()
	return calls
}

// ResetGetRetentionExecTaskLogCalls reset all the calls that were made to GetRetentionExecTaskLog.
func (mock *Controller) ResetGetRetentionExecTaskLogCalls() {
	mock.lockGetRetentionExecTaskLog.Lock()
	mock.calls.GetRetentionExecTaskLog = nil
	mock.lockGetRetentionExecTaskLog.Unlock()
}

// GetTotalOfRetentionExecTasks calls GetTotalOfRetentionExecTasksFunc.
func (mock *Controller) GetTotalOfRetentionExecTasks(ctx context.Context, executionID int64) (int64, error) {
	callInfo := struct {
		Ctx         context.Context
		ExecutionID int64
	}{
		Ctx:         ctx,
		ExecutionID: executionID,
	}
	mock.lockGetTotalOfRetentionExecTasks.Lock()
	mock.calls.GetTotalOfRetentionExecTasks = append(mock.calls.GetTotalOfRetentionExecTasks, callInfo)
	mock.lockGetTotalOfRetentionExecTasks.Unlock()
	if mock.GetTotalOfRetentionExecTasksFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.GetTotalOfRetentionExecTasksFunc(ctx, executionID)
}

// GetTotalOfRetentionExecTasksCalls gets all the calls that were made to GetTotalOfRetentionExecTasks.
// Check the length with:
//
//	len(mockedController.GetTotalOfRetentionExecTasksCalls())
func (mock *Controller) GetTotalOfRetentionExecTasksCalls() []struct {
	Ctx         context.Context
	ExecutionID int64
} {
	var calls []struct {
		Ctx         context.Context
		ExecutionID int64
	}
	mock.lockGetTotalOfRetentionExecTasks.RLock()
	calls = mock.calls.GetTotalOfRetentionExecTasks
	mock.lockGetTotalOfRetentionExecTasks.RUnlock()
	return calls
}

// ResetGetTotalOfRetentionExecTasksCalls reset all the calls that were made to GetTotalOfRetentionExecTasks.
func (mock *Controller) ResetGetTotalOfRetentionExecTasksCalls() {
	mock.lockGetTotalOfRetentionExecTasks.Lock()
	mock.calls.GetTotalOfRetentionExecTasks = nil
	mock.lockGetTotalOfRetentionExecTasks.Unlock()
}

// GetTotalOfRetentionExecs calls GetTotalOfRetentionExecsFunc.
func (mock *Controller) GetTotalOfRetentionExecs(ctx context.Context, policyID int64) (int64, error) {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
	}{
		Ctx:      ctx,
		PolicyID: policyID,
	}
	mock.lockGetTotalOfRetentionExecs.Lock()
	mock.calls.GetTotalOfRetentionExecs = append(mock.calls.GetTotalOfRetentionExecs, callInfo)
	mock.lockGetTotalOfRetentionExecs.Unlock()
	if mock.GetTotalOfRetentionExecsFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.GetTotalOfRetentionExecsFunc(ctx, policyID)
}

// GetTotalOfRetentionExecsCalls gets all the calls that were made to GetTotalOfRetentionExecs.
// Check the length with:
//
//	len(mockedController.GetTotalOfRetentionExecsCalls())
func (mock *Controller) GetTotalOfRetentionExecsCalls() []struct {
	Ctx      context.Context
	PolicyID int64
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
	}
	mock.lockGetTotalOfRetentionExecs.RLock()
	calls = mock.calls.GetTotalOfRetentionExecs
	mock.lockGetTotalOfRetentionExecs.RUnlock()
	return calls
}

// ResetGetTotalOfRetentionExecsCalls reset all the calls that were made to GetTotalOfRetentionExecs.
func (mock *Controller) ResetGetTotalOfRetentionExecsCalls() {
	mock.lockGetTotalOfRetentionExecs.Lock()
	mock.calls.GetTotalOfRetentionExecs = nil
	mock.lockGetTotalOfRetentionExecs.Unlock()
}

// ListRetentionExecTasks calls ListRetentionExecTasksFunc.
func (mock *Controller) ListRetentionExecTasks(ctx context.Context, executionID int64, query *q.Query) ([]*retention.Task, error) {
	callInfo := struct {
		Ctx         context.Context
		ExecutionID int64
		Query       *q.Query
	}{
		Ctx:         ctx,
		ExecutionID: executionID,
		Query:       query,
	}
	mock.lockListRetentionExecTasks.Lock()
	mock.calls.ListRetentionExecTasks = append(mock.calls.ListRetentionExecTasks, callInfo)
	mock.lockListRetentionExecTasks.Unlock()
	if mock.ListRetentionExecTasksFunc == nil {
		var (
			tasks []*retention.Task
			err   error
		)
		return tasks, err
	}
	return mock.ListRetentionExecTasksFunc(ctx, executionID, query)
}

// ListRetentionExecTasksCalls gets all the calls that were made to ListRetentionExecTasks.
// Check the length with:
//
//	len(mockedController.ListRetentionExecTasksCalls())
func (mock *Controller) ListRetentionExecTasksCalls() []struct {
	Ctx         context.Context
	ExecutionID int64
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ExecutionID int64
		Query       *q.Query
	}
	mock.lockListRetentionExecTasks.RLock()
	calls = mock.calls.ListRetentionExecTasks
	mock.lockListRetentionExecTasks.RUnlock()
	return calls
}

// ResetListRetentionExecTasksCalls reset all the calls that were made to ListRetentionExecTasks.
func (mock *Controller) ResetListRetentionExecTasksCalls() {
	mock.lockListRetentionExecTasks.Lock()
	mock.calls.ListRetentionExecTasks = nil
	mock.lockListRetentionExecTasks.Unlock()
}

// ListRetentionExecs calls ListRetentionExecsFunc.
func (mock *Controller) ListRetentionExecs(ctx context.Context, policyID int64, query *q.Query) ([]*retention.Execution, error) {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
		Query    *q.Query
	}{
		Ctx:      ctx,
		PolicyID: policyID,
		Query:    query,
	}
	mock.lockListRetentionExecs.Lock()
	mock.calls.ListRetentionExecs = append(mock.calls.ListRetentionExecs, callInfo)
	mock.lockListRetentionExecs.Unlock()
	if mock.ListRetentionExecsFunc == nil {
		var (
			executions []*retention.Execution
			err        error
		)
		return executions, err
	}
	return mock.ListRetentionExecsFunc(ctx, policyID, query)
}

// ListRetentionExecsCalls gets all the calls that were made to ListRetentionExecs.
// Check the length with:
//
//	len(mockedController.ListRetentionExecsCalls())
func (mock *Controller) ListRetentionExecsCalls() []struct {
	Ctx      context.Context
	PolicyID int64
	Query    *q.Query
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
		Query    *q.Query
	}
	mock.lockListRetentionExecs.RLock()
	calls = mock.calls.ListRetentionExecs
	mock.lockListRetentionExecs.RUnlock()
	return calls
}

// ResetListRetentionExecsCalls reset all the calls that were made to ListRetentionExecs.
func (mock *Controller) ResetListRetentionExecsCalls() {
	mock.lockListRetentionExecs.Lock()
	mock.calls.ListRetentionExecs = nil
	mock.lockListRetentionExecs.Unlock()
}

// OperateRetentionExec calls OperateRetentionExecFunc.
func (mock *Controller) OperateRetentionExec(ctx context.Context, eid int64, action string) error {
	callInfo := struct {
		Ctx    context.Context
		Eid    int64
		Action string
	}{
		Ctx:    ctx,
		Eid:    eid,
		Action: action,
	}
	mock.lockOperateRetentionExec.Lock()
	mock.calls.OperateRetentionExec = append(mock.calls.OperateRetentionExec, callInfo)
	mock.lockOperateRetentionExec.Unlock()
	if mock.OperateRetentionExecFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.OperateRetentionExecFunc(ctx, eid, action)
}

// OperateRetentionExecCalls gets all the calls that were made to OperateRetentionExec.
// Check the length with:
//
//	len(mockedController.OperateRetentionExecCalls())
func (mock *Controller) OperateRetentionExecCalls() []struct {
	Ctx    context.Context
	Eid    int64
	Action string
} {
	var calls []struct {
		Ctx    context.Context
		Eid    int64
		Action string
	}
	mock.lockOperateRetentionExec.RLock()
	calls = mock.calls.OperateRetentionExec
	mock.lockOperateRetentionExec.RUnlock()
	return calls
}

// ResetOperateRetentionExecCalls reset all the calls that were made to OperateRetentionExec.
func (mock *Controller) ResetOperateRetentionExecCalls() {
	mock.lockOperateRetentionExec.Lock()
	mock.calls.OperateRetentionExec = nil
	mock.lockOperateRetentionExec.Unlock()
}

// TriggerRetentionExec calls TriggerRetentionExecFunc.
func (mock *Controller) TriggerRetentionExec(ctx context.Context, policyID int64, trigger string, dryRun bool) (int64, error) {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
		Trigger  string
		DryRun   bool
	}{
		Ctx:      ctx,
		PolicyID: policyID,
		Trigger:  trigger,
		DryRun:   dryRun,
	}
	mock.lockTriggerRetentionExec.Lock()
	mock.calls.TriggerRetentionExec = append(mock.calls.TriggerRetentionExec, callInfo)
	mock.lockTriggerRetentionExec.Unlock()
	if mock.TriggerRetentionExecFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.TriggerRetentionExecFunc(ctx, policyID, trigger, dryRun)
}

// TriggerRetentionExecCalls gets all the calls that were made to TriggerRetentionExec.
// Check the length with:
//
//	len(mockedController.TriggerRetentionExecCalls())
func (mock *Controller) TriggerRetentionExecCalls() []struct {
	Ctx      context.Context
	PolicyID int64
	Trigger  string
	DryRun   bool
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
		Trigger  string
		DryRun   bool
	}
	mock.lockTriggerRetentionExec.RLock()
	calls = mock.calls.TriggerRetentionExec
	mock.lockTriggerRetentionExec.RUnlock()
	return calls
}

// ResetTriggerRetentionExecCalls reset all the calls that were made to TriggerRetentionExec.
func (mock *Controller) ResetTriggerRetentionExecCalls() {
	mock.lockTriggerRetentionExec.Lock()
	mock.calls.TriggerRetentionExec = nil
	mock.lockTriggerRetentionExec.Unlock()
}

// UpdateRetention calls UpdateRetentionFunc.
func (mock *Controller) UpdateRetention(ctx context.Context, p *policy.Metadata) error {
	callInfo := struct {
		Ctx context.Context
		P   *policy.Metadata
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockUpdateRetention.Lock()
	mock.calls.UpdateRetention = append(mock.calls.UpdateRetention, callInfo)
	mock.lockUpdateRetention.Unlock()
	if mock.UpdateRetentionFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateRetentionFunc(ctx, p)
}

// UpdateRetentionCalls gets all the calls that were made to UpdateRetention.
// Check the length with:
//
//	len(mockedController.UpdateRetentionCalls())
func (mock *Controller) UpdateRetentionCalls() []struct {
	Ctx context.Context
	P   *policy.Metadata
} {
	var calls []struct {
		Ctx context.Context
		P   *policy.Metadata
	}
	mock.lockUpdateRetention.RLock()
	calls = mock.calls.UpdateRetention
	mock.lockUpdateRetention.RUnlock()
	return calls
}

// ResetUpdateRetentionCalls reset all the calls that were made to UpdateRetention.
func (mock *Controller) ResetUpdateRetentionCalls() {
	mock.lockUpdateRetention.Lock()
	mock.calls.UpdateRetention = nil
	mock.lockUpdateRetention.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Controller) ResetCalls() {
	mock.lockCreateRetention.Lock()
	mock.calls.CreateRetention = nil
	mock.lockCreateRetention.Unlock()

	mock.lockDeleteRetention.Lock()
	mock.calls.DeleteRetention = nil
	mock.lockDeleteRetention.Unlock()

	mock.lockDeleteRetentionByProject.Lock()
	mock.calls.DeleteRetentionByProject = nil
	mock.lockDeleteRetentionByProject.Unlock()

	mock.lockGetRetention.Lock()
	mock.calls.GetRetention = nil
	mock.lockGetRetention.Unlock()

	mock.lockGetRetentionExec.Lock()
	mock.calls.GetRetentionExec = nil
	mock.lockGetRetentionExec.Unlock()

	mock.lockGetRetentionExecTask.Lock()
	mock.calls.GetRetentionExecTask = nil
	mock.lockGetRetentionExecTask.Unlock()

	mock.lockGetRetentionExecTaskLog.Lock()
	mock.calls.GetRetentionExecTaskLog = nil
	mock.lockGetRetentionExecTaskLog.Unlock()

	mock.lockGetTotalOfRetentionExecTasks.Lock()
	mock.calls.GetTotalOfRetentionExecTasks = nil
	mock.lockGetTotalOfRetentionExecTasks.Unlock()

	mock.lockGetTotalOfRetentionExecs.Lock()
	mock.calls.GetTotalOfRetentionExecs = nil
	mock.lockGetTotalOfRetentionExecs.Unlock()

	mock.lockListRetentionExecTasks.Lock()
	mock.calls.ListRetentionExecTasks = nil
	mock.lockListRetentionExecTasks.Unlock()

	mock.lockListRetentionExecs.Lock()
	mock.calls.ListRetentionExecs = nil
	mock.lockListRetentionExecs.Unlock()

	mock.lockOperateRetentionExec.Lock()
	mock.calls.OperateRetentionExec = nil
	mock.lockOperateRetentionExec.Unlock()

	mock.lockTriggerRetentionExec.Lock()
	mock.calls.TriggerRetentionExec = nil
	mock.lockTriggerRetentionExec.Unlock()

	mock.lockUpdateRetention.Lock()
	mock.calls.UpdateRetention = nil
	mock.lockUpdateRetention.Unlock()
}
