// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package allowlist

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/pkg/allowlist/models"
)

// Manager is a mock implementation of allowlist.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked allowlist.Manager
//		mockedManager := &Manager{
//			CreateEmptyFunc: func(ctx context.Context, projectID int64) error {
//				panic("mock out the CreateEmpty method")
//			},
//			GetFunc: func(ctx context.Context, projectID int64) (*models.CVEAllowlist, error) {
//				panic("mock out the Get method")
//			},
//			GetSysFunc: func(ctx context.Context) (*models.CVEAllowlist, error) {
//				panic("mock out the GetSys method")
//			},
//			SetFunc: func(ctx context.Context, projectID int64, list models.CVEAllowlist) error {
//				panic("mock out the Set method")
//			},
//			SetSysFunc: func(ctx context.Context, list models.CVEAllowlist) error {
//				panic("mock out the SetSys method")
//			},
//		}
//
//		// use mockedManager in code that requires allowlist.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CreateEmptyFunc mocks the CreateEmpty method.
	CreateEmptyFunc func(ctx context.Context, projectID int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, projectID int64) (*models.CVEAllowlist, error)

	// GetSysFunc mocks the GetSys method.
	GetSysFunc func(ctx context.Context) (*models.CVEAllowlist, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, projectID int64, list models.CVEAllowlist) error

	// SetSysFunc mocks the SetSys method.
	SetSysFunc func(ctx context.Context, list models.CVEAllowlist) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateEmpty holds details about calls to the CreateEmpty method.
		CreateEmpty []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// GetSys holds details about calls to the GetSys method.
		GetSys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// List is the list argument value.
			List models.CVEAllowlist
		}
		// SetSys holds details about calls to the SetSys method.
		SetSys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// List is the list argument value.
			List models.CVEAllowlist
		}
	}
	lockCreateEmpty sync.RWMutex
	lockGet         sync.RWMutex
	lockGetSys      sync.RWMutex
	lockSet         sync.RWMutex
	lockSetSys      sync.RWMutex
}

// CreateEmpty calls CreateEmptyFunc.
func (mock *Manager) CreateEmpty(ctx context.Context, projectID int64) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockCreateEmpty.Lock()
	mock.calls.CreateEmpty = append(mock.calls.CreateEmpty, callInfo)
	mock.lockCreateEmpty.Unlock()
	if mock.CreateEmptyFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.CreateEmptyFunc(ctx, projectID)
}

// CreateEmptyCalls gets all the calls that were made to CreateEmpty.
// Check the length with:
//
//	len(mockedManager.CreateEmptyCalls())
func (mock *Manager) CreateEmptyCalls() []struct {
	Ctx       context.Context
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
	}
	mock.lockCreateEmpty.RLock()
	calls = mock.calls.CreateEmpty
	mock.lockCreateEmpty.RUnlock()
	return calls
}

// ResetCreateEmptyCalls reset all the calls that were made to CreateEmpty.
func (mock *Manager) ResetCreateEmptyCalls() {
	mock.lockCreateEmpty.Lock()
	mock.calls.CreateEmpty = nil
	mock.lockCreateEmpty.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, projectID int64) (*models.CVEAllowlist, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			cVEAllowlist *models.CVEAllowlist
			err          error
		)
		return cVEAllowlist, err
	}
	return mock.GetFunc(ctx, projectID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx       context.Context
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetSys calls GetSysFunc.
func (mock *Manager) GetSys(ctx context.Context) (*models.CVEAllowlist, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSys.Lock()
	mock.calls.GetSys = append(mock.calls.GetSys, callInfo)
	mock.lockGetSys.Unlock()
	if mock.GetSysFunc == nil {
		var (
			cVEAllowlist *models.CVEAllowlist
			err          error
		)
		return cVEAllowlist, err
	}
	return mock.GetSysFunc(ctx)
}

// GetSysCalls gets all the calls that were made to GetSys.
// Check the length with:
//
//	len(mockedManager.GetSysCalls())
func (mock *Manager) GetSysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSys.RLock()
	calls = mock.calls.GetSys
	mock.lockGetSys.RUnlock()
	return calls
}

// ResetGetSysCalls reset all the calls that were made to GetSys.
func (mock *Manager) ResetGetSysCalls() {
	mock.lockGetSys.Lock()
	mock.calls.GetSys = nil
	mock.lockGetSys.Unlock()
}

// Set calls SetFunc.
func (mock *Manager) Set(ctx context.Context, projectID int64, list models.CVEAllowlist) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		List      models.CVEAllowlist
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		List:      list,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	if mock.SetFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SetFunc(ctx, projectID, list)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedManager.SetCalls())
func (mock *Manager) SetCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	List      models.CVEAllowlist
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		List      models.CVEAllowlist
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// ResetSetCalls reset all the calls that were made to Set.
func (mock *Manager) ResetSetCalls() {
	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}

// SetSys calls SetSysFunc.
func (mock *Manager) SetSys(ctx context.Context, list models.CVEAllowlist) error {
	callInfo := struct {
		Ctx  context.Context
		List models.CVEAllowlist
	}{
		Ctx:  ctx,
		List: list,
	}
	mock.lockSetSys.Lock()
	mock.calls.SetSys = append(mock.calls.SetSys, callInfo)
	mock.lockSetSys.Unlock()
	if mock.SetSysFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SetSysFunc(ctx, list)
}

// SetSysCalls gets all the calls that were made to SetSys.
// Check the length with:
//
//	len(mockedManager.SetSysCalls())
func (mock *Manager) SetSysCalls() []struct {
	Ctx  context.Context
	List models.CVEAllowlist
} {
	var calls []struct {
		Ctx  context.Context
		List models.CVEAllowlist
	}
	mock.lockSetSys.RLock()
	calls = mock.calls.SetSys
	mock.lockSetSys.RUnlock()
	return calls
}

// ResetSetSysCalls reset all the calls that were made to SetSys.
func (mock *Manager) ResetSetSysCalls() {
	mock.lockSetSys.Lock()
	mock.calls.SetSys = nil
	mock.lockSetSys.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCreateEmpty.Lock()
	mock.calls.CreateEmpty = nil
	mock.lockCreateEmpty.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetSys.Lock()
	mock.calls.GetSys = nil
	mock.lockGetSys.Unlock()

	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()

	mock.lockSetSys.Lock()
	mock.calls.SetSys = nil
	mock.lockSetSys.Unlock()
}
