{{- if and .Values.exporter.enabled .Values.exporter.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "harbor.fullname" . }}-exporter"
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "exporter") | nindent 4 }}
  {{- with (include "harbor.annotations" (dict "root" . "local" nil)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "harbor.toEnvVars" (dict "values" .Values.exporter.secret "prefix" "" "isSecret" true) | nindent 2 }}
{{- end }}
