{{- if and .Values.ingress.tls .Values.ingress.autoGenCert }}
{{- $secretName := include "harbor.ingress.secret" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $certHost := include "harbor.ingress.primaryHost" . }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secretName }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
{{- if $existingSecret }}
  tls.crt: {{ index $existingSecret.data "tls.crt" }}
  tls.key: {{ index $existingSecret.data "tls.key" }}
  ca.crt: {{ index $existingSecret.data "ca.crt" }}
{{- else }}
  {{- $ca := genCA "harbor-ca" 365 }}
  {{- $cert := genSignedCert $certHost nil (list $certHost) 365 $ca }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
{{- end }}
