{{- if .Values.portal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-portal
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "portal") | nindent 4 }}
  {{- with (include "harbor.annotations" (dict "root" . "local" .Values.portal.serviceAnnotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ include "harbor.portal.port" . }}
      targetPort: {{ include "harbor.portal.service.port" . }}
      protocol: TCP
  selector:
    {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "portal") | nindent 4 }}
{{- end }}
