apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-registryctl
  labels:
{{ include "harbor.labels" . | indent 4 }}
  {{- with (include "harbor.annotations" (dict "root" . "local" nil)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  _PLACEHOLDER: {{ "placeholder" | b64enc | quote }}
  {{- template "harbor.trace.jaeger.password" . }}
