{{- if and .Values.trivy.enabled .Values.trivy.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "harbor.trivy" . }}-env"
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "trivy") | nindent 4 }}
type: Opaque
data:
  {{- include "harbor.toEnvVars" (dict "values" .Values.trivy.secret "prefix" "" "isSecret" true) | nindent 2 }}
{{- end }}
