{{- if and .Values.trivy.enabled .Values.trivy.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "harbor.trivy" . }}
  labels:
    {{- include "harbor.componentLabels" (dict "root" . "component" "trivy") | nindent 4 }}
spec:
  {{- if hasKey .Values.trivy.pdb "maxUnavailable" }}
  maxUnavailable: {{ .Values.trivy.pdb.maxUnavailable }}
  {{- else if hasKey .Values.trivy.pdb "minAvailable" }}
  minAvailable: {{ .Values.trivy.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "harbor.componentSelectorLabels" (dict "root" . "component" "trivy") | nindent 6 }}
{{- end }}
