// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package robot

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/robot/model"
)

// Manager is a mock implementation of robot.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked robot.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, m *model.Robot) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			DeleteByProjectIDFunc: func(ctx context.Context, projectID int64) error {
//				panic("mock out the DeleteByProjectID method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*model.Robot, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*model.Robot, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, m *model.Robot, props ...string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedManager in code that requires robot.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, m *model.Robot) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// DeleteByProjectIDFunc mocks the DeleteByProjectID method.
	DeleteByProjectIDFunc func(ctx context.Context, projectID int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*model.Robot, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*model.Robot, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, m *model.Robot, props ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M *model.Robot
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteByProjectID holds details about calls to the DeleteByProjectID method.
		DeleteByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M *model.Robot
			// Props is the props argument value.
			Props []string
		}
	}
	lockCount             sync.RWMutex
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockDeleteByProjectID sync.RWMutex
	lockGet               sync.RWMutex
	lockList              sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, m *model.Robot) (int64, error) {
	callInfo := struct {
		Ctx context.Context
		M   *model.Robot
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CreateFunc(ctx, m)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx context.Context
	M   *model.Robot
} {
	var calls []struct {
		Ctx context.Context
		M   *model.Robot
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// DeleteByProjectID calls DeleteByProjectIDFunc.
func (mock *Manager) DeleteByProjectID(ctx context.Context, projectID int64) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockDeleteByProjectID.Lock()
	mock.calls.DeleteByProjectID = append(mock.calls.DeleteByProjectID, callInfo)
	mock.lockDeleteByProjectID.Unlock()
	if mock.DeleteByProjectIDFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteByProjectIDFunc(ctx, projectID)
}

// DeleteByProjectIDCalls gets all the calls that were made to DeleteByProjectID.
// Check the length with:
//
//	len(mockedManager.DeleteByProjectIDCalls())
func (mock *Manager) DeleteByProjectIDCalls() []struct {
	Ctx       context.Context
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
	}
	mock.lockDeleteByProjectID.RLock()
	calls = mock.calls.DeleteByProjectID
	mock.lockDeleteByProjectID.RUnlock()
	return calls
}

// ResetDeleteByProjectIDCalls reset all the calls that were made to DeleteByProjectID.
func (mock *Manager) ResetDeleteByProjectIDCalls() {
	mock.lockDeleteByProjectID.Lock()
	mock.calls.DeleteByProjectID = nil
	mock.lockDeleteByProjectID.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*model.Robot, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			robot *model.Robot
			err   error
		)
		return robot, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*model.Robot, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			robots []*model.Robot
			err    error
		)
		return robots, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, m *model.Robot, props ...string) error {
	callInfo := struct {
		Ctx   context.Context
		M     *model.Robot
		Props []string
	}{
		Ctx:   ctx,
		M:     m,
		Props: props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, m, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx   context.Context
	M     *model.Robot
	Props []string
} {
	var calls []struct {
		Ctx   context.Context
		M     *model.Robot
		Props []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDeleteByProjectID.Lock()
	mock.calls.DeleteByProjectID = nil
	mock.lockDeleteByProjectID.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
