apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: harbor-next-bootc
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/container-registry/harbor-next.git
  ref:
    branch: bootc
  secretRef:
    name: flux-git-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-harbor-core
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-core-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-harbor-jobservice
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-jobservice-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-harbor-registry
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-registry-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-harbor-registryctl
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-registryctl-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-harbor-portal
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-portal-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-harbor-exporter
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-exporter-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-trivy-adapter
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-trivy-adapter-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bootc-grype-scanner
  namespace: flux-system
spec:
  image: 8gears.container-registry.com/8gcr-dev/harbor-grype-scanner-bootc
  interval: 1m
  provider: generic
  secretRef:
    name: harbor-bootc-pull
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-harbor-core
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-harbor-core
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-harbor-jobservice
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-harbor-jobservice
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-harbor-registry
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-harbor-registry
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-harbor-registryctl
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-harbor-registryctl
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-harbor-portal
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-harbor-portal
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-harbor-exporter
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-harbor-exporter
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-trivy-adapter
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-trivy-adapter
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bootc-grype-scanner
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bootc-grype-scanner
  filterTags:
    pattern: ^latest$
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: harbor-next-bootc
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: harbor-next-bootc
  git:
    checkout:
      ref:
        branch: bootc
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "chore(rolling): Update bootc image digests"
    push:
      branch: bootc
  update:
    path: ./deploy/flux/bootc
    strategy: Setters
