apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5MwpEMNk0lR8Yisx1ul3UT5BMgvku6e2/POVQrDmg7CCycUfgqqw8ybm9V4WHL7H6PyNaN9g9T6n9147En5L+2BVEYSizQ1Y/rtcBNGUNNwPNzWLjnOC7VUGM0VET4u5sC8ZSTUUGFbo1GK5l5Kn9Vqzcw01vznlrL12ogHVXif+wSOvOYf5KHQU9baszspF2G4ljmxgVoTx5QWCd8MISEgyY6bUSI/tW3vGDR0dyBB3fTLj5cUcuW73aVKVWcXICYCAq3ELoYASrDXFYj3hzui6vjM=,iv:qdqdwCqE6LAimn+fHCqNo6l1PlKACr+pFZ4UMP7WMUQ=,tag:uh8GEZcHgDVUqj8vyD+vKw==,type:str]
kind: Secret
metadata:
    name: harbor-bootc-pull
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbHk0eUtUc2hrYkM5SXl3
            VTFKWWpIaXBRSWpPU0lkVFFsNmtVeVdocFR3CkRRSEE3SUhNSWZPYnFXbHE3WnNF
            NTBrWTh1TzFnbzlVOTBYMUxYbGlZTDgKLS0tIFNMb2FoaTYzNVNqSmowc1A1UHUv
            Y3l1anlyWXJlVjBVS1JudjdBVVMrZVUKQhOqKJRYALLYU0y+p/o+/ExEvP/9cuC6
            vDW7QLNCR+JWkUmfeCyYc8u/x41QnqBWVXQMdeDm0wG9i+uP/09VUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T15:42:46Z"
    mac: ENC[AES256_GCM,data:94q3skup6G2NoTFbz/s58WJctvo1OnyLD1T9JKudTY2EHI0avBAshn0BVrP4ohtPfNGcfnF2Mfd1KvcibjZsx0Puzg/WHIJ3qHpdZb806XKT2l2QbTOM3sdpwKAoz5HzTnWGgH6ktj/nRV+4/7eXqcGa92TRiE4+szI8BTSqacY=,iv:+NX8TcNlTnt3ZFPbEMUKy7zMnTXmcZcLw90WR5fp7N0=,tag:BI2uhIoZQk12BO7hO16Y2A==,type:str]
    version: 3.13.2
