apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:aaTZ4//382qylTtWZJqAFTUOMePFYdbRd69ioMMGGDkaZbra1dm54xgMHIs2Qeq7iY3wnRPYxlNLutecPdpsKKwoCdXTV/0UwiTvDqQ964HLyEUytsqr6XaGXf4BWeuV3plFVMml/yWIBrY5aFJ+aGusvXiqfvV17WsAvBkZmm1k8v4H2hO32+UZJ5Qx8PPIKs2YW44qe8qangviRpKQNBhclFO74H+imNszeU4FUOL0CUkctiB8CfLn+9aEvhNycOcd/YQD2WV0cAbehYFUjGPL+24=,iv:N6v0gikST8PQSYvw9tzvOHG7MdXrKHiIv2z7skLkXEU=,tag:08BQOG58dHzdvgOu0bxN9Q==,type:str]
kind: Secret
metadata:
    name: harbor-bootc-pull
    namespace: 8gcr-dev-bootc
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNmVYdU1yYW5vT09EM1Mx
            L1krcFlUVm9GNy9Qa1l4ZlYva1RiWVlBM1hvClljSzM3Y1BEelNHQy9WaGs0Q2xw
            VEhFdE16dDNxTW5QSFNhbWhmK3dkcE0KLS0tIG5UMFVOc01oeUtPSHZKWU5xNEla
            S25ranBoU3VxMG9MTE9ta1ZEZXFwcWcKyVS7jdgL9wa/LkU0ykKa+hQ/7+FJtwA5
            0bh7In7OlcJtd4Gj9GWQljCDusnk0Cvh1aBpxppMwbedeOSlPy57Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T15:42:47Z"
    mac: ENC[AES256_GCM,data:QfH5JH4gWG7btn73SVq5nugKC6NDyaoer8uiUYKTpFSI47hDD9aDyGj+BQoAKd+aL5LKZf9vNiWHU6Vnspzj9Ll39fkwuL2U3YSFovxXjgGoT2rZTt17xjsykCk2nUwmVTxIKb0yGUcoz1bgUNHfas3SLeeZDXf8i4DnEMjzkw0=,iv:nEejFTnCM3hFzCu4Xh4oeASt5QvhRK/vQs6TUDTxGt0=,tag:OqzOJsDp7b/DA5oeaRllZQ==,type:str]
    version: 3.13.2
