apiVersion: v1
data:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:Thpf/h9PDsXo1EJP6XXE/g==,iv:sXtwnWHHKAL+i7oFDrA2u0GXkEqNDbIYwrc6U0y0ZO8=,tag:+XKdhQxgqReExgKSqU8Uhg==,type:str]
kind: Secret
metadata:
    name: harbor-admin
    namespace: 8gcr-dev-bootc
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b2xPOWYrSSt4bW52ekVV
            VDZuNWZiak9GeTdIamVHblBDT2Y4RVM0c3lRCjVTRlFuSVRiUlVxdC9VZll4QTlQ
            UmRpYkd5TVZhMWVtZFdoaEgvV1ZYM1UKLS0tIDJCaWhzd1doYm42MDNNckNmYUVL
            QTZLTDErSExyV0hNcEg1NDF2MkhjcDQKtp8yAGmz1Edh0Xzby5jcfpwvzpWy19eV
            qYr0QjaoN5+ChzG6aSJTlsPyEG2FEPyFhFrDBuTcFqPme9e0rx/kng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T16:04:53Z"
    mac: ENC[AES256_GCM,data:FjFn2kSA65KFwNGPeDHm6gQlLJAezp7G7UpLxXlaNvaZ6qVzyx35KfQbgCs1p1mrGVtG5WxHiavoGzJdPzGHr1JnBm/PAnn9hmpISQ+UCVaPnI1TxZqhoHRy2y3CmZYRNkGIKRoV/RVem2yAmr7t/rZCvrfvk3H7OkGdatStOSc=,iv:n54acxZAWH+XoaKUKkSiqHTf7mLXAVPqxT9PXfWUyQU=,tag:CoBAsroM7D/WSmahv8kxLw==,type:str]
    version: 3.13.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:gPDUsj3XVUlzqaqouyWApsrzQdbiaBHtgP25L1UZJQdhWgdXqL8DSTaBii0tW+JC5uYmxBWJQ/HS3Ilf,iv:d0ByQyioHdNVpZZ7okXFjWNn8+IQbwgR1nyI6MAxpEY=,tag:SfDGLd0ZiD+8LWRuBIlBdg==,type:str]
    username: ENC[AES256_GCM,data:PXM/2ebyLB4=,iv:3cMyydHFFdMep1a/xmM0E0yUFAMmJe1UtHSiEQFVMqY=,tag:ZDvphaE94WyfyMcA6oM5Yg==,type:str]
kind: Secret
metadata:
    name: harbor-db-password
    namespace: 8gcr-dev-bootc
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b2xPOWYrSSt4bW52ekVV
            VDZuNWZiak9GeTdIamVHblBDT2Y4RVM0c3lRCjVTRlFuSVRiUlVxdC9VZll4QTlQ
            UmRpYkd5TVZhMWVtZFdoaEgvV1ZYM1UKLS0tIDJCaWhzd1doYm42MDNNckNmYUVL
            QTZLTDErSExyV0hNcEg1NDF2MkhjcDQKtp8yAGmz1Edh0Xzby5jcfpwvzpWy19eV
            qYr0QjaoN5+ChzG6aSJTlsPyEG2FEPyFhFrDBuTcFqPme9e0rx/kng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T16:04:53Z"
    mac: ENC[AES256_GCM,data:FjFn2kSA65KFwNGPeDHm6gQlLJAezp7G7UpLxXlaNvaZ6qVzyx35KfQbgCs1p1mrGVtG5WxHiavoGzJdPzGHr1JnBm/PAnn9hmpISQ+UCVaPnI1TxZqhoHRy2y3CmZYRNkGIKRoV/RVem2yAmr7t/rZCvrfvk3H7OkGdatStOSc=,iv:n54acxZAWH+XoaKUKkSiqHTf7mLXAVPqxT9PXfWUyQU=,tag:CoBAsroM7D/WSmahv8kxLw==,type:str]
    version: 3.13.2
