// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package instance

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/p2p/preheat/models/provider"
)

// Manager is a mock implementation of instance.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked instance.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*provider.Instance, error) {
//				panic("mock out the Get method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (*provider.Instance, error) {
//				panic("mock out the GetByName method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*provider.Instance, error) {
//				panic("mock out the List method")
//			},
//			SaveFunc: func(ctx context.Context, inst *provider.Instance) (int64, error) {
//				panic("mock out the Save method")
//			},
//			UpdateFunc: func(ctx context.Context, inst *provider.Instance, props ...string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedManager in code that requires instance.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*provider.Instance, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (*provider.Instance, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*provider.Instance, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, inst *provider.Instance) (int64, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, inst *provider.Instance, props ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inst is the inst argument value.
			Inst *provider.Instance
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inst is the inst argument value.
			Inst *provider.Instance
			// Props is the props argument value.
			Props []string
		}
	}
	lockCount     sync.RWMutex
	lockDelete    sync.RWMutex
	lockGet       sync.RWMutex
	lockGetByName sync.RWMutex
	lockList      sync.RWMutex
	lockSave      sync.RWMutex
	lockUpdate    sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*provider.Instance, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			instance *provider.Instance
			err      error
		)
		return instance, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetByName calls GetByNameFunc.
func (mock *Manager) GetByName(ctx context.Context, name string) (*provider.Instance, error) {
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	if mock.GetByNameFunc == nil {
		var (
			instance *provider.Instance
			err      error
		)
		return instance, err
	}
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedManager.GetByNameCalls())
func (mock *Manager) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// ResetGetByNameCalls reset all the calls that were made to GetByName.
func (mock *Manager) ResetGetByNameCalls() {
	mock.lockGetByName.Lock()
	mock.calls.GetByName = nil
	mock.lockGetByName.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*provider.Instance, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			instances []*provider.Instance
			err       error
		)
		return instances, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Save calls SaveFunc.
func (mock *Manager) Save(ctx context.Context, inst *provider.Instance) (int64, error) {
	callInfo := struct {
		Ctx  context.Context
		Inst *provider.Instance
	}{
		Ctx:  ctx,
		Inst: inst,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	if mock.SaveFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.SaveFunc(ctx, inst)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedManager.SaveCalls())
func (mock *Manager) SaveCalls() []struct {
	Ctx  context.Context
	Inst *provider.Instance
} {
	var calls []struct {
		Ctx  context.Context
		Inst *provider.Instance
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// ResetSaveCalls reset all the calls that were made to Save.
func (mock *Manager) ResetSaveCalls() {
	mock.lockSave.Lock()
	mock.calls.Save = nil
	mock.lockSave.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, inst *provider.Instance, props ...string) error {
	callInfo := struct {
		Ctx   context.Context
		Inst  *provider.Instance
		Props []string
	}{
		Ctx:   ctx,
		Inst:  inst,
		Props: props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, inst, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx   context.Context
	Inst  *provider.Instance
	Props []string
} {
	var calls []struct {
		Ctx   context.Context
		Inst  *provider.Instance
		Props []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetByName.Lock()
	mock.calls.GetByName = nil
	mock.lockGetByName.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockSave.Lock()
	mock.calls.Save = nil
	mock.lockSave.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
