// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package blob

import (
	"context"
	"sync"

	"github.com/docker/distribution"
	"github.com/goharbor/harbor/src/controller/blob"
	"github.com/goharbor/harbor/src/lib/q"
	blob0 "github.com/goharbor/harbor/src/pkg/blob"
)

// Controller is a mock implementation of blob.Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked blob.Controller
//		mockedController := &Controller{
//			AssociateWithArtifactFunc: func(ctx context.Context, blobDigests []string, artifactDigest string) error {
//				panic("mock out the AssociateWithArtifact method")
//			},
//			AssociateWithProjectByDigestFunc: func(ctx context.Context, blobDigest string, projectID int64) error {
//				panic("mock out the AssociateWithProjectByDigest method")
//			},
//			AssociateWithProjectByIDFunc: func(ctx context.Context, blobID int64, projectID int64) error {
//				panic("mock out the AssociateWithProjectByID method")
//			},
//			CalculateTotalSizeFunc: func(ctx context.Context, excludeForeign bool) (int64, error) {
//				panic("mock out the CalculateTotalSize method")
//			},
//			CalculateTotalSizeByProjectFunc: func(ctx context.Context, projectID int64, excludeForeign bool) (int64, error) {
//				panic("mock out the CalculateTotalSizeByProject method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			EnsureFunc: func(ctx context.Context, digest string, contentType string, size int64) (int64, error) {
//				panic("mock out the Ensure method")
//			},
//			ExistFunc: func(ctx context.Context, digest string, options ...blob.Option) (bool, error) {
//				panic("mock out the Exist method")
//			},
//			FailFunc: func(ctx context.Context, blob1 *blob0.Blob) error {
//				panic("mock out the Fail method")
//			},
//			FindMissingAssociationsForProjectFunc: func(ctx context.Context, projectID int64, blobs []*blob0.Blob) ([]*blob0.Blob, error) {
//				panic("mock out the FindMissingAssociationsForProject method")
//			},
//			GetFunc: func(ctx context.Context, digest string, options ...blob.Option) (*blob0.Blob, error) {
//				panic("mock out the Get method")
//			},
//			GetAcceptedBlobSizeFunc: func(ctx context.Context, sessionID string) (int64, error) {
//				panic("mock out the GetAcceptedBlobSize method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*blob0.Blob, error) {
//				panic("mock out the List method")
//			},
//			SetAcceptedBlobSizeFunc: func(ctx context.Context, sessionID string, size int64) error {
//				panic("mock out the SetAcceptedBlobSize method")
//			},
//			SyncFunc: func(ctx context.Context, references []distribution.Descriptor) error {
//				panic("mock out the Sync method")
//			},
//			TouchFunc: func(ctx context.Context, blob1 *blob0.Blob) error {
//				panic("mock out the Touch method")
//			},
//			UpdateFunc: func(ctx context.Context, blob1 *blob0.Blob) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedController in code that requires blob.Controller
//		// and then make assertions.
//
//	}
type Controller struct {
	// AssociateWithArtifactFunc mocks the AssociateWithArtifact method.
	AssociateWithArtifactFunc func(ctx context.Context, blobDigests []string, artifactDigest string) error

	// AssociateWithProjectByDigestFunc mocks the AssociateWithProjectByDigest method.
	AssociateWithProjectByDigestFunc func(ctx context.Context, blobDigest string, projectID int64) error

	// AssociateWithProjectByIDFunc mocks the AssociateWithProjectByID method.
	AssociateWithProjectByIDFunc func(ctx context.Context, blobID int64, projectID int64) error

	// CalculateTotalSizeFunc mocks the CalculateTotalSize method.
	CalculateTotalSizeFunc func(ctx context.Context, excludeForeign bool) (int64, error)

	// CalculateTotalSizeByProjectFunc mocks the CalculateTotalSizeByProject method.
	CalculateTotalSizeByProjectFunc func(ctx context.Context, projectID int64, excludeForeign bool) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// EnsureFunc mocks the Ensure method.
	EnsureFunc func(ctx context.Context, digest string, contentType string, size int64) (int64, error)

	// ExistFunc mocks the Exist method.
	ExistFunc func(ctx context.Context, digest string, options ...blob.Option) (bool, error)

	// FailFunc mocks the Fail method.
	FailFunc func(ctx context.Context, blob1 *blob0.Blob) error

	// FindMissingAssociationsForProjectFunc mocks the FindMissingAssociationsForProject method.
	FindMissingAssociationsForProjectFunc func(ctx context.Context, projectID int64, blobs []*blob0.Blob) ([]*blob0.Blob, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, digest string, options ...blob.Option) (*blob0.Blob, error)

	// GetAcceptedBlobSizeFunc mocks the GetAcceptedBlobSize method.
	GetAcceptedBlobSizeFunc func(ctx context.Context, sessionID string) (int64, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*blob0.Blob, error)

	// SetAcceptedBlobSizeFunc mocks the SetAcceptedBlobSize method.
	SetAcceptedBlobSizeFunc func(ctx context.Context, sessionID string, size int64) error

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context, references []distribution.Descriptor) error

	// TouchFunc mocks the Touch method.
	TouchFunc func(ctx context.Context, blob1 *blob0.Blob) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, blob1 *blob0.Blob) error

	// calls tracks calls to the methods.
	calls struct {
		// AssociateWithArtifact holds details about calls to the AssociateWithArtifact method.
		AssociateWithArtifact []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BlobDigests is the blobDigests argument value.
			BlobDigests []string
			// ArtifactDigest is the artifactDigest argument value.
			ArtifactDigest string
		}
		// AssociateWithProjectByDigest holds details about calls to the AssociateWithProjectByDigest method.
		AssociateWithProjectByDigest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BlobDigest is the blobDigest argument value.
			BlobDigest string
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// AssociateWithProjectByID holds details about calls to the AssociateWithProjectByID method.
		AssociateWithProjectByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BlobID is the blobID argument value.
			BlobID int64
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// CalculateTotalSize holds details about calls to the CalculateTotalSize method.
		CalculateTotalSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExcludeForeign is the excludeForeign argument value.
			ExcludeForeign bool
		}
		// CalculateTotalSizeByProject holds details about calls to the CalculateTotalSizeByProject method.
		CalculateTotalSizeByProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// ExcludeForeign is the excludeForeign argument value.
			ExcludeForeign bool
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Ensure holds details about calls to the Ensure method.
		Ensure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Digest is the digest argument value.
			Digest string
			// ContentType is the contentType argument value.
			ContentType string
			// Size is the size argument value.
			Size int64
		}
		// Exist holds details about calls to the Exist method.
		Exist []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Digest is the digest argument value.
			Digest string
			// Options is the options argument value.
			Options []blob.Option
		}
		// Fail holds details about calls to the Fail method.
		Fail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Blob1 is the blob1 argument value.
			Blob1 *blob0.Blob
		}
		// FindMissingAssociationsForProject holds details about calls to the FindMissingAssociationsForProject method.
		FindMissingAssociationsForProject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Blobs is the blobs argument value.
			Blobs []*blob0.Blob
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Digest is the digest argument value.
			Digest string
			// Options is the options argument value.
			Options []blob.Option
		}
		// GetAcceptedBlobSize holds details about calls to the GetAcceptedBlobSize method.
		GetAcceptedBlobSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// SetAcceptedBlobSize holds details about calls to the SetAcceptedBlobSize method.
		SetAcceptedBlobSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID string
			// Size is the size argument value.
			Size int64
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// References is the references argument value.
			References []distribution.Descriptor
		}
		// Touch holds details about calls to the Touch method.
		Touch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Blob1 is the blob1 argument value.
			Blob1 *blob0.Blob
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Blob1 is the blob1 argument value.
			Blob1 *blob0.Blob
		}
	}
	lockAssociateWithArtifact             sync.RWMutex
	lockAssociateWithProjectByDigest      sync.RWMutex
	lockAssociateWithProjectByID          sync.RWMutex
	lockCalculateTotalSize                sync.RWMutex
	lockCalculateTotalSizeByProject       sync.RWMutex
	lockDelete                            sync.RWMutex
	lockEnsure                            sync.RWMutex
	lockExist                             sync.RWMutex
	lockFail                              sync.RWMutex
	lockFindMissingAssociationsForProject sync.RWMutex
	lockGet                               sync.RWMutex
	lockGetAcceptedBlobSize               sync.RWMutex
	lockList                              sync.RWMutex
	lockSetAcceptedBlobSize               sync.RWMutex
	lockSync                              sync.RWMutex
	lockTouch                             sync.RWMutex
	lockUpdate                            sync.RWMutex
}

// AssociateWithArtifact calls AssociateWithArtifactFunc.
func (mock *Controller) AssociateWithArtifact(ctx context.Context, blobDigests []string, artifactDigest string) error {
	callInfo := struct {
		Ctx            context.Context
		BlobDigests    []string
		ArtifactDigest string
	}{
		Ctx:            ctx,
		BlobDigests:    blobDigests,
		ArtifactDigest: artifactDigest,
	}
	mock.lockAssociateWithArtifact.Lock()
	mock.calls.AssociateWithArtifact = append(mock.calls.AssociateWithArtifact, callInfo)
	mock.lockAssociateWithArtifact.Unlock()
	if mock.AssociateWithArtifactFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AssociateWithArtifactFunc(ctx, blobDigests, artifactDigest)
}

// AssociateWithArtifactCalls gets all the calls that were made to AssociateWithArtifact.
// Check the length with:
//
//	len(mockedController.AssociateWithArtifactCalls())
func (mock *Controller) AssociateWithArtifactCalls() []struct {
	Ctx            context.Context
	BlobDigests    []string
	ArtifactDigest string
} {
	var calls []struct {
		Ctx            context.Context
		BlobDigests    []string
		ArtifactDigest string
	}
	mock.lockAssociateWithArtifact.RLock()
	calls = mock.calls.AssociateWithArtifact
	mock.lockAssociateWithArtifact.RUnlock()
	return calls
}

// ResetAssociateWithArtifactCalls reset all the calls that were made to AssociateWithArtifact.
func (mock *Controller) ResetAssociateWithArtifactCalls() {
	mock.lockAssociateWithArtifact.Lock()
	mock.calls.AssociateWithArtifact = nil
	mock.lockAssociateWithArtifact.Unlock()
}

// AssociateWithProjectByDigest calls AssociateWithProjectByDigestFunc.
func (mock *Controller) AssociateWithProjectByDigest(ctx context.Context, blobDigest string, projectID int64) error {
	callInfo := struct {
		Ctx        context.Context
		BlobDigest string
		ProjectID  int64
	}{
		Ctx:        ctx,
		BlobDigest: blobDigest,
		ProjectID:  projectID,
	}
	mock.lockAssociateWithProjectByDigest.Lock()
	mock.calls.AssociateWithProjectByDigest = append(mock.calls.AssociateWithProjectByDigest, callInfo)
	mock.lockAssociateWithProjectByDigest.Unlock()
	if mock.AssociateWithProjectByDigestFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AssociateWithProjectByDigestFunc(ctx, blobDigest, projectID)
}

// AssociateWithProjectByDigestCalls gets all the calls that were made to AssociateWithProjectByDigest.
// Check the length with:
//
//	len(mockedController.AssociateWithProjectByDigestCalls())
func (mock *Controller) AssociateWithProjectByDigestCalls() []struct {
	Ctx        context.Context
	BlobDigest string
	ProjectID  int64
} {
	var calls []struct {
		Ctx        context.Context
		BlobDigest string
		ProjectID  int64
	}
	mock.lockAssociateWithProjectByDigest.RLock()
	calls = mock.calls.AssociateWithProjectByDigest
	mock.lockAssociateWithProjectByDigest.RUnlock()
	return calls
}

// ResetAssociateWithProjectByDigestCalls reset all the calls that were made to AssociateWithProjectByDigest.
func (mock *Controller) ResetAssociateWithProjectByDigestCalls() {
	mock.lockAssociateWithProjectByDigest.Lock()
	mock.calls.AssociateWithProjectByDigest = nil
	mock.lockAssociateWithProjectByDigest.Unlock()
}

// AssociateWithProjectByID calls AssociateWithProjectByIDFunc.
func (mock *Controller) AssociateWithProjectByID(ctx context.Context, blobID int64, projectID int64) error {
	callInfo := struct {
		Ctx       context.Context
		BlobID    int64
		ProjectID int64
	}{
		Ctx:       ctx,
		BlobID:    blobID,
		ProjectID: projectID,
	}
	mock.lockAssociateWithProjectByID.Lock()
	mock.calls.AssociateWithProjectByID = append(mock.calls.AssociateWithProjectByID, callInfo)
	mock.lockAssociateWithProjectByID.Unlock()
	if mock.AssociateWithProjectByIDFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AssociateWithProjectByIDFunc(ctx, blobID, projectID)
}

// AssociateWithProjectByIDCalls gets all the calls that were made to AssociateWithProjectByID.
// Check the length with:
//
//	len(mockedController.AssociateWithProjectByIDCalls())
func (mock *Controller) AssociateWithProjectByIDCalls() []struct {
	Ctx       context.Context
	BlobID    int64
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		BlobID    int64
		ProjectID int64
	}
	mock.lockAssociateWithProjectByID.RLock()
	calls = mock.calls.AssociateWithProjectByID
	mock.lockAssociateWithProjectByID.RUnlock()
	return calls
}

// ResetAssociateWithProjectByIDCalls reset all the calls that were made to AssociateWithProjectByID.
func (mock *Controller) ResetAssociateWithProjectByIDCalls() {
	mock.lockAssociateWithProjectByID.Lock()
	mock.calls.AssociateWithProjectByID = nil
	mock.lockAssociateWithProjectByID.Unlock()
}

// CalculateTotalSize calls CalculateTotalSizeFunc.
func (mock *Controller) CalculateTotalSize(ctx context.Context, excludeForeign bool) (int64, error) {
	callInfo := struct {
		Ctx            context.Context
		ExcludeForeign bool
	}{
		Ctx:            ctx,
		ExcludeForeign: excludeForeign,
	}
	mock.lockCalculateTotalSize.Lock()
	mock.calls.CalculateTotalSize = append(mock.calls.CalculateTotalSize, callInfo)
	mock.lockCalculateTotalSize.Unlock()
	if mock.CalculateTotalSizeFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CalculateTotalSizeFunc(ctx, excludeForeign)
}

// CalculateTotalSizeCalls gets all the calls that were made to CalculateTotalSize.
// Check the length with:
//
//	len(mockedController.CalculateTotalSizeCalls())
func (mock *Controller) CalculateTotalSizeCalls() []struct {
	Ctx            context.Context
	ExcludeForeign bool
} {
	var calls []struct {
		Ctx            context.Context
		ExcludeForeign bool
	}
	mock.lockCalculateTotalSize.RLock()
	calls = mock.calls.CalculateTotalSize
	mock.lockCalculateTotalSize.RUnlock()
	return calls
}

// ResetCalculateTotalSizeCalls reset all the calls that were made to CalculateTotalSize.
func (mock *Controller) ResetCalculateTotalSizeCalls() {
	mock.lockCalculateTotalSize.Lock()
	mock.calls.CalculateTotalSize = nil
	mock.lockCalculateTotalSize.Unlock()
}

// CalculateTotalSizeByProject calls CalculateTotalSizeByProjectFunc.
func (mock *Controller) CalculateTotalSizeByProject(ctx context.Context, projectID int64, excludeForeign bool) (int64, error) {
	callInfo := struct {
		Ctx            context.Context
		ProjectID      int64
		ExcludeForeign bool
	}{
		Ctx:            ctx,
		ProjectID:      projectID,
		ExcludeForeign: excludeForeign,
	}
	mock.lockCalculateTotalSizeByProject.Lock()
	mock.calls.CalculateTotalSizeByProject = append(mock.calls.CalculateTotalSizeByProject, callInfo)
	mock.lockCalculateTotalSizeByProject.Unlock()
	if mock.CalculateTotalSizeByProjectFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CalculateTotalSizeByProjectFunc(ctx, projectID, excludeForeign)
}

// CalculateTotalSizeByProjectCalls gets all the calls that were made to CalculateTotalSizeByProject.
// Check the length with:
//
//	len(mockedController.CalculateTotalSizeByProjectCalls())
func (mock *Controller) CalculateTotalSizeByProjectCalls() []struct {
	Ctx            context.Context
	ProjectID      int64
	ExcludeForeign bool
} {
	var calls []struct {
		Ctx            context.Context
		ProjectID      int64
		ExcludeForeign bool
	}
	mock.lockCalculateTotalSizeByProject.RLock()
	calls = mock.calls.CalculateTotalSizeByProject
	mock.lockCalculateTotalSizeByProject.RUnlock()
	return calls
}

// ResetCalculateTotalSizeByProjectCalls reset all the calls that were made to CalculateTotalSizeByProject.
func (mock *Controller) ResetCalculateTotalSizeByProjectCalls() {
	mock.lockCalculateTotalSizeByProject.Lock()
	mock.calls.CalculateTotalSizeByProject = nil
	mock.lockCalculateTotalSizeByProject.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Controller) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedController.DeleteCalls())
func (mock *Controller) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Controller) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Ensure calls EnsureFunc.
func (mock *Controller) Ensure(ctx context.Context, digest string, contentType string, size int64) (int64, error) {
	callInfo := struct {
		Ctx         context.Context
		Digest      string
		ContentType string
		Size        int64
	}{
		Ctx:         ctx,
		Digest:      digest,
		ContentType: contentType,
		Size:        size,
	}
	mock.lockEnsure.Lock()
	mock.calls.Ensure = append(mock.calls.Ensure, callInfo)
	mock.lockEnsure.Unlock()
	if mock.EnsureFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.EnsureFunc(ctx, digest, contentType, size)
}

// EnsureCalls gets all the calls that were made to Ensure.
// Check the length with:
//
//	len(mockedController.EnsureCalls())
func (mock *Controller) EnsureCalls() []struct {
	Ctx         context.Context
	Digest      string
	ContentType string
	Size        int64
} {
	var calls []struct {
		Ctx         context.Context
		Digest      string
		ContentType string
		Size        int64
	}
	mock.lockEnsure.RLock()
	calls = mock.calls.Ensure
	mock.lockEnsure.RUnlock()
	return calls
}

// ResetEnsureCalls reset all the calls that were made to Ensure.
func (mock *Controller) ResetEnsureCalls() {
	mock.lockEnsure.Lock()
	mock.calls.Ensure = nil
	mock.lockEnsure.Unlock()
}

// Exist calls ExistFunc.
func (mock *Controller) Exist(ctx context.Context, digest string, options ...blob.Option) (bool, error) {
	callInfo := struct {
		Ctx     context.Context
		Digest  string
		Options []blob.Option
	}{
		Ctx:     ctx,
		Digest:  digest,
		Options: options,
	}
	mock.lockExist.Lock()
	mock.calls.Exist = append(mock.calls.Exist, callInfo)
	mock.lockExist.Unlock()
	if mock.ExistFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.ExistFunc(ctx, digest, options...)
}

// ExistCalls gets all the calls that were made to Exist.
// Check the length with:
//
//	len(mockedController.ExistCalls())
func (mock *Controller) ExistCalls() []struct {
	Ctx     context.Context
	Digest  string
	Options []blob.Option
} {
	var calls []struct {
		Ctx     context.Context
		Digest  string
		Options []blob.Option
	}
	mock.lockExist.RLock()
	calls = mock.calls.Exist
	mock.lockExist.RUnlock()
	return calls
}

// ResetExistCalls reset all the calls that were made to Exist.
func (mock *Controller) ResetExistCalls() {
	mock.lockExist.Lock()
	mock.calls.Exist = nil
	mock.lockExist.Unlock()
}

// Fail calls FailFunc.
func (mock *Controller) Fail(ctx context.Context, blob1 *blob0.Blob) error {
	callInfo := struct {
		Ctx   context.Context
		Blob1 *blob0.Blob
	}{
		Ctx:   ctx,
		Blob1: blob1,
	}
	mock.lockFail.Lock()
	mock.calls.Fail = append(mock.calls.Fail, callInfo)
	mock.lockFail.Unlock()
	if mock.FailFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.FailFunc(ctx, blob1)
}

// FailCalls gets all the calls that were made to Fail.
// Check the length with:
//
//	len(mockedController.FailCalls())
func (mock *Controller) FailCalls() []struct {
	Ctx   context.Context
	Blob1 *blob0.Blob
} {
	var calls []struct {
		Ctx   context.Context
		Blob1 *blob0.Blob
	}
	mock.lockFail.RLock()
	calls = mock.calls.Fail
	mock.lockFail.RUnlock()
	return calls
}

// ResetFailCalls reset all the calls that were made to Fail.
func (mock *Controller) ResetFailCalls() {
	mock.lockFail.Lock()
	mock.calls.Fail = nil
	mock.lockFail.Unlock()
}

// FindMissingAssociationsForProject calls FindMissingAssociationsForProjectFunc.
func (mock *Controller) FindMissingAssociationsForProject(ctx context.Context, projectID int64, blobs []*blob0.Blob) ([]*blob0.Blob, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		Blobs     []*blob0.Blob
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		Blobs:     blobs,
	}
	mock.lockFindMissingAssociationsForProject.Lock()
	mock.calls.FindMissingAssociationsForProject = append(mock.calls.FindMissingAssociationsForProject, callInfo)
	mock.lockFindMissingAssociationsForProject.Unlock()
	if mock.FindMissingAssociationsForProjectFunc == nil {
		var (
			vs  []*blob0.Blob
			err error
		)
		return vs, err
	}
	return mock.FindMissingAssociationsForProjectFunc(ctx, projectID, blobs)
}

// FindMissingAssociationsForProjectCalls gets all the calls that were made to FindMissingAssociationsForProject.
// Check the length with:
//
//	len(mockedController.FindMissingAssociationsForProjectCalls())
func (mock *Controller) FindMissingAssociationsForProjectCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	Blobs     []*blob0.Blob
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		Blobs     []*blob0.Blob
	}
	mock.lockFindMissingAssociationsForProject.RLock()
	calls = mock.calls.FindMissingAssociationsForProject
	mock.lockFindMissingAssociationsForProject.RUnlock()
	return calls
}

// ResetFindMissingAssociationsForProjectCalls reset all the calls that were made to FindMissingAssociationsForProject.
func (mock *Controller) ResetFindMissingAssociationsForProjectCalls() {
	mock.lockFindMissingAssociationsForProject.Lock()
	mock.calls.FindMissingAssociationsForProject = nil
	mock.lockFindMissingAssociationsForProject.Unlock()
}

// Get calls GetFunc.
func (mock *Controller) Get(ctx context.Context, digest string, options ...blob.Option) (*blob0.Blob, error) {
	callInfo := struct {
		Ctx     context.Context
		Digest  string
		Options []blob.Option
	}{
		Ctx:     ctx,
		Digest:  digest,
		Options: options,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			v   *blob0.Blob
			err error
		)
		return v, err
	}
	return mock.GetFunc(ctx, digest, options...)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedController.GetCalls())
func (mock *Controller) GetCalls() []struct {
	Ctx     context.Context
	Digest  string
	Options []blob.Option
} {
	var calls []struct {
		Ctx     context.Context
		Digest  string
		Options []blob.Option
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Controller) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetAcceptedBlobSize calls GetAcceptedBlobSizeFunc.
func (mock *Controller) GetAcceptedBlobSize(ctx context.Context, sessionID string) (int64, error) {
	callInfo := struct {
		Ctx       context.Context
		SessionID string
	}{
		Ctx:       ctx,
		SessionID: sessionID,
	}
	mock.lockGetAcceptedBlobSize.Lock()
	mock.calls.GetAcceptedBlobSize = append(mock.calls.GetAcceptedBlobSize, callInfo)
	mock.lockGetAcceptedBlobSize.Unlock()
	if mock.GetAcceptedBlobSizeFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.GetAcceptedBlobSizeFunc(ctx, sessionID)
}

// GetAcceptedBlobSizeCalls gets all the calls that were made to GetAcceptedBlobSize.
// Check the length with:
//
//	len(mockedController.GetAcceptedBlobSizeCalls())
func (mock *Controller) GetAcceptedBlobSizeCalls() []struct {
	Ctx       context.Context
	SessionID string
} {
	var calls []struct {
		Ctx       context.Context
		SessionID string
	}
	mock.lockGetAcceptedBlobSize.RLock()
	calls = mock.calls.GetAcceptedBlobSize
	mock.lockGetAcceptedBlobSize.RUnlock()
	return calls
}

// ResetGetAcceptedBlobSizeCalls reset all the calls that were made to GetAcceptedBlobSize.
func (mock *Controller) ResetGetAcceptedBlobSizeCalls() {
	mock.lockGetAcceptedBlobSize.Lock()
	mock.calls.GetAcceptedBlobSize = nil
	mock.lockGetAcceptedBlobSize.Unlock()
}

// List calls ListFunc.
func (mock *Controller) List(ctx context.Context, query *q.Query) ([]*blob0.Blob, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			vs  []*blob0.Blob
			err error
		)
		return vs, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedController.ListCalls())
func (mock *Controller) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Controller) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// SetAcceptedBlobSize calls SetAcceptedBlobSizeFunc.
func (mock *Controller) SetAcceptedBlobSize(ctx context.Context, sessionID string, size int64) error {
	callInfo := struct {
		Ctx       context.Context
		SessionID string
		Size      int64
	}{
		Ctx:       ctx,
		SessionID: sessionID,
		Size:      size,
	}
	mock.lockSetAcceptedBlobSize.Lock()
	mock.calls.SetAcceptedBlobSize = append(mock.calls.SetAcceptedBlobSize, callInfo)
	mock.lockSetAcceptedBlobSize.Unlock()
	if mock.SetAcceptedBlobSizeFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SetAcceptedBlobSizeFunc(ctx, sessionID, size)
}

// SetAcceptedBlobSizeCalls gets all the calls that were made to SetAcceptedBlobSize.
// Check the length with:
//
//	len(mockedController.SetAcceptedBlobSizeCalls())
func (mock *Controller) SetAcceptedBlobSizeCalls() []struct {
	Ctx       context.Context
	SessionID string
	Size      int64
} {
	var calls []struct {
		Ctx       context.Context
		SessionID string
		Size      int64
	}
	mock.lockSetAcceptedBlobSize.RLock()
	calls = mock.calls.SetAcceptedBlobSize
	mock.lockSetAcceptedBlobSize.RUnlock()
	return calls
}

// ResetSetAcceptedBlobSizeCalls reset all the calls that were made to SetAcceptedBlobSize.
func (mock *Controller) ResetSetAcceptedBlobSizeCalls() {
	mock.lockSetAcceptedBlobSize.Lock()
	mock.calls.SetAcceptedBlobSize = nil
	mock.lockSetAcceptedBlobSize.Unlock()
}

// Sync calls SyncFunc.
func (mock *Controller) Sync(ctx context.Context, references []distribution.Descriptor) error {
	callInfo := struct {
		Ctx        context.Context
		References []distribution.Descriptor
	}{
		Ctx:        ctx,
		References: references,
	}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	if mock.SyncFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SyncFunc(ctx, references)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedController.SyncCalls())
func (mock *Controller) SyncCalls() []struct {
	Ctx        context.Context
	References []distribution.Descriptor
} {
	var calls []struct {
		Ctx        context.Context
		References []distribution.Descriptor
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}

// ResetSyncCalls reset all the calls that were made to Sync.
func (mock *Controller) ResetSyncCalls() {
	mock.lockSync.Lock()
	mock.calls.Sync = nil
	mock.lockSync.Unlock()
}

// Touch calls TouchFunc.
func (mock *Controller) Touch(ctx context.Context, blob1 *blob0.Blob) error {
	callInfo := struct {
		Ctx   context.Context
		Blob1 *blob0.Blob
	}{
		Ctx:   ctx,
		Blob1: blob1,
	}
	mock.lockTouch.Lock()
	mock.calls.Touch = append(mock.calls.Touch, callInfo)
	mock.lockTouch.Unlock()
	if mock.TouchFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.TouchFunc(ctx, blob1)
}

// TouchCalls gets all the calls that were made to Touch.
// Check the length with:
//
//	len(mockedController.TouchCalls())
func (mock *Controller) TouchCalls() []struct {
	Ctx   context.Context
	Blob1 *blob0.Blob
} {
	var calls []struct {
		Ctx   context.Context
		Blob1 *blob0.Blob
	}
	mock.lockTouch.RLock()
	calls = mock.calls.Touch
	mock.lockTouch.RUnlock()
	return calls
}

// ResetTouchCalls reset all the calls that were made to Touch.
func (mock *Controller) ResetTouchCalls() {
	mock.lockTouch.Lock()
	mock.calls.Touch = nil
	mock.lockTouch.Unlock()
}

// Update calls UpdateFunc.
func (mock *Controller) Update(ctx context.Context, blob1 *blob0.Blob) error {
	callInfo := struct {
		Ctx   context.Context
		Blob1 *blob0.Blob
	}{
		Ctx:   ctx,
		Blob1: blob1,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, blob1)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedController.UpdateCalls())
func (mock *Controller) UpdateCalls() []struct {
	Ctx   context.Context
	Blob1 *blob0.Blob
} {
	var calls []struct {
		Ctx   context.Context
		Blob1 *blob0.Blob
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Controller) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Controller) ResetCalls() {
	mock.lockAssociateWithArtifact.Lock()
	mock.calls.AssociateWithArtifact = nil
	mock.lockAssociateWithArtifact.Unlock()

	mock.lockAssociateWithProjectByDigest.Lock()
	mock.calls.AssociateWithProjectByDigest = nil
	mock.lockAssociateWithProjectByDigest.Unlock()

	mock.lockAssociateWithProjectByID.Lock()
	mock.calls.AssociateWithProjectByID = nil
	mock.lockAssociateWithProjectByID.Unlock()

	mock.lockCalculateTotalSize.Lock()
	mock.calls.CalculateTotalSize = nil
	mock.lockCalculateTotalSize.Unlock()

	mock.lockCalculateTotalSizeByProject.Lock()
	mock.calls.CalculateTotalSizeByProject = nil
	mock.lockCalculateTotalSizeByProject.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockEnsure.Lock()
	mock.calls.Ensure = nil
	mock.lockEnsure.Unlock()

	mock.lockExist.Lock()
	mock.calls.Exist = nil
	mock.lockExist.Unlock()

	mock.lockFail.Lock()
	mock.calls.Fail = nil
	mock.lockFail.Unlock()

	mock.lockFindMissingAssociationsForProject.Lock()
	mock.calls.FindMissingAssociationsForProject = nil
	mock.lockFindMissingAssociationsForProject.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetAcceptedBlobSize.Lock()
	mock.calls.GetAcceptedBlobSize = nil
	mock.lockGetAcceptedBlobSize.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockSetAcceptedBlobSize.Lock()
	mock.calls.SetAcceptedBlobSize = nil
	mock.lockSetAcceptedBlobSize.Unlock()

	mock.lockSync.Lock()
	mock.calls.Sync = nil
	mock.lockSync.Unlock()

	mock.lockTouch.Lock()
	mock.calls.Touch = nil
	mock.lockTouch.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
