// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package adapter

import (
	"sync"

	"github.com/goharbor/harbor/src/pkg/reg/model"
)

// Adapter is a mock implementation of adapter.Adapter.
//
//	func TestSomethingThatUsesAdapter(t *testing.T) {
//
//		// make and configure a mocked adapter.Adapter
//		mockedAdapter := &Adapter{
//			HealthCheckFunc: func() (string, error) {
//				panic("mock out the HealthCheck method")
//			},
//			InfoFunc: func() (*model.RegistryInfo, error) {
//				panic("mock out the Info method")
//			},
//			PrepareForPushFunc: func(resources []*model.Resource) error {
//				panic("mock out the PrepareForPush method")
//			},
//		}
//
//		// use mockedAdapter in code that requires adapter.Adapter
//		// and then make assertions.
//
//	}
type Adapter struct {
	// HealthCheckFunc mocks the HealthCheck method.
	HealthCheckFunc func() (string, error)

	// InfoFunc mocks the Info method.
	InfoFunc func() (*model.RegistryInfo, error)

	// PrepareForPushFunc mocks the PrepareForPush method.
	PrepareForPushFunc func(resources []*model.Resource) error

	// calls tracks calls to the methods.
	calls struct {
		// HealthCheck holds details about calls to the HealthCheck method.
		HealthCheck []struct {
		}
		// Info holds details about calls to the Info method.
		Info []struct {
		}
		// PrepareForPush holds details about calls to the PrepareForPush method.
		PrepareForPush []struct {
			// Resources is the resources argument value.
			Resources []*model.Resource
		}
	}
	lockHealthCheck    sync.RWMutex
	lockInfo           sync.RWMutex
	lockPrepareForPush sync.RWMutex
}

// HealthCheck calls HealthCheckFunc.
func (mock *Adapter) HealthCheck() (string, error) {
	callInfo := struct {
	}{}
	mock.lockHealthCheck.Lock()
	mock.calls.HealthCheck = append(mock.calls.HealthCheck, callInfo)
	mock.lockHealthCheck.Unlock()
	if mock.HealthCheckFunc == nil {
		var (
			s   string
			err error
		)
		return s, err
	}
	return mock.HealthCheckFunc()
}

// HealthCheckCalls gets all the calls that were made to HealthCheck.
// Check the length with:
//
//	len(mockedAdapter.HealthCheckCalls())
func (mock *Adapter) HealthCheckCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHealthCheck.RLock()
	calls = mock.calls.HealthCheck
	mock.lockHealthCheck.RUnlock()
	return calls
}

// ResetHealthCheckCalls reset all the calls that were made to HealthCheck.
func (mock *Adapter) ResetHealthCheckCalls() {
	mock.lockHealthCheck.Lock()
	mock.calls.HealthCheck = nil
	mock.lockHealthCheck.Unlock()
}

// Info calls InfoFunc.
func (mock *Adapter) Info() (*model.RegistryInfo, error) {
	callInfo := struct {
	}{}
	mock.lockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	mock.lockInfo.Unlock()
	if mock.InfoFunc == nil {
		var (
			registryInfo *model.RegistryInfo
			err          error
		)
		return registryInfo, err
	}
	return mock.InfoFunc()
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//
//	len(mockedAdapter.InfoCalls())
func (mock *Adapter) InfoCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockInfo.RLock()
	calls = mock.calls.Info
	mock.lockInfo.RUnlock()
	return calls
}

// ResetInfoCalls reset all the calls that were made to Info.
func (mock *Adapter) ResetInfoCalls() {
	mock.lockInfo.Lock()
	mock.calls.Info = nil
	mock.lockInfo.Unlock()
}

// PrepareForPush calls PrepareForPushFunc.
func (mock *Adapter) PrepareForPush(resources []*model.Resource) error {
	callInfo := struct {
		Resources []*model.Resource
	}{
		Resources: resources,
	}
	mock.lockPrepareForPush.Lock()
	mock.calls.PrepareForPush = append(mock.calls.PrepareForPush, callInfo)
	mock.lockPrepareForPush.Unlock()
	if mock.PrepareForPushFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PrepareForPushFunc(resources)
}

// PrepareForPushCalls gets all the calls that were made to PrepareForPush.
// Check the length with:
//
//	len(mockedAdapter.PrepareForPushCalls())
func (mock *Adapter) PrepareForPushCalls() []struct {
	Resources []*model.Resource
} {
	var calls []struct {
		Resources []*model.Resource
	}
	mock.lockPrepareForPush.RLock()
	calls = mock.calls.PrepareForPush
	mock.lockPrepareForPush.RUnlock()
	return calls
}

// ResetPrepareForPushCalls reset all the calls that were made to PrepareForPush.
func (mock *Adapter) ResetPrepareForPushCalls() {
	mock.lockPrepareForPush.Lock()
	mock.calls.PrepareForPush = nil
	mock.lockPrepareForPush.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Adapter) ResetCalls() {
	mock.lockHealthCheck.Lock()
	mock.calls.HealthCheck = nil
	mock.lockHealthCheck.Unlock()

	mock.lockInfo.Lock()
	mock.calls.Info = nil
	mock.lockInfo.Unlock()

	mock.lockPrepareForPush.Lock()
	mock.calls.PrepareForPush = nil
	mock.lockPrepareForPush.Unlock()
}
