// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package parser

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/pkg/artifact"
)

// Parser is a mock implementation of annotation.Parser.
//
//	func TestSomethingThatUsesParser(t *testing.T) {
//
//		// make and configure a mocked annotation.Parser
//		mockedParser := &Parser{
//			ParseFunc: func(ctx context.Context, artifact1 *artifact.Artifact, manifest []byte) error {
//				panic("mock out the Parse method")
//			},
//		}
//
//		// use mockedParser in code that requires annotation.Parser
//		// and then make assertions.
//
//	}
type Parser struct {
	// ParseFunc mocks the Parse method.
	ParseFunc func(ctx context.Context, artifact1 *artifact.Artifact, manifest []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
			// Manifest is the manifest argument value.
			Manifest []byte
		}
	}
	lockParse sync.RWMutex
}

// Parse calls ParseFunc.
func (mock *Parser) Parse(ctx context.Context, artifact1 *artifact.Artifact, manifest []byte) error {
	callInfo := struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
		Manifest  []byte
	}{
		Ctx:       ctx,
		Artifact1: artifact1,
		Manifest:  manifest,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	if mock.ParseFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.ParseFunc(ctx, artifact1, manifest)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedParser.ParseCalls())
func (mock *Parser) ParseCalls() []struct {
	Ctx       context.Context
	Artifact1 *artifact.Artifact
	Manifest  []byte
} {
	var calls []struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
		Manifest  []byte
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}

// ResetParseCalls reset all the calls that were made to Parse.
func (mock *Parser) ResetParseCalls() {
	mock.lockParse.Lock()
	mock.calls.Parse = nil
	mock.lockParse.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Parser) ResetCalls() {
	mock.lockParse.Lock()
	mock.calls.Parse = nil
	mock.lockParse.Unlock()
}
