// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package artifact

import (
	"context"
	"sync"
	"time"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/artifact"
)

// Manager is a mock implementation of artifact.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked artifact.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, artifact1 *artifact.Artifact) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			DeleteReferenceFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteReference method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*artifact.Artifact, error) {
//				panic("mock out the Get method")
//			},
//			GetByDigestFunc: func(ctx context.Context, repository string, digest string) (*artifact.Artifact, error) {
//				panic("mock out the GetByDigest method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*artifact.Artifact, error) {
//				panic("mock out the List method")
//			},
//			ListReferencesFunc: func(ctx context.Context, query *q.Query) ([]*artifact.Reference, error) {
//				panic("mock out the ListReferences method")
//			},
//			ListWithLatestFunc: func(ctx context.Context, query *q.Query) ([]*artifact.Artifact, error) {
//				panic("mock out the ListWithLatest method")
//			},
//			UpdateFunc: func(ctx context.Context, artifact1 *artifact.Artifact, props ...string) error {
//				panic("mock out the Update method")
//			},
//			UpdatePullTimeFunc: func(ctx context.Context, id int64, pullTime time.Time) error {
//				panic("mock out the UpdatePullTime method")
//			},
//		}
//
//		// use mockedManager in code that requires artifact.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, artifact1 *artifact.Artifact) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// DeleteReferenceFunc mocks the DeleteReference method.
	DeleteReferenceFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*artifact.Artifact, error)

	// GetByDigestFunc mocks the GetByDigest method.
	GetByDigestFunc func(ctx context.Context, repository string, digest string) (*artifact.Artifact, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*artifact.Artifact, error)

	// ListReferencesFunc mocks the ListReferences method.
	ListReferencesFunc func(ctx context.Context, query *q.Query) ([]*artifact.Reference, error)

	// ListWithLatestFunc mocks the ListWithLatest method.
	ListWithLatestFunc func(ctx context.Context, query *q.Query) ([]*artifact.Artifact, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, artifact1 *artifact.Artifact, props ...string) error

	// UpdatePullTimeFunc mocks the UpdatePullTime method.
	UpdatePullTimeFunc func(ctx context.Context, id int64, pullTime time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteReference holds details about calls to the DeleteReference method.
		DeleteReference []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetByDigest holds details about calls to the GetByDigest method.
		GetByDigest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repository is the repository argument value.
			Repository string
			// Digest is the digest argument value.
			Digest string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListReferences holds details about calls to the ListReferences method.
		ListReferences []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListWithLatest holds details about calls to the ListWithLatest method.
		ListWithLatest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
			// Props is the props argument value.
			Props []string
		}
		// UpdatePullTime holds details about calls to the UpdatePullTime method.
		UpdatePullTime []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// PullTime is the pullTime argument value.
			PullTime time.Time
		}
	}
	lockCount           sync.RWMutex
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockDeleteReference sync.RWMutex
	lockGet             sync.RWMutex
	lockGetByDigest     sync.RWMutex
	lockList            sync.RWMutex
	lockListReferences  sync.RWMutex
	lockListWithLatest  sync.RWMutex
	lockUpdate          sync.RWMutex
	lockUpdatePullTime  sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, artifact1 *artifact.Artifact) (int64, error) {
	callInfo := struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
	}{
		Ctx:       ctx,
		Artifact1: artifact1,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, artifact1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx       context.Context
	Artifact1 *artifact.Artifact
} {
	var calls []struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// DeleteReference calls DeleteReferenceFunc.
func (mock *Manager) DeleteReference(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteReference.Lock()
	mock.calls.DeleteReference = append(mock.calls.DeleteReference, callInfo)
	mock.lockDeleteReference.Unlock()
	if mock.DeleteReferenceFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteReferenceFunc(ctx, id)
}

// DeleteReferenceCalls gets all the calls that were made to DeleteReference.
// Check the length with:
//
//	len(mockedManager.DeleteReferenceCalls())
func (mock *Manager) DeleteReferenceCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteReference.RLock()
	calls = mock.calls.DeleteReference
	mock.lockDeleteReference.RUnlock()
	return calls
}

// ResetDeleteReferenceCalls reset all the calls that were made to DeleteReference.
func (mock *Manager) ResetDeleteReferenceCalls() {
	mock.lockDeleteReference.Lock()
	mock.calls.DeleteReference = nil
	mock.lockDeleteReference.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*artifact.Artifact, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			artifact1 *artifact.Artifact
			err       error
		)
		return artifact1, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetByDigest calls GetByDigestFunc.
func (mock *Manager) GetByDigest(ctx context.Context, repository string, digest string) (*artifact.Artifact, error) {
	callInfo := struct {
		Ctx        context.Context
		Repository string
		Digest     string
	}{
		Ctx:        ctx,
		Repository: repository,
		Digest:     digest,
	}
	mock.lockGetByDigest.Lock()
	mock.calls.GetByDigest = append(mock.calls.GetByDigest, callInfo)
	mock.lockGetByDigest.Unlock()
	if mock.GetByDigestFunc == nil {
		var (
			artifact1 *artifact.Artifact
			err       error
		)
		return artifact1, err
	}
	return mock.GetByDigestFunc(ctx, repository, digest)
}

// GetByDigestCalls gets all the calls that were made to GetByDigest.
// Check the length with:
//
//	len(mockedManager.GetByDigestCalls())
func (mock *Manager) GetByDigestCalls() []struct {
	Ctx        context.Context
	Repository string
	Digest     string
} {
	var calls []struct {
		Ctx        context.Context
		Repository string
		Digest     string
	}
	mock.lockGetByDigest.RLock()
	calls = mock.calls.GetByDigest
	mock.lockGetByDigest.RUnlock()
	return calls
}

// ResetGetByDigestCalls reset all the calls that were made to GetByDigest.
func (mock *Manager) ResetGetByDigestCalls() {
	mock.lockGetByDigest.Lock()
	mock.calls.GetByDigest = nil
	mock.lockGetByDigest.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*artifact.Artifact, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			artifacts []*artifact.Artifact
			err       error
		)
		return artifacts, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ListReferences calls ListReferencesFunc.
func (mock *Manager) ListReferences(ctx context.Context, query *q.Query) ([]*artifact.Reference, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockListReferences.Lock()
	mock.calls.ListReferences = append(mock.calls.ListReferences, callInfo)
	mock.lockListReferences.Unlock()
	if mock.ListReferencesFunc == nil {
		var (
			references []*artifact.Reference
			err        error
		)
		return references, err
	}
	return mock.ListReferencesFunc(ctx, query)
}

// ListReferencesCalls gets all the calls that were made to ListReferences.
// Check the length with:
//
//	len(mockedManager.ListReferencesCalls())
func (mock *Manager) ListReferencesCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockListReferences.RLock()
	calls = mock.calls.ListReferences
	mock.lockListReferences.RUnlock()
	return calls
}

// ResetListReferencesCalls reset all the calls that were made to ListReferences.
func (mock *Manager) ResetListReferencesCalls() {
	mock.lockListReferences.Lock()
	mock.calls.ListReferences = nil
	mock.lockListReferences.Unlock()
}

// ListWithLatest calls ListWithLatestFunc.
func (mock *Manager) ListWithLatest(ctx context.Context, query *q.Query) ([]*artifact.Artifact, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockListWithLatest.Lock()
	mock.calls.ListWithLatest = append(mock.calls.ListWithLatest, callInfo)
	mock.lockListWithLatest.Unlock()
	if mock.ListWithLatestFunc == nil {
		var (
			artifacts []*artifact.Artifact
			err       error
		)
		return artifacts, err
	}
	return mock.ListWithLatestFunc(ctx, query)
}

// ListWithLatestCalls gets all the calls that were made to ListWithLatest.
// Check the length with:
//
//	len(mockedManager.ListWithLatestCalls())
func (mock *Manager) ListWithLatestCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockListWithLatest.RLock()
	calls = mock.calls.ListWithLatest
	mock.lockListWithLatest.RUnlock()
	return calls
}

// ResetListWithLatestCalls reset all the calls that were made to ListWithLatest.
func (mock *Manager) ResetListWithLatestCalls() {
	mock.lockListWithLatest.Lock()
	mock.calls.ListWithLatest = nil
	mock.lockListWithLatest.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, artifact1 *artifact.Artifact, props ...string) error {
	callInfo := struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
		Props     []string
	}{
		Ctx:       ctx,
		Artifact1: artifact1,
		Props:     props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, artifact1, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx       context.Context
	Artifact1 *artifact.Artifact
	Props     []string
} {
	var calls []struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
		Props     []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// UpdatePullTime calls UpdatePullTimeFunc.
func (mock *Manager) UpdatePullTime(ctx context.Context, id int64, pullTime time.Time) error {
	callInfo := struct {
		Ctx      context.Context
		ID       int64
		PullTime time.Time
	}{
		Ctx:      ctx,
		ID:       id,
		PullTime: pullTime,
	}
	mock.lockUpdatePullTime.Lock()
	mock.calls.UpdatePullTime = append(mock.calls.UpdatePullTime, callInfo)
	mock.lockUpdatePullTime.Unlock()
	if mock.UpdatePullTimeFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdatePullTimeFunc(ctx, id, pullTime)
}

// UpdatePullTimeCalls gets all the calls that were made to UpdatePullTime.
// Check the length with:
//
//	len(mockedManager.UpdatePullTimeCalls())
func (mock *Manager) UpdatePullTimeCalls() []struct {
	Ctx      context.Context
	ID       int64
	PullTime time.Time
} {
	var calls []struct {
		Ctx      context.Context
		ID       int64
		PullTime time.Time
	}
	mock.lockUpdatePullTime.RLock()
	calls = mock.calls.UpdatePullTime
	mock.lockUpdatePullTime.RUnlock()
	return calls
}

// ResetUpdatePullTimeCalls reset all the calls that were made to UpdatePullTime.
func (mock *Manager) ResetUpdatePullTimeCalls() {
	mock.lockUpdatePullTime.Lock()
	mock.calls.UpdatePullTime = nil
	mock.lockUpdatePullTime.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDeleteReference.Lock()
	mock.calls.DeleteReference = nil
	mock.lockDeleteReference.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetByDigest.Lock()
	mock.calls.GetByDigest = nil
	mock.lockGetByDigest.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockListReferences.Lock()
	mock.calls.ListReferences = nil
	mock.lockListReferences.Unlock()

	mock.lockListWithLatest.Lock()
	mock.calls.ListWithLatest = nil
	mock.lockListWithLatest.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()

	mock.lockUpdatePullTime.Lock()
	mock.calls.UpdatePullTime = nil
	mock.lockUpdatePullTime.Unlock()
}
