// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package user

import (
	"context"
	"sync"

	models0 "github.com/goharbor/harbor/src/common/models"
	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/user/models"
)

// Manager is a mock implementation of user.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked user.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query, options ...models.Option) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, user *models0.User) (int, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int) error {
//				panic("mock out the Delete method")
//			},
//			DeleteGDPRFunc: func(ctx context.Context, id int) error {
//				panic("mock out the DeleteGDPR method")
//			},
//			GenerateCheckSumFunc: func(in string) string {
//				panic("mock out the GenerateCheckSum method")
//			},
//			GetFunc: func(ctx context.Context, id int) (*models0.User, error) {
//				panic("mock out the Get method")
//			},
//			GetByNameFunc: func(ctx context.Context, username string) (*models0.User, error) {
//				panic("mock out the GetByName method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query, options ...models.Option) (models0.Users, error) {
//				panic("mock out the List method")
//			},
//			MatchLocalPasswordFunc: func(ctx context.Context, username string, password string) (*models0.User, error) {
//				panic("mock out the MatchLocalPassword method")
//			},
//			OnboardFunc: func(ctx context.Context, user *models0.User) error {
//				panic("mock out the Onboard method")
//			},
//			SearchByNameFunc: func(ctx context.Context, name string, limitSize int) (models0.Users, error) {
//				panic("mock out the SearchByName method")
//			},
//			SetSysAdminFlagFunc: func(ctx context.Context, id int, admin bool) error {
//				panic("mock out the SetSysAdminFlag method")
//			},
//			UpdatePasswordFunc: func(ctx context.Context, id int, newPassword string) error {
//				panic("mock out the UpdatePassword method")
//			},
//			UpdateProfileFunc: func(ctx context.Context, user *models0.User, col ...string) error {
//				panic("mock out the UpdateProfile method")
//			},
//		}
//
//		// use mockedManager in code that requires user.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query, options ...models.Option) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *models0.User) (int, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int) error

	// DeleteGDPRFunc mocks the DeleteGDPR method.
	DeleteGDPRFunc func(ctx context.Context, id int) error

	// GenerateCheckSumFunc mocks the GenerateCheckSum method.
	GenerateCheckSumFunc func(in string) string

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int) (*models0.User, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, username string) (*models0.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query, options ...models.Option) (models0.Users, error)

	// MatchLocalPasswordFunc mocks the MatchLocalPassword method.
	MatchLocalPasswordFunc func(ctx context.Context, username string, password string) (*models0.User, error)

	// OnboardFunc mocks the Onboard method.
	OnboardFunc func(ctx context.Context, user *models0.User) error

	// SearchByNameFunc mocks the SearchByName method.
	SearchByNameFunc func(ctx context.Context, name string, limitSize int) (models0.Users, error)

	// SetSysAdminFlagFunc mocks the SetSysAdminFlag method.
	SetSysAdminFlagFunc func(ctx context.Context, id int, admin bool) error

	// UpdatePasswordFunc mocks the UpdatePassword method.
	UpdatePasswordFunc func(ctx context.Context, id int, newPassword string) error

	// UpdateProfileFunc mocks the UpdateProfile method.
	UpdateProfileFunc func(ctx context.Context, user *models0.User, col ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
			// Options is the options argument value.
			Options []models.Option
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *models0.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// DeleteGDPR holds details about calls to the DeleteGDPR method.
		DeleteGDPR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// GenerateCheckSum holds details about calls to the GenerateCheckSum method.
		GenerateCheckSum []struct {
			// In is the in argument value.
			In string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Username is the username argument value.
			Username string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
			// Options is the options argument value.
			Options []models.Option
		}
		// MatchLocalPassword holds details about calls to the MatchLocalPassword method.
		MatchLocalPassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Username is the username argument value.
			Username string
			// Password is the password argument value.
			Password string
		}
		// Onboard holds details about calls to the Onboard method.
		Onboard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *models0.User
		}
		// SearchByName holds details about calls to the SearchByName method.
		SearchByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// LimitSize is the limitSize argument value.
			LimitSize int
		}
		// SetSysAdminFlag holds details about calls to the SetSysAdminFlag method.
		SetSysAdminFlag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
			// Admin is the admin argument value.
			Admin bool
		}
		// UpdatePassword holds details about calls to the UpdatePassword method.
		UpdatePassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
			// NewPassword is the newPassword argument value.
			NewPassword string
		}
		// UpdateProfile holds details about calls to the UpdateProfile method.
		UpdateProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *models0.User
			// Col is the col argument value.
			Col []string
		}
	}
	lockCount              sync.RWMutex
	lockCreate             sync.RWMutex
	lockDelete             sync.RWMutex
	lockDeleteGDPR         sync.RWMutex
	lockGenerateCheckSum   sync.RWMutex
	lockGet                sync.RWMutex
	lockGetByName          sync.RWMutex
	lockList               sync.RWMutex
	lockMatchLocalPassword sync.RWMutex
	lockOnboard            sync.RWMutex
	lockSearchByName       sync.RWMutex
	lockSetSysAdminFlag    sync.RWMutex
	lockUpdatePassword     sync.RWMutex
	lockUpdateProfile      sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query, options ...models.Option) (int64, error) {
	callInfo := struct {
		Ctx     context.Context
		Query   *q.Query
		Options []models.Option
	}{
		Ctx:     ctx,
		Query:   query,
		Options: options,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountFunc(ctx, query, options...)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx     context.Context
	Query   *q.Query
	Options []models.Option
} {
	var calls []struct {
		Ctx     context.Context
		Query   *q.Query
		Options []models.Option
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, user *models0.User) (int, error) {
	callInfo := struct {
		Ctx  context.Context
		User *models0.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			n   int
			err error
		)
		return n, err
	}
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx  context.Context
	User *models0.User
} {
	var calls []struct {
		Ctx  context.Context
		User *models0.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, id int) error {
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// DeleteGDPR calls DeleteGDPRFunc.
func (mock *Manager) DeleteGDPR(ctx context.Context, id int) error {
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteGDPR.Lock()
	mock.calls.DeleteGDPR = append(mock.calls.DeleteGDPR, callInfo)
	mock.lockDeleteGDPR.Unlock()
	if mock.DeleteGDPRFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteGDPRFunc(ctx, id)
}

// DeleteGDPRCalls gets all the calls that were made to DeleteGDPR.
// Check the length with:
//
//	len(mockedManager.DeleteGDPRCalls())
func (mock *Manager) DeleteGDPRCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockDeleteGDPR.RLock()
	calls = mock.calls.DeleteGDPR
	mock.lockDeleteGDPR.RUnlock()
	return calls
}

// ResetDeleteGDPRCalls reset all the calls that were made to DeleteGDPR.
func (mock *Manager) ResetDeleteGDPRCalls() {
	mock.lockDeleteGDPR.Lock()
	mock.calls.DeleteGDPR = nil
	mock.lockDeleteGDPR.Unlock()
}

// GenerateCheckSum calls GenerateCheckSumFunc.
func (mock *Manager) GenerateCheckSum(in string) string {
	callInfo := struct {
		In string
	}{
		In: in,
	}
	mock.lockGenerateCheckSum.Lock()
	mock.calls.GenerateCheckSum = append(mock.calls.GenerateCheckSum, callInfo)
	mock.lockGenerateCheckSum.Unlock()
	if mock.GenerateCheckSumFunc == nil {
		var (
			s string
		)
		return s
	}
	return mock.GenerateCheckSumFunc(in)
}

// GenerateCheckSumCalls gets all the calls that were made to GenerateCheckSum.
// Check the length with:
//
//	len(mockedManager.GenerateCheckSumCalls())
func (mock *Manager) GenerateCheckSumCalls() []struct {
	In string
} {
	var calls []struct {
		In string
	}
	mock.lockGenerateCheckSum.RLock()
	calls = mock.calls.GenerateCheckSum
	mock.lockGenerateCheckSum.RUnlock()
	return calls
}

// ResetGenerateCheckSumCalls reset all the calls that were made to GenerateCheckSum.
func (mock *Manager) ResetGenerateCheckSumCalls() {
	mock.lockGenerateCheckSum.Lock()
	mock.calls.GenerateCheckSum = nil
	mock.lockGenerateCheckSum.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int) (*models0.User, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			user *models0.User
			err  error
		)
		return user, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetByName calls GetByNameFunc.
func (mock *Manager) GetByName(ctx context.Context, username string) (*models0.User, error) {
	callInfo := struct {
		Ctx      context.Context
		Username string
	}{
		Ctx:      ctx,
		Username: username,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	if mock.GetByNameFunc == nil {
		var (
			user *models0.User
			err  error
		)
		return user, err
	}
	return mock.GetByNameFunc(ctx, username)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedManager.GetByNameCalls())
func (mock *Manager) GetByNameCalls() []struct {
	Ctx      context.Context
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Username string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// ResetGetByNameCalls reset all the calls that were made to GetByName.
func (mock *Manager) ResetGetByNameCalls() {
	mock.lockGetByName.Lock()
	mock.calls.GetByName = nil
	mock.lockGetByName.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query, options ...models.Option) (models0.Users, error) {
	callInfo := struct {
		Ctx     context.Context
		Query   *q.Query
		Options []models.Option
	}{
		Ctx:     ctx,
		Query:   query,
		Options: options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			users models0.Users
			err   error
		)
		return users, err
	}
	return mock.ListFunc(ctx, query, options...)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx     context.Context
	Query   *q.Query
	Options []models.Option
} {
	var calls []struct {
		Ctx     context.Context
		Query   *q.Query
		Options []models.Option
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// MatchLocalPassword calls MatchLocalPasswordFunc.
func (mock *Manager) MatchLocalPassword(ctx context.Context, username string, password string) (*models0.User, error) {
	callInfo := struct {
		Ctx      context.Context
		Username string
		Password string
	}{
		Ctx:      ctx,
		Username: username,
		Password: password,
	}
	mock.lockMatchLocalPassword.Lock()
	mock.calls.MatchLocalPassword = append(mock.calls.MatchLocalPassword, callInfo)
	mock.lockMatchLocalPassword.Unlock()
	if mock.MatchLocalPasswordFunc == nil {
		var (
			user *models0.User
			err  error
		)
		return user, err
	}
	return mock.MatchLocalPasswordFunc(ctx, username, password)
}

// MatchLocalPasswordCalls gets all the calls that were made to MatchLocalPassword.
// Check the length with:
//
//	len(mockedManager.MatchLocalPasswordCalls())
func (mock *Manager) MatchLocalPasswordCalls() []struct {
	Ctx      context.Context
	Username string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Username string
		Password string
	}
	mock.lockMatchLocalPassword.RLock()
	calls = mock.calls.MatchLocalPassword
	mock.lockMatchLocalPassword.RUnlock()
	return calls
}

// ResetMatchLocalPasswordCalls reset all the calls that were made to MatchLocalPassword.
func (mock *Manager) ResetMatchLocalPasswordCalls() {
	mock.lockMatchLocalPassword.Lock()
	mock.calls.MatchLocalPassword = nil
	mock.lockMatchLocalPassword.Unlock()
}

// Onboard calls OnboardFunc.
func (mock *Manager) Onboard(ctx context.Context, user *models0.User) error {
	callInfo := struct {
		Ctx  context.Context
		User *models0.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockOnboard.Lock()
	mock.calls.Onboard = append(mock.calls.Onboard, callInfo)
	mock.lockOnboard.Unlock()
	if mock.OnboardFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.OnboardFunc(ctx, user)
}

// OnboardCalls gets all the calls that were made to Onboard.
// Check the length with:
//
//	len(mockedManager.OnboardCalls())
func (mock *Manager) OnboardCalls() []struct {
	Ctx  context.Context
	User *models0.User
} {
	var calls []struct {
		Ctx  context.Context
		User *models0.User
	}
	mock.lockOnboard.RLock()
	calls = mock.calls.Onboard
	mock.lockOnboard.RUnlock()
	return calls
}

// ResetOnboardCalls reset all the calls that were made to Onboard.
func (mock *Manager) ResetOnboardCalls() {
	mock.lockOnboard.Lock()
	mock.calls.Onboard = nil
	mock.lockOnboard.Unlock()
}

// SearchByName calls SearchByNameFunc.
func (mock *Manager) SearchByName(ctx context.Context, name string, limitSize int) (models0.Users, error) {
	callInfo := struct {
		Ctx       context.Context
		Name      string
		LimitSize int
	}{
		Ctx:       ctx,
		Name:      name,
		LimitSize: limitSize,
	}
	mock.lockSearchByName.Lock()
	mock.calls.SearchByName = append(mock.calls.SearchByName, callInfo)
	mock.lockSearchByName.Unlock()
	if mock.SearchByNameFunc == nil {
		var (
			users models0.Users
			err   error
		)
		return users, err
	}
	return mock.SearchByNameFunc(ctx, name, limitSize)
}

// SearchByNameCalls gets all the calls that were made to SearchByName.
// Check the length with:
//
//	len(mockedManager.SearchByNameCalls())
func (mock *Manager) SearchByNameCalls() []struct {
	Ctx       context.Context
	Name      string
	LimitSize int
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		LimitSize int
	}
	mock.lockSearchByName.RLock()
	calls = mock.calls.SearchByName
	mock.lockSearchByName.RUnlock()
	return calls
}

// ResetSearchByNameCalls reset all the calls that were made to SearchByName.
func (mock *Manager) ResetSearchByNameCalls() {
	mock.lockSearchByName.Lock()
	mock.calls.SearchByName = nil
	mock.lockSearchByName.Unlock()
}

// SetSysAdminFlag calls SetSysAdminFlagFunc.
func (mock *Manager) SetSysAdminFlag(ctx context.Context, id int, admin bool) error {
	callInfo := struct {
		Ctx   context.Context
		ID    int
		Admin bool
	}{
		Ctx:   ctx,
		ID:    id,
		Admin: admin,
	}
	mock.lockSetSysAdminFlag.Lock()
	mock.calls.SetSysAdminFlag = append(mock.calls.SetSysAdminFlag, callInfo)
	mock.lockSetSysAdminFlag.Unlock()
	if mock.SetSysAdminFlagFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SetSysAdminFlagFunc(ctx, id, admin)
}

// SetSysAdminFlagCalls gets all the calls that were made to SetSysAdminFlag.
// Check the length with:
//
//	len(mockedManager.SetSysAdminFlagCalls())
func (mock *Manager) SetSysAdminFlagCalls() []struct {
	Ctx   context.Context
	ID    int
	Admin bool
} {
	var calls []struct {
		Ctx   context.Context
		ID    int
		Admin bool
	}
	mock.lockSetSysAdminFlag.RLock()
	calls = mock.calls.SetSysAdminFlag
	mock.lockSetSysAdminFlag.RUnlock()
	return calls
}

// ResetSetSysAdminFlagCalls reset all the calls that were made to SetSysAdminFlag.
func (mock *Manager) ResetSetSysAdminFlagCalls() {
	mock.lockSetSysAdminFlag.Lock()
	mock.calls.SetSysAdminFlag = nil
	mock.lockSetSysAdminFlag.Unlock()
}

// UpdatePassword calls UpdatePasswordFunc.
func (mock *Manager) UpdatePassword(ctx context.Context, id int, newPassword string) error {
	callInfo := struct {
		Ctx         context.Context
		ID          int
		NewPassword string
	}{
		Ctx:         ctx,
		ID:          id,
		NewPassword: newPassword,
	}
	mock.lockUpdatePassword.Lock()
	mock.calls.UpdatePassword = append(mock.calls.UpdatePassword, callInfo)
	mock.lockUpdatePassword.Unlock()
	if mock.UpdatePasswordFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdatePasswordFunc(ctx, id, newPassword)
}

// UpdatePasswordCalls gets all the calls that were made to UpdatePassword.
// Check the length with:
//
//	len(mockedManager.UpdatePasswordCalls())
func (mock *Manager) UpdatePasswordCalls() []struct {
	Ctx         context.Context
	ID          int
	NewPassword string
} {
	var calls []struct {
		Ctx         context.Context
		ID          int
		NewPassword string
	}
	mock.lockUpdatePassword.RLock()
	calls = mock.calls.UpdatePassword
	mock.lockUpdatePassword.RUnlock()
	return calls
}

// ResetUpdatePasswordCalls reset all the calls that were made to UpdatePassword.
func (mock *Manager) ResetUpdatePasswordCalls() {
	mock.lockUpdatePassword.Lock()
	mock.calls.UpdatePassword = nil
	mock.lockUpdatePassword.Unlock()
}

// UpdateProfile calls UpdateProfileFunc.
func (mock *Manager) UpdateProfile(ctx context.Context, user *models0.User, col ...string) error {
	callInfo := struct {
		Ctx  context.Context
		User *models0.User
		Col  []string
	}{
		Ctx:  ctx,
		User: user,
		Col:  col,
	}
	mock.lockUpdateProfile.Lock()
	mock.calls.UpdateProfile = append(mock.calls.UpdateProfile, callInfo)
	mock.lockUpdateProfile.Unlock()
	if mock.UpdateProfileFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateProfileFunc(ctx, user, col...)
}

// UpdateProfileCalls gets all the calls that were made to UpdateProfile.
// Check the length with:
//
//	len(mockedManager.UpdateProfileCalls())
func (mock *Manager) UpdateProfileCalls() []struct {
	Ctx  context.Context
	User *models0.User
	Col  []string
} {
	var calls []struct {
		Ctx  context.Context
		User *models0.User
		Col  []string
	}
	mock.lockUpdateProfile.RLock()
	calls = mock.calls.UpdateProfile
	mock.lockUpdateProfile.RUnlock()
	return calls
}

// ResetUpdateProfileCalls reset all the calls that were made to UpdateProfile.
func (mock *Manager) ResetUpdateProfileCalls() {
	mock.lockUpdateProfile.Lock()
	mock.calls.UpdateProfile = nil
	mock.lockUpdateProfile.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDeleteGDPR.Lock()
	mock.calls.DeleteGDPR = nil
	mock.lockDeleteGDPR.Unlock()

	mock.lockGenerateCheckSum.Lock()
	mock.calls.GenerateCheckSum = nil
	mock.lockGenerateCheckSum.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetByName.Lock()
	mock.calls.GetByName = nil
	mock.lockGetByName.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockMatchLocalPassword.Lock()
	mock.calls.MatchLocalPassword = nil
	mock.lockMatchLocalPassword.Unlock()

	mock.lockOnboard.Lock()
	mock.calls.Onboard = nil
	mock.lockOnboard.Unlock()

	mock.lockSearchByName.Lock()
	mock.calls.SearchByName = nil
	mock.lockSearchByName.Unlock()

	mock.lockSetSysAdminFlag.Lock()
	mock.calls.SetSysAdminFlag = nil
	mock.lockSetSysAdminFlag.Unlock()

	mock.lockUpdatePassword.Lock()
	mock.calls.UpdatePassword = nil
	mock.lockUpdatePassword.Unlock()

	mock.lockUpdateProfile.Lock()
	mock.calls.UpdateProfile = nil
	mock.lockUpdateProfile.Unlock()
}
