apiVersion: v1
data:
    token: ENC[AES256_GCM,data:mIYE374qdaDtJVvtFL0JxPZvsDiFxQ8wTtciK6Trt2pjbFml2KUdXRUKnJxVmoGo1VmWi3ySQsw7dxf1om0oXpkSxsxFnVOwBqdHWJu0MkoFpIE8L6DmJOasM6VqAG8Sy+XRhsQqwCEeSg7ttqGxZB3Tb3nlaJHjL5u2IiXx5yKZRmJSMONd3fHykwAzlXJOd7HZv5kJT7MWqQLrw7a/9TvOZ00EPQ42sMBvDOO/lLCslwxpfCC2RXkJ27zEeHXnyi9F063c2VFWncDItbG8yLDO2n4cbpQ6mckvL5YsIk2gRb2cFtsw0jxKv2B443F6hUcbTAqzAIDnfMY/ux6PBUoX7HJ2rpGnVDWqaYsJptmbGS814UdsNrxb58EGode/+14sxs34vzqmZ1tfHdH+nTnnMRQn5KtRN5ASrMivI04lt1Jq+h4rgopj70Qfxn+XydLM6wG5vuPSTb/MG+SYDrNl1qc=,iv:zFsFURLrNHCR/DxGPUo3GucrBFPJsw1wYGTD/bFP2Ys=,tag:KWPbAbU/NsMFcqQGR3Ud1A==,type:str]
kind: Secret
metadata:
    name: harbor-snyk
    namespace: 8gcr-dev-main
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOWdPbWI4Y3ZJSGlVSENv
            Z0ZJbG00T2dqV09hdW1BWVpTUHB2UmZyQ25NClFSbVEyR0RDbEdDWkM5T0RGZ2pD
            L05YOW56NEM4dUlnRDF2UDdqY1p4MzQKLS0tIFhGWTBSWWMrenNqOUlIaitRcWxt
            aW1VdEd0RkVtNUk5dXVaUlZIbVg4MWcKY3rSEw4c2oZpYcY7UZwMNRzdG06VS4UQ
            RCUm49WTz2RLvQG+OkUBaEtpSeQCyFMBrDMhN5873DB3FBKHPQFqiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T03:05:58Z"
    mac: ENC[AES256_GCM,data:OOPkeIOiHSSAZqGmjJK3gYkt+KR1NLF1sxnDNJuKcXKH25sk8Aik7aNyAtdFjpOH7PH/KSPxREDWPO0KdGjjOiutl0Z902HHyVK7pf1xTwuFiYaCbnwzPz1CtNzP51Ljtdr77XPRYfSVK0Zz0o/LvJuPkxfPNzBuh3eSFSgKoS0=,iv:DuakHzIJwK+dUpnSnAi5MM+EtXuxZYsW021FGrePsYU=,tag:mUsejpZEDkDd6VbGeUzK0Q==,type:str]
    version: 3.13.3
