apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:0uG5fJWC4KFllwKzljOnBcz/hAqQJ2FbaOJKr+6sgAkpPNU8n49RVM7LVa60ZJQx9AuJaCEzroTEzv2PiEo3tDoZ8qi8RaXaVpxeh9U8NI2vcIAfVMeGRg8JekWgnURFvlS3JOtcH22z6K5yiiJHMKAtBqEuyF2iKqHpeXr48We+OZ+HyxRo9J27nbH1fh4u1KB8ZMcVQPIiPRD++sE4VxDVP18/QW36JvdlD+4xgj/CA43S5eJz3eNqkx/CGjdb1CkTXzwuDqAVctM3kp8+3MwLZ7qhQ0+jepWXBO4cGb5x13er/y61upTMCSdi/Whv5Te7zGEfojHQw9a+KQTwr9jtPc5d7o32lXYe9kPhgC6UVzXZyFu1X8TzlsIRlnyJzElmf9TVIsmkeSAB5Y/CzCsjQ16TiNSpM1uU1frSQmdhSYwn,iv:7XRKJbR9EisI/6Gb2MG++UI5XndhCOcOcHo7UzlboeE=,tag:f/vZzuJ6jSyWZXXfBUDp3A==,type:str]
kind: Secret
metadata:
    name: harbor-system-pull
    namespace: 8gcr-dev-main
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cWhXeVJYN0tWS0xkTkJU
            Ym53T1paL0RMYTRiRUkxenpaNkZxeWJxblNZCktDRU9WeTljaDJldG5XbzdXQStk
            UmxsUmZDcXlHZnQyRGhRbHgxV013WDAKLS0tIFNnSzVkTmZnT24zenV2b3ppdkJR
            eXhGcUFCVVU5Ym56cUdnQnF0aGxMdHMKbcRMpV3sU6KGutlGw9z02jhYc76m+k4t
            cuaeHVc262AIsaw/NlN+El5sVY4Dsrwvh602c/NwlcU0IN83pgnPlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T19:57:05Z"
    mac: ENC[AES256_GCM,data:1XNGxz2ROPK6HwFpk1UamgaFXNvXNZhWAZG3jlsp3SOwKskcVCJdbBsIntppzega20NOk6KV6y9Zf11i8rNqM1TNwRzb2B5uZGXXfvLiytvLy68b0IOuD1HXXwzfuGnn7y3sip0eEDWSQg5Mq35tekp4fwfI6EJFBKE3Pjq9BHA=,iv:iP162+7xn0I0EtnzQcmsCxv+aB4zqOYgMII6VapVbmc=,tag:hl1IJP8ZBimwYTophqDEWA==,type:str]
    version: 3.13.1
