apiVersion: v1
kind: Secret
metadata:
    name: harbor-8gcr-pull
    namespace: 8gcr-dev-main
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:bxJrdTYMYixhBcdN++RxYQU6Zh0s2KFyZJdPQ9q8Mg3rk6iN46YTeXn+IdU3EJxWo2tMNMElYMXBvuf5NVXvoNOewN3Qn7F9XXugreb95RzvCUvATyFBkNn/mmGVCVAeNVSsR0F00emX9OhUjBSxAzK214mAAvqyB9X/hdAd3UThblE1uE4rnJWctAcghnYCQTOeAH5mCVeGYvTCC/TYWT+oiL8VAA6F0UbtN52nF/iO12Be9lftBPwicBfmq9DPGLyZDT9/KDNHQTpIJFvX59YAH0gyiIavQKQrgFSRX/3zeGtdLaaflqTIkX/Z7LsGhF8MBzKtWc36bA==,iv:J4qzFkxRUGG7hxqklzbSC8gcXvXdHFSIcTScLjyQWd8=,tag:DjrD/gi4Q3IuzXgCSbVqig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK1A2Y0RjdktRZDJIWGQw
            c3NUYzlJTytwam4xMGg5NlhzRGxjUUFjMVFBCkpJdmZhRllpNElTMWsrL0c2SnQ1
            U1ZXL3hDNXdGSHJZRWhNOTRvNXFyejAKLS0tIFRCZEVQZEFxVndsbmZxb0ZRcHUy
            WHpGTnVPb0JCc21mUVhOWWRXU09aMlkK3Lg7ToCEWVab9I4OnAVM3/XMSLq+PX4K
            J5LDA7VE8icdUJqVT4ssA1BmxEsQQND9+0605F1HcNt+U6qyufKNCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T16:28:35Z"
    mac: ENC[AES256_GCM,data:UhCkrKYlnwhmLwdKWQBo/6vJRyFV1cQiSROwdU6/bLitjNp6lq5OiGTY4DMGmUEAZNRT2e6CqaojaSPidQNaoETQT+U+vxaaU2P8BL5TYdUXz0mghA9JWpISL/Qa3+tJ1Jbf9o9TV+NLSHvv+4rYl8cVGYJRggkvtwbniyXwKC8=,iv:lDD2tG1RITvN4OdDg/aTjYzXLWqgZEdoBy8pB/K005U=,tag:JmZIv2rkPdLhPU8ra/pLbA==,type:str]
    version: 3.13.1
