apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:a8XvQnX74jord1RDZByx2eArkCpFtE8IkxXVJNHaqgx4ow3OfYMNm6Q06FHPWFEtdIIt9iiWCK3O8EKr8cWfTV1iIhspYi70fLBDmmifa4rbmGhZmu+D+8XhECD4mmnRuz61ELJQZaMLZK/ZzoXO+RGKUa1dPWwVzkhM3rcq/tvExJQXO7fn8O7vmAj4tCVSxJ44z16JE95pgPt9Kio0qdajoCfe2Fe6MVGWCRWyvVfI4oQSFcmjm/DbrPxbOFqBHftr5M0H/DIsmT1UA4zZYkBt+69hcyUFiyg8aZogbLZNbSTKm3v07PLSBYENvn0v18cej5k7S0StLXNfl3hsoWtFKpowy/shxBBdgnnvlJECgQ3kSrdH5P4UJfCnd5tASXekrx+hiaWWFFyGPcTpdf5PfTywWbkXbCKtc2rT6pgZKyXm,iv:nMOZohUFllZpTLFBXmN4cdR8rZ4ZDN+dNVGqOgJiPxw=,tag:M5Yj72sSiaR+jKoUMqLpBQ==,type:str]
kind: Secret
metadata:
    name: harbor-system-pull
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybWtiRXhYN0QzMDhOYjRr
            TlhDRUZmMVlSWHN2MjhBWncvb1dHYVpwZFFrCkRBZFNHbnFqNkFKQllMMmFxSnlO
            cWlNdWd3cGt1MmJmazJTa3JodE9YTGsKLS0tIFJoQWhCZ2RoNHV0VGZBOTZpKzA1
            STlJaUZ3emZyTXhCZmxZTFZOMVRjb0EKLW0126uMWBNuf1wnj3MFYikh7dgkkp1E
            B6O76Y+7EMtAr2TAYnXHw2LQF19QBSL9+DoQChQwIHLdocBhd+wd1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T19:57:05Z"
    mac: ENC[AES256_GCM,data:gqnLh8AEEqE0Bsxt5in2/SZdIP9WtSbBy2dn7cZR+dAQtbPczqV5yidloh2dWcqB6rwDG4O7cuR4Ijqq9wknYKPq4Q3xNBjkoS33ZwljLMvH08RfPZ3rzh716U+kP6DvVHEGOwHi5bl6CL3gRPgV5sWi39UfvteKVqMcgkhB/Bc=,iv:Gb0SVNkliJ+dOwkcacb9yhNx4+qteKDrwoQKjIxohBo=,tag:3L2IM8h7bF/iNl86sKfIjw==,type:str]
    version: 3.13.1
