apiVersion: v1
kind: Secret
metadata:
    name: harbor-8gcr-pull
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:O5hfjaVhuLiDXoR4W4O9HJVMLYYXvYdZ9AL8MW7zVVnaco06GQglHf3Ll5IdfF5Vnse74iCjrwGROke6BqvmItixpxgV0LKqiigfiykn8fYjQzzry0234hCZIQ9lQadEp0rqoAxAeZfb1LUfC4qPGcYelYCwcMuq1qi7kYEPbW4w6+j4ZXNNsf5Xdg6I1FRQSohKrQiYpMrCTMaIPRCFLvSUColLlGLrYHM9fbgmSyyg8Ta1kGE5F5hyxVza5TisjRxR8F+R9WBCjuNPPKk0wcDe7Bjouwrt1iOGHH7FNjdNpOv+e2NeiZ3gJlDZVS3CtInCA3DuWutDgw==,iv:+DEDe94ZLN2nJh10YJOaHLEMV4l0naa05JKAfCLbDWA=,tag:ZkPps5TJzSYgLAZRCx0x3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN2VUOVpCZFAyekNZVHpp
            NkpHMFFnNDJCcHRIdnRkR2YxWmxNZUsyMkc4CjNXdmRzQ0taanVyVVlPdHZkOVFo
            Y3hpV0pNMmxjK1Y3dmUraGRWRDFDMmcKLS0tIEo2OG95K09jajVkUGRxdUZzRmFH
            VXJZV2lqMzFFSlloK3htaitQYjFXczgK9ZYLJuWL1JJufOInFe5buvoGu7hzzaMB
            awWWQibVPtQ3Dncexpem6Zm0NYN1gYUcuK1u6Px3Z0VVldv/Z3ejIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T16:28:35Z"
    mac: ENC[AES256_GCM,data:c6CqxYdGgnjDWIeturrt483MCtOhlaNhlBR6mAdv4DZb2i+PZAANAIx3KepLfzZ7U0BkyvtYePNzZkOYTZLLKHgFRLN1OF2K2kWaFkajk3lNnmdN9lDvsg51xNGjM27Z6abjNWnPsoKWUAbij7sb6Hb9LaMj+sQsYaikI3yyrh0=,iv:y8w0VuP56IuKKjgeDwydFtvDLQBapNFZZxH5b/nGToI=,tag:Oa8aCXuzUcpSXd8ckWRJ0Q==,type:str]
    version: 3.13.1
