apiVersion: v1
kind: Secret
metadata:
    name: harbor-admin
    namespace: 8gcr-dev-main
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:CRiXcDGPP+pzYldpdEqNf+cq+VfxeCpc,iv:ERnk7rL8zwKYAJOje/XCq9VZiWWdg9/RbXczxNRIrsU=,tag:SPM82nYVEAUxyaGPHsJf/w==,type:str]
sops:
    age:
        - recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVVluWHVaRitMeDU4eWox
            SXpCN2FLa0JHYnQwOVdibmM0bEowamRaY0NFCktYSjRSRlQ2WE05VFRBdkhLQWJM
            RDREMkwrYkdiSFArUzg2TWZaejNOcEUKLS0tIFpxK0RiUTRFM1IzZVpmUmZQcWZv
            Q1NNUUZCc2NzSTU5a0lZckFnMUlyRUkKvlqDF0y9c7q18hmwFDYoMNG2Q8JJgBII
            B2U6Sdsto/RBRxIpNn7lJsx9TP6uGQ1a5etyshvUBJ/Riv137BOG6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T13:07:10Z"
    mac: ENC[AES256_GCM,data:q9s76Hb9ZkzmAcUa06FA56V1x+eHxeHtAPVUAAj1i4KZdLNR6LsLklo6YQfLObUxQm7l4wieli9/41tK/C3/KWT9RZpSwmN2CHYONQa8obhpBsS6y2/ukNAW4ysybUUQ5q0MjoKxucZ0I2+C0SUwPg5ZN+jGemQWKRlYBuzdcvs=,iv:VhdvGhy6Ly2+IfgRaGvlUNVBnINsB2puTsBi1ZE1pP4=,tag:kDE9+wxdQ8IePD2839ou8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: harbor-database
    namespace: 8gcr-dev-main
stringData:
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:T/olgazA7ErZ+4J0Pruesd4hF4ttgZ1siylWZgE=,iv:TNYg1dDVEMveTKH+mQvD+2YGkMBxO5LylXohQwUBYcM=,tag:y+UBOGdbmPmR5rc2CFA3VA==,type:str]
sops:
    age:
        - recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVVluWHVaRitMeDU4eWox
            SXpCN2FLa0JHYnQwOVdibmM0bEowamRaY0NFCktYSjRSRlQ2WE05VFRBdkhLQWJM
            RDREMkwrYkdiSFArUzg2TWZaejNOcEUKLS0tIFpxK0RiUTRFM1IzZVpmUmZQcWZv
            Q1NNUUZCc2NzSTU5a0lZckFnMUlyRUkKvlqDF0y9c7q18hmwFDYoMNG2Q8JJgBII
            B2U6Sdsto/RBRxIpNn7lJsx9TP6uGQ1a5etyshvUBJ/Riv137BOG6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T13:07:10Z"
    mac: ENC[AES256_GCM,data:q9s76Hb9ZkzmAcUa06FA56V1x+eHxeHtAPVUAAj1i4KZdLNR6LsLklo6YQfLObUxQm7l4wieli9/41tK/C3/KWT9RZpSwmN2CHYONQa8obhpBsS6y2/ukNAW4ysybUUQ5q0MjoKxucZ0I2+C0SUwPg5ZN+jGemQWKRlYBuzdcvs=,iv:VhdvGhy6Ly2+IfgRaGvlUNVBnINsB2puTsBi1ZE1pP4=,tag:kDE9+wxdQ8IePD2839ou8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: harbor-db-password
    namespace: 8gcr-dev-main
stringData:
    username: ENC[AES256_GCM,data:ZO11Nrgq,iv:4l+N7/W+UeuGUWPBpJGqOLjCvL3TAj3YZeGMIB70aww=,tag:tQ0anLzEtDsIR5RMUXfMmA==,type:str]
    password: ENC[AES256_GCM,data:y/6zhjBh0WUuYDhNWHJImX7+tlSgpffeop1WU54=,iv:myso0WfK65PeFUPQMnVohvFFIBQeJNW6kpKiixd9OEA=,tag:gpX9H2QJSr6BW7swhSIXLw==,type:str]
sops:
    age:
        - recipient: age18jfefmcak9zk6jrh7j59ap0rg3zxg577suvmlyrgm3sn0l28zq4slcu94r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVVluWHVaRitMeDU4eWox
            SXpCN2FLa0JHYnQwOVdibmM0bEowamRaY0NFCktYSjRSRlQ2WE05VFRBdkhLQWJM
            RDREMkwrYkdiSFArUzg2TWZaejNOcEUKLS0tIFpxK0RiUTRFM1IzZVpmUmZQcWZv
            Q1NNUUZCc2NzSTU5a0lZckFnMUlyRUkKvlqDF0y9c7q18hmwFDYoMNG2Q8JJgBII
            B2U6Sdsto/RBRxIpNn7lJsx9TP6uGQ1a5etyshvUBJ/Riv137BOG6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T13:07:10Z"
    mac: ENC[AES256_GCM,data:q9s76Hb9ZkzmAcUa06FA56V1x+eHxeHtAPVUAAj1i4KZdLNR6LsLklo6YQfLObUxQm7l4wieli9/41tK/C3/KWT9RZpSwmN2CHYONQa8obhpBsS6y2/ukNAW4ysybUUQ5q0MjoKxucZ0I2+C0SUwPg5ZN+jGemQWKRlYBuzdcvs=,iv:VhdvGhy6Ly2+IfgRaGvlUNVBnINsB2puTsBi1ZE1pP4=,tag:kDE9+wxdQ8IePD2839ou8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
