name: Feature Request
description: Suggest a new feature or enhancement for Harbor
title: "[Feature]: "
labels: ["kind/enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please describe the problem you're trying to solve and your proposed solution.

        **Before submitting:**
        - Search [existing issues](https://github.com/goharbor/harbor/issues) and feature requests to avoid duplicates
        - Review the [ROADMAP](https://github.com/goharbor/harbor/blob/main/ROADMAP.md) to see if this is already planned
        - Consider starting a [discussion](https://github.com/goharbor/harbor/discussions) first to gather feedback
        - For major features, consider submitting a [proposal](https://github.com/goharbor/community/tree/main/proposals)

        **Note:** "Nice to have" is not a strong use case. Please explain the specific problem this feature would solve.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? Why is it important?
      placeholder: |
        Describe the problem you're experiencing or the gap you've identified.
        Focus on the problem, not the solution.
    validations:
      required: true

  - type: checkboxes
    id: who-is-affected
    attributes:
      label: Who is affected by this problem?
      description: Help us understand the impact and audience
      options:
        - label: End users (developers pushing/pulling images)
        - label: Harbor administrators
        - label: Platform engineers / DevOps teams
        - label: Security teams
        - label: CI/CD pipelines / automation
        - label: Other (please describe below)

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        How would this feature work? What would the user experience be?
        Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered or tried?
      placeholder: |
        - Current workarounds you're using
        - Other tools or features that solve similar problems
        - Why those alternatives don't fully address the need
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe 1-3 specific scenarios where this feature would be valuable
      placeholder: |
        **Use Case 1:** As a [role], I want to [action] so that [benefit]
        **Use Case 2:** [Describe another scenario]
      value: |
        **Use Case 1:**

        **Use Case 2:**
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which Harbor component would this feature affect?
      options:
        - "Core (API, authentication, authorization)"
        - "Portal (Web UI)"
        - "Registry"
        - "Job Service"
        - "Trivy (vulnerability scanning)"
        - "Replication"
        - "Garbage Collection"
        - "Helm Charts"
        - "Notary (content trust)"
        - "Proxy Cache"
        - "Installation / Deployment"
        - "Documentation"
        - "Multiple / Other"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples
      placeholder: |
        - Links to relevant documentation
        - Screenshots or mockups
        - Examples from other projects
        - Performance or scalability considerations
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Important (workarounds exist but are painful)"
        - "Critical (blocking adoption/use of Harbor)"
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to contribute this feature?
      description: Would you be interested in implementing this feature with guidance from maintainers?
      options:
        - "Yes, I'd like to implement this"
        - "Yes, with help from maintainers"
        - "Maybe, depending on complexity"
        - "No, but I can help test it"
        - "No, I'm just suggesting it"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have described the problem, not just the solution
          required: true
        - label: I have reviewed the project ROADMAP
          required: false
