// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package distribution

import (
	"sync"

	"github.com/docker/distribution"
)

// Manifest is a mock implementation of distribution.Manifest.
//
//	func TestSomethingThatUsesManifest(t *testing.T) {
//
//		// make and configure a mocked distribution.Manifest
//		mockedManifest := &Manifest{
//			PayloadFunc: func() (string, []byte, error) {
//				panic("mock out the Payload method")
//			},
//			ReferencesFunc: func() []distribution.Descriptor {
//				panic("mock out the References method")
//			},
//		}
//
//		// use mockedManifest in code that requires distribution.Manifest
//		// and then make assertions.
//
//	}
type Manifest struct {
	// PayloadFunc mocks the Payload method.
	PayloadFunc func() (string, []byte, error)

	// ReferencesFunc mocks the References method.
	ReferencesFunc func() []distribution.Descriptor

	// calls tracks calls to the methods.
	calls struct {
		// Payload holds details about calls to the Payload method.
		Payload []struct {
		}
		// References holds details about calls to the References method.
		References []struct {
		}
	}
	lockPayload    sync.RWMutex
	lockReferences sync.RWMutex
}

// Payload calls PayloadFunc.
func (mock *Manifest) Payload() (string, []byte, error) {
	callInfo := struct {
	}{}
	mock.lockPayload.Lock()
	mock.calls.Payload = append(mock.calls.Payload, callInfo)
	mock.lockPayload.Unlock()
	if mock.PayloadFunc == nil {
		var (
			mediaType string
			payload   []byte
			err       error
		)
		return mediaType, payload, err
	}
	return mock.PayloadFunc()
}

// PayloadCalls gets all the calls that were made to Payload.
// Check the length with:
//
//	len(mockedManifest.PayloadCalls())
func (mock *Manifest) PayloadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPayload.RLock()
	calls = mock.calls.Payload
	mock.lockPayload.RUnlock()
	return calls
}

// ResetPayloadCalls reset all the calls that were made to Payload.
func (mock *Manifest) ResetPayloadCalls() {
	mock.lockPayload.Lock()
	mock.calls.Payload = nil
	mock.lockPayload.Unlock()
}

// References calls ReferencesFunc.
func (mock *Manifest) References() []distribution.Descriptor {
	callInfo := struct {
	}{}
	mock.lockReferences.Lock()
	mock.calls.References = append(mock.calls.References, callInfo)
	mock.lockReferences.Unlock()
	if mock.ReferencesFunc == nil {
		var (
			descriptors []distribution.Descriptor
		)
		return descriptors
	}
	return mock.ReferencesFunc()
}

// ReferencesCalls gets all the calls that were made to References.
// Check the length with:
//
//	len(mockedManifest.ReferencesCalls())
func (mock *Manifest) ReferencesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReferences.RLock()
	calls = mock.calls.References
	mock.lockReferences.RUnlock()
	return calls
}

// ResetReferencesCalls reset all the calls that were made to References.
func (mock *Manifest) ResetReferencesCalls() {
	mock.lockReferences.Lock()
	mock.calls.References = nil
	mock.lockReferences.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manifest) ResetCalls() {
	mock.lockPayload.Lock()
	mock.calls.Payload = nil
	mock.lockPayload.Unlock()

	mock.lockReferences.Lock()
	mock.calls.References = nil
	mock.lockReferences.Unlock()
}
