version: '3'

vars:
  # Paths
  COMPOSE_FILE: devenv/docker-compose.yml
  TOKEN_KEY_FILE: devenv/token_service_key.pem

  # Database (only vars used in task commands)
  POSTGRES_USER: postgres
  POSTGRES_DB: registry

tasks:
  # ---------------------------------------------------------------------------
  # Tool Installation
  # ---------------------------------------------------------------------------
  tools:install:
    internal: true
    status:
      - command -v {{.TOOL_NAME}}
    cmds:
      - go install {{.TOOL_PKG}}

  setup:
    desc: Install required Go development tools (for native development)
    cmds:
      - for:
          - { name: air, pkg: 'github.com/air-verse/air@latest' }
          - { name: dlv, pkg: 'github.com/go-delve/delve/cmd/dlv@latest' }
          - { name: govulncheck, pkg: 'golang.org/x/vuln/cmd/govulncheck@latest' }
        task: tools:install
        vars:
          TOOL_NAME: '{{.ITEM.name}}'
          TOOL_PKG: '{{.ITEM.pkg}}'
      - echo "All development tools installed"

  require-step:
    internal: true
    run: once
    status:
      - command -v step
    cmds:
      - go install github.com/smallstep/cli/cmd/step@latest

  gen:private-key:
    desc: Generate RSA private key for token signing
    deps: [require-step]
    status:
      - test -f {{.TOKEN_KEY_FILE}}
    cmds:
      - step crypto keypair /dev/null {{.TOKEN_KEY_FILE}} --kty RSA --size 4096 --no-password --insecure --force
      - chmod 600 {{.TOKEN_KEY_FILE}}
      - echo "Generated {{.TOKEN_KEY_FILE}}"

  # ---------------------------------------------------------------------------
  # Full Development Environment (Containerized)
  # ---------------------------------------------------------------------------
  up:
    desc: Start full dev environment (Portal, Core, JobService, Trivy)
    deps: [gen:private-key]
    cmds:
      - task build:gen-apis
      - defer: { task: dev:down }
      - |
        echo "Portal:      http://localhost:4200/"
        echo "API:         http://localhost:8080/api/v2.0"
        echo "JobService:  http://localhost:8888"
        echo "Trivy:       http://localhost:8081"
        echo "Debug Portal: chrome://inspect (port 9229)"
        echo "Debug Core:   localhost:2345"
        echo "Debug Job:    localhost:2346"
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile trivy up --build

  down:
    desc: Stop all dev environment services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile portal --profile core --profile jobservice --profile trivy down
      - echo "Dev environment stopped"

  # ---------------------------------------------------------------------------
  # Infrastructure (Docker Compose)
  # ---------------------------------------------------------------------------
  infra:up:
    desc: Start infrastructure only (PostgreSQL, Redis, Registry)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d
      - |
        echo "Waiting for PostgreSQL..."
        timeout=60 elapsed=0
        until docker compose -f {{.COMPOSE_FILE}} exec -T postgresql pg_isready -U postgres > /dev/null 2>&1; do
          [ $elapsed -ge $timeout ] && echo "PostgreSQL failed to start" && exit 1
          sleep 2; elapsed=$((elapsed + 2))
        done
      - echo "Infrastructure ready"
      - docker compose -f {{.COMPOSE_FILE}} ps

  infra:down:
    desc: Stop infrastructure services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} down

  infra:remove:
    desc: Remove infrastructure and all volumes
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile trivy down -v

  # ---------------------------------------------------------------------------
  # Backend Services (Containerized)
  # ---------------------------------------------------------------------------
  backend:up:
    desc: Start Core + JobService containers with hot reload
    deps: [gen:private-key]
    cmds:
      - task build:gen-apis
      - docker compose -f {{.COMPOSE_FILE}} --profile core --profile jobservice up -d --build

  backend:down:
    desc: Stop Core + JobService containers
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile core --profile jobservice down

  backend:logs:
    desc: View backend container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile core --profile jobservice logs -f

  backend:logs:core:
    desc: View Core container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs -f core

  backend:logs:jobservice:
    desc: View JobService container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs -f jobservice

  backend:restart:
    desc: Restart backend containers
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile core --profile jobservice restart

  # ---------------------------------------------------------------------------
  # Frontend (Native - alternative to containerized portal)
  # ---------------------------------------------------------------------------
  frontend:native:
    desc: Start Portal natively (alternative to --profile portal)
    silent: true
    dir: src/portal
    cmds:
      - '[ ! -d "node_modules" ] && npm install || true'
      - task: :build:gen-apis:frontend
      - exec ./node_modules/.bin/ng serve --host 0.0.0.0 --hmr --disable-host-check

  frontend:build:
    desc: Build frontend for production
    dir: src/portal
    cmds:
      - npm run build

  frontend:test:
    desc: Run frontend tests in watch mode
    dir: src/portal
    cmds:
      - npm run test -- --watch

  frontend:test:once:
    desc: Run frontend tests once
    dir: src/portal
    cmds:
      - npm run test -- --watch=false

  # ---------------------------------------------------------------------------
  # Database Operations
  # ---------------------------------------------------------------------------
  db:migrate:
    desc: Run database migrations
    cmds:
      - |
        echo "Running migrations..."
        docker compose -f {{.COMPOSE_FILE}} exec -T postgresql \
          psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}} -f /migrations/postgresql/0180_2.15.0_schema.up.sql
      - echo "Migrations complete"

  db:reset:
    desc: Reset database to clean state
    cmds:
      - |
        echo "WARNING: This will delete all data. Continue? (Ctrl+C to cancel)"
        read -p "Press Enter to continue..."
      - docker compose -f {{.COMPOSE_FILE}} exec -T postgresql dropdb -U {{.POSTGRES_USER}} {{.POSTGRES_DB}} --if-exists
      - docker compose -f {{.COMPOSE_FILE}} exec -T postgresql createdb -U {{.POSTGRES_USER}} {{.POSTGRES_DB}}
      - task: db:migrate
      - echo "Database reset complete"

  db:shell:
    desc: Open PostgreSQL shell
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} exec postgresql psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}}

  # ---------------------------------------------------------------------------
  # Utilities
  # ---------------------------------------------------------------------------
  clean:
    desc: Clean temporary files and all containers/volumes
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile trivy down -v
      - pkill -f "ng serve" || true
      - rm -rf tmp/
      - rm -f build-errors.log
      - rm -f {{.TOKEN_KEY_FILE}}
      - echo "Clean complete"

  status:
    desc: Show status of all development services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile trivy ps

  logs:
    desc: View all container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile trivy logs -f
