// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package webhook

import (
	"context"
	"sync"
	"time"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/notification/policy/model"
	"github.com/goharbor/harbor/src/pkg/task"
)

// Controller is a mock implementation of webhook.Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked webhook.Controller
//		mockedController := &Controller{
//			CountExecutionsFunc: func(ctx context.Context, policyID int64, query *q.Query) (int64, error) {
//				panic("mock out the CountExecutions method")
//			},
//			CountPoliciesFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the CountPolicies method")
//			},
//			CountTasksFunc: func(ctx context.Context, execID int64, query *q.Query) (int64, error) {
//				panic("mock out the CountTasks method")
//			},
//			CreatePolicyFunc: func(ctx context.Context, policy *model.Policy) (int64, error) {
//				panic("mock out the CreatePolicy method")
//			},
//			DeletePolicyFunc: func(ctx context.Context, policyID int64) error {
//				panic("mock out the DeletePolicy method")
//			},
//			GetLastTriggerTimeFunc: func(ctx context.Context, eventType string, policyID int64) (time.Time, error) {
//				panic("mock out the GetLastTriggerTime method")
//			},
//			GetPolicyFunc: func(ctx context.Context, id int64) (*model.Policy, error) {
//				panic("mock out the GetPolicy method")
//			},
//			GetRelatedPolicesFunc: func(ctx context.Context, projectID int64, eventType string) ([]*model.Policy, error) {
//				panic("mock out the GetRelatedPolices method")
//			},
//			GetTaskFunc: func(ctx context.Context, taskID int64) (*task.Task, error) {
//				panic("mock out the GetTask method")
//			},
//			GetTaskLogFunc: func(ctx context.Context, taskID int64) ([]byte, error) {
//				panic("mock out the GetTaskLog method")
//			},
//			ListExecutionsFunc: func(ctx context.Context, policyID int64, query *q.Query) ([]*task.Execution, error) {
//				panic("mock out the ListExecutions method")
//			},
//			ListPoliciesFunc: func(ctx context.Context, query *q.Query) ([]*model.Policy, error) {
//				panic("mock out the ListPolicies method")
//			},
//			ListTasksFunc: func(ctx context.Context, execID int64, query *q.Query) ([]*task.Task, error) {
//				panic("mock out the ListTasks method")
//			},
//			UpdatePolicyFunc: func(ctx context.Context, policy *model.Policy) error {
//				panic("mock out the UpdatePolicy method")
//			},
//		}
//
//		// use mockedController in code that requires webhook.Controller
//		// and then make assertions.
//
//	}
type Controller struct {
	// CountExecutionsFunc mocks the CountExecutions method.
	CountExecutionsFunc func(ctx context.Context, policyID int64, query *q.Query) (int64, error)

	// CountPoliciesFunc mocks the CountPolicies method.
	CountPoliciesFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CountTasksFunc mocks the CountTasks method.
	CountTasksFunc func(ctx context.Context, execID int64, query *q.Query) (int64, error)

	// CreatePolicyFunc mocks the CreatePolicy method.
	CreatePolicyFunc func(ctx context.Context, policy *model.Policy) (int64, error)

	// DeletePolicyFunc mocks the DeletePolicy method.
	DeletePolicyFunc func(ctx context.Context, policyID int64) error

	// GetLastTriggerTimeFunc mocks the GetLastTriggerTime method.
	GetLastTriggerTimeFunc func(ctx context.Context, eventType string, policyID int64) (time.Time, error)

	// GetPolicyFunc mocks the GetPolicy method.
	GetPolicyFunc func(ctx context.Context, id int64) (*model.Policy, error)

	// GetRelatedPolicesFunc mocks the GetRelatedPolices method.
	GetRelatedPolicesFunc func(ctx context.Context, projectID int64, eventType string) ([]*model.Policy, error)

	// GetTaskFunc mocks the GetTask method.
	GetTaskFunc func(ctx context.Context, taskID int64) (*task.Task, error)

	// GetTaskLogFunc mocks the GetTaskLog method.
	GetTaskLogFunc func(ctx context.Context, taskID int64) ([]byte, error)

	// ListExecutionsFunc mocks the ListExecutions method.
	ListExecutionsFunc func(ctx context.Context, policyID int64, query *q.Query) ([]*task.Execution, error)

	// ListPoliciesFunc mocks the ListPolicies method.
	ListPoliciesFunc func(ctx context.Context, query *q.Query) ([]*model.Policy, error)

	// ListTasksFunc mocks the ListTasks method.
	ListTasksFunc func(ctx context.Context, execID int64, query *q.Query) ([]*task.Task, error)

	// UpdatePolicyFunc mocks the UpdatePolicy method.
	UpdatePolicyFunc func(ctx context.Context, policy *model.Policy) error

	// calls tracks calls to the methods.
	calls struct {
		// CountExecutions holds details about calls to the CountExecutions method.
		CountExecutions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// CountPolicies holds details about calls to the CountPolicies method.
		CountPolicies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// CountTasks holds details about calls to the CountTasks method.
		CountTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExecID is the execID argument value.
			ExecID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// CreatePolicy holds details about calls to the CreatePolicy method.
		CreatePolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Policy is the policy argument value.
			Policy *model.Policy
		}
		// DeletePolicy holds details about calls to the DeletePolicy method.
		DeletePolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
		}
		// GetLastTriggerTime holds details about calls to the GetLastTriggerTime method.
		GetLastTriggerTime []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EventType is the eventType argument value.
			EventType string
			// PolicyID is the policyID argument value.
			PolicyID int64
		}
		// GetPolicy holds details about calls to the GetPolicy method.
		GetPolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetRelatedPolices holds details about calls to the GetRelatedPolices method.
		GetRelatedPolices []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// EventType is the eventType argument value.
			EventType string
		}
		// GetTask holds details about calls to the GetTask method.
		GetTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TaskID is the taskID argument value.
			TaskID int64
		}
		// GetTaskLog holds details about calls to the GetTaskLog method.
		GetTaskLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TaskID is the taskID argument value.
			TaskID int64
		}
		// ListExecutions holds details about calls to the ListExecutions method.
		ListExecutions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyID is the policyID argument value.
			PolicyID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// ListPolicies holds details about calls to the ListPolicies method.
		ListPolicies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListTasks holds details about calls to the ListTasks method.
		ListTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExecID is the execID argument value.
			ExecID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// UpdatePolicy holds details about calls to the UpdatePolicy method.
		UpdatePolicy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Policy is the policy argument value.
			Policy *model.Policy
		}
	}
	lockCountExecutions    sync.RWMutex
	lockCountPolicies      sync.RWMutex
	lockCountTasks         sync.RWMutex
	lockCreatePolicy       sync.RWMutex
	lockDeletePolicy       sync.RWMutex
	lockGetLastTriggerTime sync.RWMutex
	lockGetPolicy          sync.RWMutex
	lockGetRelatedPolices  sync.RWMutex
	lockGetTask            sync.RWMutex
	lockGetTaskLog         sync.RWMutex
	lockListExecutions     sync.RWMutex
	lockListPolicies       sync.RWMutex
	lockListTasks          sync.RWMutex
	lockUpdatePolicy       sync.RWMutex
}

// CountExecutions calls CountExecutionsFunc.
func (mock *Controller) CountExecutions(ctx context.Context, policyID int64, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
		Query    *q.Query
	}{
		Ctx:      ctx,
		PolicyID: policyID,
		Query:    query,
	}
	mock.lockCountExecutions.Lock()
	mock.calls.CountExecutions = append(mock.calls.CountExecutions, callInfo)
	mock.lockCountExecutions.Unlock()
	if mock.CountExecutionsFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountExecutionsFunc(ctx, policyID, query)
}

// CountExecutionsCalls gets all the calls that were made to CountExecutions.
// Check the length with:
//
//	len(mockedController.CountExecutionsCalls())
func (mock *Controller) CountExecutionsCalls() []struct {
	Ctx      context.Context
	PolicyID int64
	Query    *q.Query
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
		Query    *q.Query
	}
	mock.lockCountExecutions.RLock()
	calls = mock.calls.CountExecutions
	mock.lockCountExecutions.RUnlock()
	return calls
}

// ResetCountExecutionsCalls reset all the calls that were made to CountExecutions.
func (mock *Controller) ResetCountExecutionsCalls() {
	mock.lockCountExecutions.Lock()
	mock.calls.CountExecutions = nil
	mock.lockCountExecutions.Unlock()
}

// CountPolicies calls CountPoliciesFunc.
func (mock *Controller) CountPolicies(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCountPolicies.Lock()
	mock.calls.CountPolicies = append(mock.calls.CountPolicies, callInfo)
	mock.lockCountPolicies.Unlock()
	if mock.CountPoliciesFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountPoliciesFunc(ctx, query)
}

// CountPoliciesCalls gets all the calls that were made to CountPolicies.
// Check the length with:
//
//	len(mockedController.CountPoliciesCalls())
func (mock *Controller) CountPoliciesCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCountPolicies.RLock()
	calls = mock.calls.CountPolicies
	mock.lockCountPolicies.RUnlock()
	return calls
}

// ResetCountPoliciesCalls reset all the calls that were made to CountPolicies.
func (mock *Controller) ResetCountPoliciesCalls() {
	mock.lockCountPolicies.Lock()
	mock.calls.CountPolicies = nil
	mock.lockCountPolicies.Unlock()
}

// CountTasks calls CountTasksFunc.
func (mock *Controller) CountTasks(ctx context.Context, execID int64, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		ExecID int64
		Query  *q.Query
	}{
		Ctx:    ctx,
		ExecID: execID,
		Query:  query,
	}
	mock.lockCountTasks.Lock()
	mock.calls.CountTasks = append(mock.calls.CountTasks, callInfo)
	mock.lockCountTasks.Unlock()
	if mock.CountTasksFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountTasksFunc(ctx, execID, query)
}

// CountTasksCalls gets all the calls that were made to CountTasks.
// Check the length with:
//
//	len(mockedController.CountTasksCalls())
func (mock *Controller) CountTasksCalls() []struct {
	Ctx    context.Context
	ExecID int64
	Query  *q.Query
} {
	var calls []struct {
		Ctx    context.Context
		ExecID int64
		Query  *q.Query
	}
	mock.lockCountTasks.RLock()
	calls = mock.calls.CountTasks
	mock.lockCountTasks.RUnlock()
	return calls
}

// ResetCountTasksCalls reset all the calls that were made to CountTasks.
func (mock *Controller) ResetCountTasksCalls() {
	mock.lockCountTasks.Lock()
	mock.calls.CountTasks = nil
	mock.lockCountTasks.Unlock()
}

// CreatePolicy calls CreatePolicyFunc.
func (mock *Controller) CreatePolicy(ctx context.Context, policy *model.Policy) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		Policy *model.Policy
	}{
		Ctx:    ctx,
		Policy: policy,
	}
	mock.lockCreatePolicy.Lock()
	mock.calls.CreatePolicy = append(mock.calls.CreatePolicy, callInfo)
	mock.lockCreatePolicy.Unlock()
	if mock.CreatePolicyFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CreatePolicyFunc(ctx, policy)
}

// CreatePolicyCalls gets all the calls that were made to CreatePolicy.
// Check the length with:
//
//	len(mockedController.CreatePolicyCalls())
func (mock *Controller) CreatePolicyCalls() []struct {
	Ctx    context.Context
	Policy *model.Policy
} {
	var calls []struct {
		Ctx    context.Context
		Policy *model.Policy
	}
	mock.lockCreatePolicy.RLock()
	calls = mock.calls.CreatePolicy
	mock.lockCreatePolicy.RUnlock()
	return calls
}

// ResetCreatePolicyCalls reset all the calls that were made to CreatePolicy.
func (mock *Controller) ResetCreatePolicyCalls() {
	mock.lockCreatePolicy.Lock()
	mock.calls.CreatePolicy = nil
	mock.lockCreatePolicy.Unlock()
}

// DeletePolicy calls DeletePolicyFunc.
func (mock *Controller) DeletePolicy(ctx context.Context, policyID int64) error {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
	}{
		Ctx:      ctx,
		PolicyID: policyID,
	}
	mock.lockDeletePolicy.Lock()
	mock.calls.DeletePolicy = append(mock.calls.DeletePolicy, callInfo)
	mock.lockDeletePolicy.Unlock()
	if mock.DeletePolicyFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeletePolicyFunc(ctx, policyID)
}

// DeletePolicyCalls gets all the calls that were made to DeletePolicy.
// Check the length with:
//
//	len(mockedController.DeletePolicyCalls())
func (mock *Controller) DeletePolicyCalls() []struct {
	Ctx      context.Context
	PolicyID int64
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
	}
	mock.lockDeletePolicy.RLock()
	calls = mock.calls.DeletePolicy
	mock.lockDeletePolicy.RUnlock()
	return calls
}

// ResetDeletePolicyCalls reset all the calls that were made to DeletePolicy.
func (mock *Controller) ResetDeletePolicyCalls() {
	mock.lockDeletePolicy.Lock()
	mock.calls.DeletePolicy = nil
	mock.lockDeletePolicy.Unlock()
}

// GetLastTriggerTime calls GetLastTriggerTimeFunc.
func (mock *Controller) GetLastTriggerTime(ctx context.Context, eventType string, policyID int64) (time.Time, error) {
	callInfo := struct {
		Ctx       context.Context
		EventType string
		PolicyID  int64
	}{
		Ctx:       ctx,
		EventType: eventType,
		PolicyID:  policyID,
	}
	mock.lockGetLastTriggerTime.Lock()
	mock.calls.GetLastTriggerTime = append(mock.calls.GetLastTriggerTime, callInfo)
	mock.lockGetLastTriggerTime.Unlock()
	if mock.GetLastTriggerTimeFunc == nil {
		var (
			time1 time.Time
			err   error
		)
		return time1, err
	}
	return mock.GetLastTriggerTimeFunc(ctx, eventType, policyID)
}

// GetLastTriggerTimeCalls gets all the calls that were made to GetLastTriggerTime.
// Check the length with:
//
//	len(mockedController.GetLastTriggerTimeCalls())
func (mock *Controller) GetLastTriggerTimeCalls() []struct {
	Ctx       context.Context
	EventType string
	PolicyID  int64
} {
	var calls []struct {
		Ctx       context.Context
		EventType string
		PolicyID  int64
	}
	mock.lockGetLastTriggerTime.RLock()
	calls = mock.calls.GetLastTriggerTime
	mock.lockGetLastTriggerTime.RUnlock()
	return calls
}

// ResetGetLastTriggerTimeCalls reset all the calls that were made to GetLastTriggerTime.
func (mock *Controller) ResetGetLastTriggerTimeCalls() {
	mock.lockGetLastTriggerTime.Lock()
	mock.calls.GetLastTriggerTime = nil
	mock.lockGetLastTriggerTime.Unlock()
}

// GetPolicy calls GetPolicyFunc.
func (mock *Controller) GetPolicy(ctx context.Context, id int64) (*model.Policy, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetPolicy.Lock()
	mock.calls.GetPolicy = append(mock.calls.GetPolicy, callInfo)
	mock.lockGetPolicy.Unlock()
	if mock.GetPolicyFunc == nil {
		var (
			policy *model.Policy
			err    error
		)
		return policy, err
	}
	return mock.GetPolicyFunc(ctx, id)
}

// GetPolicyCalls gets all the calls that were made to GetPolicy.
// Check the length with:
//
//	len(mockedController.GetPolicyCalls())
func (mock *Controller) GetPolicyCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetPolicy.RLock()
	calls = mock.calls.GetPolicy
	mock.lockGetPolicy.RUnlock()
	return calls
}

// ResetGetPolicyCalls reset all the calls that were made to GetPolicy.
func (mock *Controller) ResetGetPolicyCalls() {
	mock.lockGetPolicy.Lock()
	mock.calls.GetPolicy = nil
	mock.lockGetPolicy.Unlock()
}

// GetRelatedPolices calls GetRelatedPolicesFunc.
func (mock *Controller) GetRelatedPolices(ctx context.Context, projectID int64, eventType string) ([]*model.Policy, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		EventType string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		EventType: eventType,
	}
	mock.lockGetRelatedPolices.Lock()
	mock.calls.GetRelatedPolices = append(mock.calls.GetRelatedPolices, callInfo)
	mock.lockGetRelatedPolices.Unlock()
	if mock.GetRelatedPolicesFunc == nil {
		var (
			policys []*model.Policy
			err     error
		)
		return policys, err
	}
	return mock.GetRelatedPolicesFunc(ctx, projectID, eventType)
}

// GetRelatedPolicesCalls gets all the calls that were made to GetRelatedPolices.
// Check the length with:
//
//	len(mockedController.GetRelatedPolicesCalls())
func (mock *Controller) GetRelatedPolicesCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	EventType string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		EventType string
	}
	mock.lockGetRelatedPolices.RLock()
	calls = mock.calls.GetRelatedPolices
	mock.lockGetRelatedPolices.RUnlock()
	return calls
}

// ResetGetRelatedPolicesCalls reset all the calls that were made to GetRelatedPolices.
func (mock *Controller) ResetGetRelatedPolicesCalls() {
	mock.lockGetRelatedPolices.Lock()
	mock.calls.GetRelatedPolices = nil
	mock.lockGetRelatedPolices.Unlock()
}

// GetTask calls GetTaskFunc.
func (mock *Controller) GetTask(ctx context.Context, taskID int64) (*task.Task, error) {
	callInfo := struct {
		Ctx    context.Context
		TaskID int64
	}{
		Ctx:    ctx,
		TaskID: taskID,
	}
	mock.lockGetTask.Lock()
	mock.calls.GetTask = append(mock.calls.GetTask, callInfo)
	mock.lockGetTask.Unlock()
	if mock.GetTaskFunc == nil {
		var (
			task1 *task.Task
			err   error
		)
		return task1, err
	}
	return mock.GetTaskFunc(ctx, taskID)
}

// GetTaskCalls gets all the calls that were made to GetTask.
// Check the length with:
//
//	len(mockedController.GetTaskCalls())
func (mock *Controller) GetTaskCalls() []struct {
	Ctx    context.Context
	TaskID int64
} {
	var calls []struct {
		Ctx    context.Context
		TaskID int64
	}
	mock.lockGetTask.RLock()
	calls = mock.calls.GetTask
	mock.lockGetTask.RUnlock()
	return calls
}

// ResetGetTaskCalls reset all the calls that were made to GetTask.
func (mock *Controller) ResetGetTaskCalls() {
	mock.lockGetTask.Lock()
	mock.calls.GetTask = nil
	mock.lockGetTask.Unlock()
}

// GetTaskLog calls GetTaskLogFunc.
func (mock *Controller) GetTaskLog(ctx context.Context, taskID int64) ([]byte, error) {
	callInfo := struct {
		Ctx    context.Context
		TaskID int64
	}{
		Ctx:    ctx,
		TaskID: taskID,
	}
	mock.lockGetTaskLog.Lock()
	mock.calls.GetTaskLog = append(mock.calls.GetTaskLog, callInfo)
	mock.lockGetTaskLog.Unlock()
	if mock.GetTaskLogFunc == nil {
		var (
			bytes []byte
			err   error
		)
		return bytes, err
	}
	return mock.GetTaskLogFunc(ctx, taskID)
}

// GetTaskLogCalls gets all the calls that were made to GetTaskLog.
// Check the length with:
//
//	len(mockedController.GetTaskLogCalls())
func (mock *Controller) GetTaskLogCalls() []struct {
	Ctx    context.Context
	TaskID int64
} {
	var calls []struct {
		Ctx    context.Context
		TaskID int64
	}
	mock.lockGetTaskLog.RLock()
	calls = mock.calls.GetTaskLog
	mock.lockGetTaskLog.RUnlock()
	return calls
}

// ResetGetTaskLogCalls reset all the calls that were made to GetTaskLog.
func (mock *Controller) ResetGetTaskLogCalls() {
	mock.lockGetTaskLog.Lock()
	mock.calls.GetTaskLog = nil
	mock.lockGetTaskLog.Unlock()
}

// ListExecutions calls ListExecutionsFunc.
func (mock *Controller) ListExecutions(ctx context.Context, policyID int64, query *q.Query) ([]*task.Execution, error) {
	callInfo := struct {
		Ctx      context.Context
		PolicyID int64
		Query    *q.Query
	}{
		Ctx:      ctx,
		PolicyID: policyID,
		Query:    query,
	}
	mock.lockListExecutions.Lock()
	mock.calls.ListExecutions = append(mock.calls.ListExecutions, callInfo)
	mock.lockListExecutions.Unlock()
	if mock.ListExecutionsFunc == nil {
		var (
			executions []*task.Execution
			err        error
		)
		return executions, err
	}
	return mock.ListExecutionsFunc(ctx, policyID, query)
}

// ListExecutionsCalls gets all the calls that were made to ListExecutions.
// Check the length with:
//
//	len(mockedController.ListExecutionsCalls())
func (mock *Controller) ListExecutionsCalls() []struct {
	Ctx      context.Context
	PolicyID int64
	Query    *q.Query
} {
	var calls []struct {
		Ctx      context.Context
		PolicyID int64
		Query    *q.Query
	}
	mock.lockListExecutions.RLock()
	calls = mock.calls.ListExecutions
	mock.lockListExecutions.RUnlock()
	return calls
}

// ResetListExecutionsCalls reset all the calls that were made to ListExecutions.
func (mock *Controller) ResetListExecutionsCalls() {
	mock.lockListExecutions.Lock()
	mock.calls.ListExecutions = nil
	mock.lockListExecutions.Unlock()
}

// ListPolicies calls ListPoliciesFunc.
func (mock *Controller) ListPolicies(ctx context.Context, query *q.Query) ([]*model.Policy, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockListPolicies.Lock()
	mock.calls.ListPolicies = append(mock.calls.ListPolicies, callInfo)
	mock.lockListPolicies.Unlock()
	if mock.ListPoliciesFunc == nil {
		var (
			policys []*model.Policy
			err     error
		)
		return policys, err
	}
	return mock.ListPoliciesFunc(ctx, query)
}

// ListPoliciesCalls gets all the calls that were made to ListPolicies.
// Check the length with:
//
//	len(mockedController.ListPoliciesCalls())
func (mock *Controller) ListPoliciesCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockListPolicies.RLock()
	calls = mock.calls.ListPolicies
	mock.lockListPolicies.RUnlock()
	return calls
}

// ResetListPoliciesCalls reset all the calls that were made to ListPolicies.
func (mock *Controller) ResetListPoliciesCalls() {
	mock.lockListPolicies.Lock()
	mock.calls.ListPolicies = nil
	mock.lockListPolicies.Unlock()
}

// ListTasks calls ListTasksFunc.
func (mock *Controller) ListTasks(ctx context.Context, execID int64, query *q.Query) ([]*task.Task, error) {
	callInfo := struct {
		Ctx    context.Context
		ExecID int64
		Query  *q.Query
	}{
		Ctx:    ctx,
		ExecID: execID,
		Query:  query,
	}
	mock.lockListTasks.Lock()
	mock.calls.ListTasks = append(mock.calls.ListTasks, callInfo)
	mock.lockListTasks.Unlock()
	if mock.ListTasksFunc == nil {
		var (
			tasks []*task.Task
			err   error
		)
		return tasks, err
	}
	return mock.ListTasksFunc(ctx, execID, query)
}

// ListTasksCalls gets all the calls that were made to ListTasks.
// Check the length with:
//
//	len(mockedController.ListTasksCalls())
func (mock *Controller) ListTasksCalls() []struct {
	Ctx    context.Context
	ExecID int64
	Query  *q.Query
} {
	var calls []struct {
		Ctx    context.Context
		ExecID int64
		Query  *q.Query
	}
	mock.lockListTasks.RLock()
	calls = mock.calls.ListTasks
	mock.lockListTasks.RUnlock()
	return calls
}

// ResetListTasksCalls reset all the calls that were made to ListTasks.
func (mock *Controller) ResetListTasksCalls() {
	mock.lockListTasks.Lock()
	mock.calls.ListTasks = nil
	mock.lockListTasks.Unlock()
}

// UpdatePolicy calls UpdatePolicyFunc.
func (mock *Controller) UpdatePolicy(ctx context.Context, policy *model.Policy) error {
	callInfo := struct {
		Ctx    context.Context
		Policy *model.Policy
	}{
		Ctx:    ctx,
		Policy: policy,
	}
	mock.lockUpdatePolicy.Lock()
	mock.calls.UpdatePolicy = append(mock.calls.UpdatePolicy, callInfo)
	mock.lockUpdatePolicy.Unlock()
	if mock.UpdatePolicyFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdatePolicyFunc(ctx, policy)
}

// UpdatePolicyCalls gets all the calls that were made to UpdatePolicy.
// Check the length with:
//
//	len(mockedController.UpdatePolicyCalls())
func (mock *Controller) UpdatePolicyCalls() []struct {
	Ctx    context.Context
	Policy *model.Policy
} {
	var calls []struct {
		Ctx    context.Context
		Policy *model.Policy
	}
	mock.lockUpdatePolicy.RLock()
	calls = mock.calls.UpdatePolicy
	mock.lockUpdatePolicy.RUnlock()
	return calls
}

// ResetUpdatePolicyCalls reset all the calls that were made to UpdatePolicy.
func (mock *Controller) ResetUpdatePolicyCalls() {
	mock.lockUpdatePolicy.Lock()
	mock.calls.UpdatePolicy = nil
	mock.lockUpdatePolicy.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Controller) ResetCalls() {
	mock.lockCountExecutions.Lock()
	mock.calls.CountExecutions = nil
	mock.lockCountExecutions.Unlock()

	mock.lockCountPolicies.Lock()
	mock.calls.CountPolicies = nil
	mock.lockCountPolicies.Unlock()

	mock.lockCountTasks.Lock()
	mock.calls.CountTasks = nil
	mock.lockCountTasks.Unlock()

	mock.lockCreatePolicy.Lock()
	mock.calls.CreatePolicy = nil
	mock.lockCreatePolicy.Unlock()

	mock.lockDeletePolicy.Lock()
	mock.calls.DeletePolicy = nil
	mock.lockDeletePolicy.Unlock()

	mock.lockGetLastTriggerTime.Lock()
	mock.calls.GetLastTriggerTime = nil
	mock.lockGetLastTriggerTime.Unlock()

	mock.lockGetPolicy.Lock()
	mock.calls.GetPolicy = nil
	mock.lockGetPolicy.Unlock()

	mock.lockGetRelatedPolices.Lock()
	mock.calls.GetRelatedPolices = nil
	mock.lockGetRelatedPolices.Unlock()

	mock.lockGetTask.Lock()
	mock.calls.GetTask = nil
	mock.lockGetTask.Unlock()

	mock.lockGetTaskLog.Lock()
	mock.calls.GetTaskLog = nil
	mock.lockGetTaskLog.Unlock()

	mock.lockListExecutions.Lock()
	mock.calls.ListExecutions = nil
	mock.lockListExecutions.Unlock()

	mock.lockListPolicies.Lock()
	mock.calls.ListPolicies = nil
	mock.lockListPolicies.Unlock()

	mock.lockListTasks.Lock()
	mock.calls.ListTasks = nil
	mock.lockListTasks.Unlock()

	mock.lockUpdatePolicy.Lock()
	mock.calls.UpdatePolicy = nil
	mock.lockUpdatePolicy.Unlock()
}
