// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package chart

import (
	"sync"

	chart0 "github.com/goharbor/harbor/src/pkg/chart"
	"helm.sh/helm/v3/pkg/chart"
)

// Operator is a mock implementation of chart0.Operator.
//
//	func TestSomethingThatUsesOperator(t *testing.T) {
//
//		// make and configure a mocked chart0.Operator
//		mockedOperator := &Operator{
//			GetDataFunc: func(content []byte) (*chart.Chart, error) {
//				panic("mock out the GetData method")
//			},
//			GetDetailsFunc: func(content []byte) (*chart0.VersionDetails, error) {
//				panic("mock out the GetDetails method")
//			},
//		}
//
//		// use mockedOperator in code that requires chart0.Operator
//		// and then make assertions.
//
//	}
type Operator struct {
	// GetDataFunc mocks the GetData method.
	GetDataFunc func(content []byte) (*chart.Chart, error)

	// GetDetailsFunc mocks the GetDetails method.
	GetDetailsFunc func(content []byte) (*chart0.VersionDetails, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetData holds details about calls to the GetData method.
		GetData []struct {
			// Content is the content argument value.
			Content []byte
		}
		// GetDetails holds details about calls to the GetDetails method.
		GetDetails []struct {
			// Content is the content argument value.
			Content []byte
		}
	}
	lockGetData    sync.RWMutex
	lockGetDetails sync.RWMutex
}

// GetData calls GetDataFunc.
func (mock *Operator) GetData(content []byte) (*chart.Chart, error) {
	callInfo := struct {
		Content []byte
	}{
		Content: content,
	}
	mock.lockGetData.Lock()
	mock.calls.GetData = append(mock.calls.GetData, callInfo)
	mock.lockGetData.Unlock()
	if mock.GetDataFunc == nil {
		var (
			chart1 *chart.Chart
			err    error
		)
		return chart1, err
	}
	return mock.GetDataFunc(content)
}

// GetDataCalls gets all the calls that were made to GetData.
// Check the length with:
//
//	len(mockedOperator.GetDataCalls())
func (mock *Operator) GetDataCalls() []struct {
	Content []byte
} {
	var calls []struct {
		Content []byte
	}
	mock.lockGetData.RLock()
	calls = mock.calls.GetData
	mock.lockGetData.RUnlock()
	return calls
}

// ResetGetDataCalls reset all the calls that were made to GetData.
func (mock *Operator) ResetGetDataCalls() {
	mock.lockGetData.Lock()
	mock.calls.GetData = nil
	mock.lockGetData.Unlock()
}

// GetDetails calls GetDetailsFunc.
func (mock *Operator) GetDetails(content []byte) (*chart0.VersionDetails, error) {
	callInfo := struct {
		Content []byte
	}{
		Content: content,
	}
	mock.lockGetDetails.Lock()
	mock.calls.GetDetails = append(mock.calls.GetDetails, callInfo)
	mock.lockGetDetails.Unlock()
	if mock.GetDetailsFunc == nil {
		var (
			versionDetails *chart0.VersionDetails
			err            error
		)
		return versionDetails, err
	}
	return mock.GetDetailsFunc(content)
}

// GetDetailsCalls gets all the calls that were made to GetDetails.
// Check the length with:
//
//	len(mockedOperator.GetDetailsCalls())
func (mock *Operator) GetDetailsCalls() []struct {
	Content []byte
} {
	var calls []struct {
		Content []byte
	}
	mock.lockGetDetails.RLock()
	calls = mock.calls.GetDetails
	mock.lockGetDetails.RUnlock()
	return calls
}

// ResetGetDetailsCalls reset all the calls that were made to GetDetails.
func (mock *Operator) ResetGetDetailsCalls() {
	mock.lockGetDetails.Lock()
	mock.calls.GetDetails = nil
	mock.lockGetDetails.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Operator) ResetCalls() {
	mock.lockGetData.Lock()
	mock.calls.GetData = nil
	mock.lockGetData.Unlock()

	mock.lockGetDetails.Lock()
	mock.calls.GetDetails = nil
	mock.lockGetDetails.Unlock()
}
