// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package task

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/task"
)

// Manager is a mock implementation of task.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked task.Manager
//		mockedManager := &Manager{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, executionID int64, job *task.Job, extraAttrs ...map[string]any) (int64, error) {
//				panic("mock out the Create method")
//			},
//			ExecutionIDsByVendorAndStatusFunc: func(ctx context.Context, vendorType string, status string) ([]int64, error) {
//				panic("mock out the ExecutionIDsByVendorAndStatus method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*task.Task, error) {
//				panic("mock out the Get method")
//			},
//			GetLogFunc: func(ctx context.Context, id int64) ([]byte, error) {
//				panic("mock out the GetLog method")
//			},
//			GetLogByJobIDFunc: func(ctx context.Context, jobID string) ([]byte, error) {
//				panic("mock out the GetLogByJobID method")
//			},
//			IsTaskFinishedFunc: func(ctx context.Context, reportID string) bool {
//				panic("mock out the IsTaskFinished method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*task.Task, error) {
//				panic("mock out the List method")
//			},
//			ListScanTasksByReportUUIDFunc: func(ctx context.Context, uuid string) ([]*task.Task, error) {
//				panic("mock out the ListScanTasksByReportUUID method")
//			},
//			RetrieveStatusFromTaskFunc: func(ctx context.Context, reportID string) string {
//				panic("mock out the RetrieveStatusFromTask method")
//			},
//			StopFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Stop method")
//			},
//			UpdateFunc: func(ctx context.Context, task1 *task.Task, props ...string) error {
//				panic("mock out the Update method")
//			},
//			UpdateExtraAttrsFunc: func(ctx context.Context, id int64, extraAttrs map[string]any) error {
//				panic("mock out the UpdateExtraAttrs method")
//			},
//			UpdateStatusInBatchFunc: func(ctx context.Context, jobIDs []string, status string, batchSize int) error {
//				panic("mock out the UpdateStatusInBatch method")
//			},
//		}
//
//		// use mockedManager in code that requires task.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, executionID int64, job *task.Job, extraAttrs ...map[string]any) (int64, error)

	// ExecutionIDsByVendorAndStatusFunc mocks the ExecutionIDsByVendorAndStatus method.
	ExecutionIDsByVendorAndStatusFunc func(ctx context.Context, vendorType string, status string) ([]int64, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*task.Task, error)

	// GetLogFunc mocks the GetLog method.
	GetLogFunc func(ctx context.Context, id int64) ([]byte, error)

	// GetLogByJobIDFunc mocks the GetLogByJobID method.
	GetLogByJobIDFunc func(ctx context.Context, jobID string) ([]byte, error)

	// IsTaskFinishedFunc mocks the IsTaskFinished method.
	IsTaskFinishedFunc func(ctx context.Context, reportID string) bool

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*task.Task, error)

	// ListScanTasksByReportUUIDFunc mocks the ListScanTasksByReportUUID method.
	ListScanTasksByReportUUIDFunc func(ctx context.Context, uuid string) ([]*task.Task, error)

	// RetrieveStatusFromTaskFunc mocks the RetrieveStatusFromTask method.
	RetrieveStatusFromTaskFunc func(ctx context.Context, reportID string) string

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context, id int64) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, task1 *task.Task, props ...string) error

	// UpdateExtraAttrsFunc mocks the UpdateExtraAttrs method.
	UpdateExtraAttrsFunc func(ctx context.Context, id int64, extraAttrs map[string]any) error

	// UpdateStatusInBatchFunc mocks the UpdateStatusInBatch method.
	UpdateStatusInBatchFunc func(ctx context.Context, jobIDs []string, status string, batchSize int) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExecutionID is the executionID argument value.
			ExecutionID int64
			// Job is the job argument value.
			Job *task.Job
			// ExtraAttrs is the extraAttrs argument value.
			ExtraAttrs []map[string]any
		}
		// ExecutionIDsByVendorAndStatus holds details about calls to the ExecutionIDsByVendorAndStatus method.
		ExecutionIDsByVendorAndStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VendorType is the vendorType argument value.
			VendorType string
			// Status is the status argument value.
			Status string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetLog holds details about calls to the GetLog method.
		GetLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetLogByJobID holds details about calls to the GetLogByJobID method.
		GetLogByJobID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// IsTaskFinished holds details about calls to the IsTaskFinished method.
		IsTaskFinished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReportID is the reportID argument value.
			ReportID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// ListScanTasksByReportUUID holds details about calls to the ListScanTasksByReportUUID method.
		ListScanTasksByReportUUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UUID is the uuid argument value.
			UUID string
		}
		// RetrieveStatusFromTask holds details about calls to the RetrieveStatusFromTask method.
		RetrieveStatusFromTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReportID is the reportID argument value.
			ReportID string
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Task1 is the task1 argument value.
			Task1 *task.Task
			// Props is the props argument value.
			Props []string
		}
		// UpdateExtraAttrs holds details about calls to the UpdateExtraAttrs method.
		UpdateExtraAttrs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// ExtraAttrs is the extraAttrs argument value.
			ExtraAttrs map[string]any
		}
		// UpdateStatusInBatch holds details about calls to the UpdateStatusInBatch method.
		UpdateStatusInBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobIDs is the jobIDs argument value.
			JobIDs []string
			// Status is the status argument value.
			Status string
			// BatchSize is the batchSize argument value.
			BatchSize int
		}
	}
	lockCount                         sync.RWMutex
	lockCreate                        sync.RWMutex
	lockExecutionIDsByVendorAndStatus sync.RWMutex
	lockGet                           sync.RWMutex
	lockGetLog                        sync.RWMutex
	lockGetLogByJobID                 sync.RWMutex
	lockIsTaskFinished                sync.RWMutex
	lockList                          sync.RWMutex
	lockListScanTasksByReportUUID     sync.RWMutex
	lockRetrieveStatusFromTask        sync.RWMutex
	lockStop                          sync.RWMutex
	lockUpdate                        sync.RWMutex
	lockUpdateExtraAttrs              sync.RWMutex
	lockUpdateStatusInBatch           sync.RWMutex
}

// Count calls CountFunc.
func (mock *Manager) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedManager.CountCalls())
func (mock *Manager) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Manager) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, executionID int64, job *task.Job, extraAttrs ...map[string]any) (int64, error) {
	callInfo := struct {
		Ctx         context.Context
		ExecutionID int64
		Job         *task.Job
		ExtraAttrs  []map[string]any
	}{
		Ctx:         ctx,
		ExecutionID: executionID,
		Job:         job,
		ExtraAttrs:  extraAttrs,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, executionID, job, extraAttrs...)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx         context.Context
	ExecutionID int64
	Job         *task.Job
	ExtraAttrs  []map[string]any
} {
	var calls []struct {
		Ctx         context.Context
		ExecutionID int64
		Job         *task.Job
		ExtraAttrs  []map[string]any
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// ExecutionIDsByVendorAndStatus calls ExecutionIDsByVendorAndStatusFunc.
func (mock *Manager) ExecutionIDsByVendorAndStatus(ctx context.Context, vendorType string, status string) ([]int64, error) {
	callInfo := struct {
		Ctx        context.Context
		VendorType string
		Status     string
	}{
		Ctx:        ctx,
		VendorType: vendorType,
		Status:     status,
	}
	mock.lockExecutionIDsByVendorAndStatus.Lock()
	mock.calls.ExecutionIDsByVendorAndStatus = append(mock.calls.ExecutionIDsByVendorAndStatus, callInfo)
	mock.lockExecutionIDsByVendorAndStatus.Unlock()
	if mock.ExecutionIDsByVendorAndStatusFunc == nil {
		var (
			int64s []int64
			err    error
		)
		return int64s, err
	}
	return mock.ExecutionIDsByVendorAndStatusFunc(ctx, vendorType, status)
}

// ExecutionIDsByVendorAndStatusCalls gets all the calls that were made to ExecutionIDsByVendorAndStatus.
// Check the length with:
//
//	len(mockedManager.ExecutionIDsByVendorAndStatusCalls())
func (mock *Manager) ExecutionIDsByVendorAndStatusCalls() []struct {
	Ctx        context.Context
	VendorType string
	Status     string
} {
	var calls []struct {
		Ctx        context.Context
		VendorType string
		Status     string
	}
	mock.lockExecutionIDsByVendorAndStatus.RLock()
	calls = mock.calls.ExecutionIDsByVendorAndStatus
	mock.lockExecutionIDsByVendorAndStatus.RUnlock()
	return calls
}

// ResetExecutionIDsByVendorAndStatusCalls reset all the calls that were made to ExecutionIDsByVendorAndStatus.
func (mock *Manager) ResetExecutionIDsByVendorAndStatusCalls() {
	mock.lockExecutionIDsByVendorAndStatus.Lock()
	mock.calls.ExecutionIDsByVendorAndStatus = nil
	mock.lockExecutionIDsByVendorAndStatus.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, id int64) (*task.Task, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			task1 *task.Task
			err   error
		)
		return task1, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetLog calls GetLogFunc.
func (mock *Manager) GetLog(ctx context.Context, id int64) ([]byte, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetLog.Lock()
	mock.calls.GetLog = append(mock.calls.GetLog, callInfo)
	mock.lockGetLog.Unlock()
	if mock.GetLogFunc == nil {
		var (
			log []byte
			err error
		)
		return log, err
	}
	return mock.GetLogFunc(ctx, id)
}

// GetLogCalls gets all the calls that were made to GetLog.
// Check the length with:
//
//	len(mockedManager.GetLogCalls())
func (mock *Manager) GetLogCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetLog.RLock()
	calls = mock.calls.GetLog
	mock.lockGetLog.RUnlock()
	return calls
}

// ResetGetLogCalls reset all the calls that were made to GetLog.
func (mock *Manager) ResetGetLogCalls() {
	mock.lockGetLog.Lock()
	mock.calls.GetLog = nil
	mock.lockGetLog.Unlock()
}

// GetLogByJobID calls GetLogByJobIDFunc.
func (mock *Manager) GetLogByJobID(ctx context.Context, jobID string) ([]byte, error) {
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockGetLogByJobID.Lock()
	mock.calls.GetLogByJobID = append(mock.calls.GetLogByJobID, callInfo)
	mock.lockGetLogByJobID.Unlock()
	if mock.GetLogByJobIDFunc == nil {
		var (
			log []byte
			err error
		)
		return log, err
	}
	return mock.GetLogByJobIDFunc(ctx, jobID)
}

// GetLogByJobIDCalls gets all the calls that were made to GetLogByJobID.
// Check the length with:
//
//	len(mockedManager.GetLogByJobIDCalls())
func (mock *Manager) GetLogByJobIDCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockGetLogByJobID.RLock()
	calls = mock.calls.GetLogByJobID
	mock.lockGetLogByJobID.RUnlock()
	return calls
}

// ResetGetLogByJobIDCalls reset all the calls that were made to GetLogByJobID.
func (mock *Manager) ResetGetLogByJobIDCalls() {
	mock.lockGetLogByJobID.Lock()
	mock.calls.GetLogByJobID = nil
	mock.lockGetLogByJobID.Unlock()
}

// IsTaskFinished calls IsTaskFinishedFunc.
func (mock *Manager) IsTaskFinished(ctx context.Context, reportID string) bool {
	callInfo := struct {
		Ctx      context.Context
		ReportID string
	}{
		Ctx:      ctx,
		ReportID: reportID,
	}
	mock.lockIsTaskFinished.Lock()
	mock.calls.IsTaskFinished = append(mock.calls.IsTaskFinished, callInfo)
	mock.lockIsTaskFinished.Unlock()
	if mock.IsTaskFinishedFunc == nil {
		var (
			b bool
		)
		return b
	}
	return mock.IsTaskFinishedFunc(ctx, reportID)
}

// IsTaskFinishedCalls gets all the calls that were made to IsTaskFinished.
// Check the length with:
//
//	len(mockedManager.IsTaskFinishedCalls())
func (mock *Manager) IsTaskFinishedCalls() []struct {
	Ctx      context.Context
	ReportID string
} {
	var calls []struct {
		Ctx      context.Context
		ReportID string
	}
	mock.lockIsTaskFinished.RLock()
	calls = mock.calls.IsTaskFinished
	mock.lockIsTaskFinished.RUnlock()
	return calls
}

// ResetIsTaskFinishedCalls reset all the calls that were made to IsTaskFinished.
func (mock *Manager) ResetIsTaskFinishedCalls() {
	mock.lockIsTaskFinished.Lock()
	mock.calls.IsTaskFinished = nil
	mock.lockIsTaskFinished.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*task.Task, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			tasks []*task.Task
			err   error
		)
		return tasks, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ListScanTasksByReportUUID calls ListScanTasksByReportUUIDFunc.
func (mock *Manager) ListScanTasksByReportUUID(ctx context.Context, uuid string) ([]*task.Task, error) {
	callInfo := struct {
		Ctx  context.Context
		UUID string
	}{
		Ctx:  ctx,
		UUID: uuid,
	}
	mock.lockListScanTasksByReportUUID.Lock()
	mock.calls.ListScanTasksByReportUUID = append(mock.calls.ListScanTasksByReportUUID, callInfo)
	mock.lockListScanTasksByReportUUID.Unlock()
	if mock.ListScanTasksByReportUUIDFunc == nil {
		var (
			tasks []*task.Task
			err   error
		)
		return tasks, err
	}
	return mock.ListScanTasksByReportUUIDFunc(ctx, uuid)
}

// ListScanTasksByReportUUIDCalls gets all the calls that were made to ListScanTasksByReportUUID.
// Check the length with:
//
//	len(mockedManager.ListScanTasksByReportUUIDCalls())
func (mock *Manager) ListScanTasksByReportUUIDCalls() []struct {
	Ctx  context.Context
	UUID string
} {
	var calls []struct {
		Ctx  context.Context
		UUID string
	}
	mock.lockListScanTasksByReportUUID.RLock()
	calls = mock.calls.ListScanTasksByReportUUID
	mock.lockListScanTasksByReportUUID.RUnlock()
	return calls
}

// ResetListScanTasksByReportUUIDCalls reset all the calls that were made to ListScanTasksByReportUUID.
func (mock *Manager) ResetListScanTasksByReportUUIDCalls() {
	mock.lockListScanTasksByReportUUID.Lock()
	mock.calls.ListScanTasksByReportUUID = nil
	mock.lockListScanTasksByReportUUID.Unlock()
}

// RetrieveStatusFromTask calls RetrieveStatusFromTaskFunc.
func (mock *Manager) RetrieveStatusFromTask(ctx context.Context, reportID string) string {
	callInfo := struct {
		Ctx      context.Context
		ReportID string
	}{
		Ctx:      ctx,
		ReportID: reportID,
	}
	mock.lockRetrieveStatusFromTask.Lock()
	mock.calls.RetrieveStatusFromTask = append(mock.calls.RetrieveStatusFromTask, callInfo)
	mock.lockRetrieveStatusFromTask.Unlock()
	if mock.RetrieveStatusFromTaskFunc == nil {
		var (
			s string
		)
		return s
	}
	return mock.RetrieveStatusFromTaskFunc(ctx, reportID)
}

// RetrieveStatusFromTaskCalls gets all the calls that were made to RetrieveStatusFromTask.
// Check the length with:
//
//	len(mockedManager.RetrieveStatusFromTaskCalls())
func (mock *Manager) RetrieveStatusFromTaskCalls() []struct {
	Ctx      context.Context
	ReportID string
} {
	var calls []struct {
		Ctx      context.Context
		ReportID string
	}
	mock.lockRetrieveStatusFromTask.RLock()
	calls = mock.calls.RetrieveStatusFromTask
	mock.lockRetrieveStatusFromTask.RUnlock()
	return calls
}

// ResetRetrieveStatusFromTaskCalls reset all the calls that were made to RetrieveStatusFromTask.
func (mock *Manager) ResetRetrieveStatusFromTaskCalls() {
	mock.lockRetrieveStatusFromTask.Lock()
	mock.calls.RetrieveStatusFromTask = nil
	mock.lockRetrieveStatusFromTask.Unlock()
}

// Stop calls StopFunc.
func (mock *Manager) Stop(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	if mock.StopFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.StopFunc(ctx, id)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedManager.StopCalls())
func (mock *Manager) StopCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// ResetStopCalls reset all the calls that were made to Stop.
func (mock *Manager) ResetStopCalls() {
	mock.lockStop.Lock()
	mock.calls.Stop = nil
	mock.lockStop.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, task1 *task.Task, props ...string) error {
	callInfo := struct {
		Ctx   context.Context
		Task1 *task.Task
		Props []string
	}{
		Ctx:   ctx,
		Task1: task1,
		Props: props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, task1, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx   context.Context
	Task1 *task.Task
	Props []string
} {
	var calls []struct {
		Ctx   context.Context
		Task1 *task.Task
		Props []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// UpdateExtraAttrs calls UpdateExtraAttrsFunc.
func (mock *Manager) UpdateExtraAttrs(ctx context.Context, id int64, extraAttrs map[string]any) error {
	callInfo := struct {
		Ctx        context.Context
		ID         int64
		ExtraAttrs map[string]any
	}{
		Ctx:        ctx,
		ID:         id,
		ExtraAttrs: extraAttrs,
	}
	mock.lockUpdateExtraAttrs.Lock()
	mock.calls.UpdateExtraAttrs = append(mock.calls.UpdateExtraAttrs, callInfo)
	mock.lockUpdateExtraAttrs.Unlock()
	if mock.UpdateExtraAttrsFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateExtraAttrsFunc(ctx, id, extraAttrs)
}

// UpdateExtraAttrsCalls gets all the calls that were made to UpdateExtraAttrs.
// Check the length with:
//
//	len(mockedManager.UpdateExtraAttrsCalls())
func (mock *Manager) UpdateExtraAttrsCalls() []struct {
	Ctx        context.Context
	ID         int64
	ExtraAttrs map[string]any
} {
	var calls []struct {
		Ctx        context.Context
		ID         int64
		ExtraAttrs map[string]any
	}
	mock.lockUpdateExtraAttrs.RLock()
	calls = mock.calls.UpdateExtraAttrs
	mock.lockUpdateExtraAttrs.RUnlock()
	return calls
}

// ResetUpdateExtraAttrsCalls reset all the calls that were made to UpdateExtraAttrs.
func (mock *Manager) ResetUpdateExtraAttrsCalls() {
	mock.lockUpdateExtraAttrs.Lock()
	mock.calls.UpdateExtraAttrs = nil
	mock.lockUpdateExtraAttrs.Unlock()
}

// UpdateStatusInBatch calls UpdateStatusInBatchFunc.
func (mock *Manager) UpdateStatusInBatch(ctx context.Context, jobIDs []string, status string, batchSize int) error {
	callInfo := struct {
		Ctx       context.Context
		JobIDs    []string
		Status    string
		BatchSize int
	}{
		Ctx:       ctx,
		JobIDs:    jobIDs,
		Status:    status,
		BatchSize: batchSize,
	}
	mock.lockUpdateStatusInBatch.Lock()
	mock.calls.UpdateStatusInBatch = append(mock.calls.UpdateStatusInBatch, callInfo)
	mock.lockUpdateStatusInBatch.Unlock()
	if mock.UpdateStatusInBatchFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateStatusInBatchFunc(ctx, jobIDs, status, batchSize)
}

// UpdateStatusInBatchCalls gets all the calls that were made to UpdateStatusInBatch.
// Check the length with:
//
//	len(mockedManager.UpdateStatusInBatchCalls())
func (mock *Manager) UpdateStatusInBatchCalls() []struct {
	Ctx       context.Context
	JobIDs    []string
	Status    string
	BatchSize int
} {
	var calls []struct {
		Ctx       context.Context
		JobIDs    []string
		Status    string
		BatchSize int
	}
	mock.lockUpdateStatusInBatch.RLock()
	calls = mock.calls.UpdateStatusInBatch
	mock.lockUpdateStatusInBatch.RUnlock()
	return calls
}

// ResetUpdateStatusInBatchCalls reset all the calls that were made to UpdateStatusInBatch.
func (mock *Manager) ResetUpdateStatusInBatchCalls() {
	mock.lockUpdateStatusInBatch.Lock()
	mock.calls.UpdateStatusInBatch = nil
	mock.lockUpdateStatusInBatch.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockExecutionIDsByVendorAndStatus.Lock()
	mock.calls.ExecutionIDsByVendorAndStatus = nil
	mock.lockExecutionIDsByVendorAndStatus.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetLog.Lock()
	mock.calls.GetLog = nil
	mock.lockGetLog.Unlock()

	mock.lockGetLogByJobID.Lock()
	mock.calls.GetLogByJobID = nil
	mock.lockGetLogByJobID.Unlock()

	mock.lockIsTaskFinished.Lock()
	mock.calls.IsTaskFinished = nil
	mock.lockIsTaskFinished.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockListScanTasksByReportUUID.Lock()
	mock.calls.ListScanTasksByReportUUID = nil
	mock.lockListScanTasksByReportUUID.Unlock()

	mock.lockRetrieveStatusFromTask.Lock()
	mock.calls.RetrieveStatusFromTask = nil
	mock.lockRetrieveStatusFromTask.Unlock()

	mock.lockStop.Lock()
	mock.calls.Stop = nil
	mock.lockStop.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()

	mock.lockUpdateExtraAttrs.Lock()
	mock.calls.UpdateExtraAttrs = nil
	mock.lockUpdateExtraAttrs.Unlock()

	mock.lockUpdateStatusInBatch.Lock()
	mock.calls.UpdateStatusInBatch = nil
	mock.lockUpdateStatusInBatch.Unlock()
}
