# Cross-platform Go binary compilation
#
# CI-aware: local builds native arch only, CI builds all platforms
# Explicit PLATFORMS=... always wins

version: '3'

vars:
  LDFLAGS_PROD: "-extldflags=-static -s -w"
  GCFLAGS_DEBUG: "all=-N -l"
  VERSION_LDFLAGS: '-X github.com/goharbor/harbor/src/pkg/version.GitCommit={{.GIT_COMMIT}} -X github.com/goharbor/harbor/src/pkg/version.ReleaseVersion={{.VERSION}}'
  DEFAULT_PLATFORMS: '{{.IMAGE_PLATFORMS | default "linux/amd64,linux/arm64"}}'
  IS_CI:
    sh: '[ -n "${CI:-}${GITHUB_ACTIONS:-}${GITLAB_CI:-}${JENKINS_URL:-}" ] && echo "true" || echo "false"'
  PLATFORMS: '{{.PLATFORMS | default (ternary .DEFAULT_PLATFORMS (printf "linux/%s" ARCH) (eq .IS_CI "true"))}}'

tasks:
  all-binaries:
    desc: "Build all Harbor binaries (CI-aware)"
    cmds:
      - for: { var: PLATFORMS, split: ',' }
        task: _build-platform
        vars: { PLATFORM: '{{.ITEM | trim | replace "/" "-"}}' }
      - cmd: 'echo "Binaries:"; find bin -type f -exec ls -lh {} \;'
        silent: true

  _build-platform:
    internal: true
    requires:
      vars: [PLATFORM]
    cmds:
      - for: [core, jobservice, registryctl, exporter]
        task: 'binary:{{.ITEM}}:{{.PLATFORM}}'

  # --- Internal Go Build ---

  _go-build:
    internal: true
    label: 'build:{{.OUTPUT_NAME}}:{{.PLATFORM}}'
    requires:
      vars: [PLATFORM, MAIN_PATH, OUTPUT_NAME]
    vars:
      GOOS: '{{index (splitList "-" .PLATFORM) 0}}'
      GOARCH: '{{index (splitList "-" .PLATFORM) 1}}'
      OUTPUT: 'bin/{{.PLATFORM}}/{{.OUTPUT_NAME}}'
      GO_LDFLAGS: '{{.GO_LDFLAGS | default .LDFLAGS_PROD}}'
      GCFLAGS: '{{.GCFLAGS | default ""}}'
    dir: src
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
      CGO_ENABLED: '0'
    cmds:
      - cmd: mkdir -p $(dirname ../{{.OUTPUT}})
        silent: true
      - go build {{.GOBUILD_FLAGS}} -gcflags="{{.GCFLAGS}}" -ldflags="{{.GO_LDFLAGS}} {{.VERSION_LDFLAGS}}" -o ../{{.OUTPUT}} {{.MAIN_PATH}}

  # --- Binary Tasks ---

  binary:core:*:
    desc: "Build Harbor core binary"
    sources:
      - src/core/**/*.go
      - src/controller/**/*.go
      - src/server/**/*.go
      - src/pkg/**/*.go
      - src/lib/**/*.go
      - src/go.mod
      - src/go.sum
    generates:
      - bin/{{index .MATCH 0}}/core
    deps: [gen-apis]
    cmds:
      - task: _go-build
        vars:
          PLATFORM: '{{index .MATCH 0}}'
          MAIN_PATH: ./core/main.go
          OUTPUT_NAME: core

  binary:core:*:debug:
    desc: "Build Harbor core binary with debug symbols"
    deps: [gen-apis]
    cmds:
      - task: _go-build
        vars:
          PLATFORM: '{{index .MATCH 0}}'
          MAIN_PATH: ./core/main.go
          OUTPUT_NAME: core
          GO_LDFLAGS: ''
          GCFLAGS: '{{.GCFLAGS_DEBUG}}'

  binary:jobservice:*:
    desc: "Build Harbor jobservice binary"
    sources:
      - src/jobservice/**/*.go
      - src/pkg/**/*.go
      - src/lib/**/*.go
      - src/go.mod
      - src/go.sum
    generates:
      - bin/{{index .MATCH 0}}/jobservice
    cmds:
      - task: _go-build
        vars:
          PLATFORM: '{{index .MATCH 0}}'
          MAIN_PATH: ./jobservice/main.go
          OUTPUT_NAME: jobservice

  binary:registryctl:*:
    desc: "Build Harbor registryctl binary"
    sources:
      - src/registryctl/**/*.go
      - src/pkg/**/*.go
      - src/lib/**/*.go
      - src/go.mod
      - src/go.sum
    generates:
      - bin/{{index .MATCH 0}}/registryctl
    cmds:
      - task: _go-build
        vars:
          PLATFORM: '{{index .MATCH 0}}'
          MAIN_PATH: ./registryctl/main.go
          OUTPUT_NAME: registryctl

  binary:exporter:*:
    desc: "Build Harbor exporter binary"
    sources:
      - src/cmd/exporter/**/*.go
      - src/pkg/**/*.go
      - src/lib/**/*.go
      - src/go.mod
      - src/go.sum
    generates:
      - bin/{{index .MATCH 0}}/harbor-exporter
    cmds:
      - task: _go-build
        vars:
          PLATFORM: '{{index .MATCH 0}}'
          MAIN_PATH: ./cmd/exporter/main.go
          OUTPUT_NAME: harbor-exporter

  # --- API Generation ---

  require-swagger:
    internal: true
    run: once
    status:
      - command -v swagger
    cmd: go install github.com/go-swagger/go-swagger/cmd/swagger@{{.SWAGGER_VERSION}}

  gen-apis:
    desc: "Generate API server code from OpenAPI spec"
    run: once
    deps: [require-swagger]
    sources:
      - api/v2.0/swagger.yaml
      - tools/swagger/templates/**/*
    generates:
      - src/server/v2.0/models/*.go
      - src/server/v2.0/restapi/**/*.go
    cmds:
      - mkdir -p src/server/v2.0
      - >-
        swagger generate server
        --template-dir=./tools/swagger/templates
        --exclude-main
        --additional-initialism=CVE
        --additional-initialism=GC
        --additional-initialism=OIDC
        -f ./api/v2.0/swagger.yaml
        -A harbor
        --target ./src/server/v2.0

  gen-apis:frontend:
    desc: "Generate frontend API code from OpenAPI spec"
    sources:
      - api/v2.0/swagger.yaml
    generates:
      - src/portal/ng-swagger-gen/models.ts
    method: checksum
    dir: src/portal
    cmds:
      - node scripts/convert-yaml-to-json.js
      - npx ng-swagger-gen -i ng-swagger-gen/swagger.json -o ng-swagger-gen
      - node scripts/delete-swagger-json.js

  # --- Utilities ---

  clean:
    desc: "Clean all built binaries and generated API code"
    cmds:
      - rm -rf bin/ src/server/v2.0/models/ src/server/v2.0/restapi/
      - rm -rf src/portal/ng-swagger-gen/models/ src/portal/ng-swagger-gen/services/
      - rm -f src/portal/ng-swagger-gen/*.ts

  verify:
    desc: "Verify all binaries are executable"
    preconditions:
      - sh: test -d bin
        msg: "No binaries found. Run 'task build:all-binaries' first."
    vars:
      BINARIES:
        sh: find bin -type f
    cmds:
      - for: { var: BINARIES }
        cmd: 'file {{.ITEM}} | grep -q "executable" && echo "ok {{.ITEM}}" || echo "FAIL {{.ITEM}}"'
