version: '3'

vars:
  # Paths
  COMPOSE_FILE: devenv/docker-compose.yml
  TOKEN_KEY_FILE: devenv/token_service_key.pem

  # Database (only vars used in task commands)
  POSTGRES_USER: postgres
  POSTGRES_DB: registry

  # Slot-based port allocation: SLOT=0 gives default ports, SLOT=1 offsets +100, etc.
  SLOT: '{{.SLOT | default "0"}}'

  PORT_CORE:         { sh: 'echo $((8080  + {{.SLOT}} * 100))' }
  PORT_PORTAL:       { sh: 'echo $((4200  + {{.SLOT}} * 100))' }
  PORT_POSTGRES:     { sh: 'echo $((5432  + {{.SLOT}} * 100))' }
  PORT_REDIS:        { sh: 'echo $((6379  + {{.SLOT}} * 100))' }
  PORT_REGISTRY:     { sh: 'echo $((50000 + {{.SLOT}} * 100))' }
  PORT_REGISTRYCTL:  { sh: 'echo $((8085  + {{.SLOT}} * 100))' }
  PORT_TRIVY:        { sh: 'echo $((8081  + {{.SLOT}} * 100))' }
  PORT_DEBUG_CORE:   { sh: 'echo $((2345  + {{.SLOT}} * 100))' }
  PORT_DEBUG_JOB:    { sh: 'echo $((2346  + {{.SLOT}} * 100))' }
  PORT_DEBUG_REGCTL: { sh: 'echo $((2347  + {{.SLOT}} * 100))' }

  PROJECT_PREFIX: 'harbor-{{.SLOT}}'

env:
  COMPOSE_PROJECT_NAME:   '{{.PROJECT_PREFIX}}'
  PROJECT_PREFIX:         '{{.PROJECT_PREFIX}}'
  PORT_CORE:              '{{.PORT_CORE}}'
  PORT_PORTAL:            '{{.PORT_PORTAL}}'
  PORT_POSTGRES:          '{{.PORT_POSTGRES}}'
  PORT_REDIS:             '{{.PORT_REDIS}}'
  PORT_REGISTRY:          '{{.PORT_REGISTRY}}'
  PORT_REGISTRYCTL:       '{{.PORT_REGISTRYCTL}}'
  PORT_TRIVY:             '{{.PORT_TRIVY}}'
  PORT_DEBUG_CORE:        '{{.PORT_DEBUG_CORE}}'
  PORT_DEBUG_JOBSERVICE:  '{{.PORT_DEBUG_JOB}}'
  PORT_DEBUG_REGISTRYCTL: '{{.PORT_DEBUG_REGCTL}}'

tasks:
  # ---------------------------------------------------------------------------
  # Tool Installation
  # ---------------------------------------------------------------------------
  tools:install:
    internal: true
    status:
      - command -v {{.TOOL_NAME}}
    cmds:
      - go install {{.TOOL_PKG}}

  setup:
    desc: Install required Go development tools (for native development)
    cmds:
      - for:
          - { name: air, pkg: 'github.com/air-verse/air@latest' }
          - { name: dlv, pkg: 'github.com/go-delve/delve/cmd/dlv@{{.DELVE_VERSION}}' }
          - { name: govulncheck, pkg: 'golang.org/x/vuln/cmd/govulncheck@latest' }
        task: tools:install
        vars:
          TOOL_NAME: '{{.ITEM.name}}'
          TOOL_PKG: '{{.ITEM.pkg}}'
      - echo "All development tools installed"

  require-docker:
    internal: true
    run: once
    silent: true
    preconditions:
      - sh: command -v docker
        msg: "Docker is not installed. Please install Docker first."
      - sh: docker info > /dev/null 2>&1
        msg: "Docker daemon is not running. Please start Docker first."

  gen:private-key:
    desc: Generate RSA 4096 key for token signing (skipped if exists)
    status:
      - test -f {{.TOKEN_KEY_FILE}}
    cmds:
      - openssl genpkey -algorithm RSA -out {{.TOKEN_KEY_FILE}} -pkeyopt rsa_keygen_bits:4096
      - chmod 600 {{.TOKEN_KEY_FILE}}
      - echo "Generated {{.TOKEN_KEY_FILE}}"

  # ---------------------------------------------------------------------------
  # Info
  # ---------------------------------------------------------------------------
  info:
    desc: Show current SLOT and port assignments
    silent: true
    cmds:
      - |
        echo ""
        echo "Harbor Dev Environment (SLOT={{.SLOT}})"
        echo "================================"
        echo "  Portal:       http://localhost:{{.PORT_PORTAL}}"
        echo "  Core API:     http://localhost:{{.PORT_CORE}}/api/v2.0"
        echo "  PostgreSQL:   localhost:{{.PORT_POSTGRES}}"
        echo "  Redis:        localhost:{{.PORT_REDIS}}"
        echo "  Registry:     localhost:{{.PORT_REGISTRY}}"
        echo "  RegistryCtl:  localhost:{{.PORT_REGISTRYCTL}}"
        echo "  Trivy:        localhost:{{.PORT_TRIVY}}"
        echo "  Prefix:       {{.PROJECT_PREFIX}}"
        echo ""

  # ---------------------------------------------------------------------------
  # Full Development Environment (Containerized)
  # ---------------------------------------------------------------------------
  up:
    desc: "Start full dev environment. Use SKIP_TRIVY=true to exclude Trivy."
    deps: [require-docker, gen:private-key]
    vars:
      TRIVY_PROFILE: '{{if ne .SKIP_TRIVY "true"}}--profile trivy{{end}}'
    cmds:
      - task: :build:gen-apis
      - task: frontend:install
      - task: :build:gen-apis:frontend
      - defer: { task: dev:down, vars: { SKIP_TRIVY: "{{.SKIP_TRIVY}}" } }
      - task: info
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile registryctl {{.TRIVY_PROFILE}} up --build

  down:
    desc: Stop all dev environment services
    vars:
      TRIVY_PROFILE: '{{if ne .SKIP_TRIVY "true"}}--profile trivy{{end}}'
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile registryctl {{.TRIVY_PROFILE}} down
      - echo "Dev environment stopped"

  # ---------------------------------------------------------------------------
  # Infrastructure (Docker Compose)
  # ---------------------------------------------------------------------------
  infra:up:
    desc: Start infrastructure only (PostgreSQL, Redis, Registry)
    deps: [require-docker]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d
      - |
        echo "Waiting for PostgreSQL..."
        timeout=60 elapsed=0
        until docker compose -f {{.COMPOSE_FILE}} exec -T postgresql pg_isready -U postgres > /dev/null 2>&1; do
          [ $elapsed -ge $timeout ] && echo "PostgreSQL failed to start" && exit 1
          sleep 2; elapsed=$((elapsed + 2))
        done
      - echo "Infrastructure ready"
      - docker compose -f {{.COMPOSE_FILE}} ps

  infra:down:
    desc: Stop infrastructure services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} down

  infra:remove:
    desc: Remove infrastructure and all volumes
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile registryctl --profile trivy down -v

  # ---------------------------------------------------------------------------
  # Backend Services (Containerized)
  # ---------------------------------------------------------------------------
  backend:up:
    desc: Start Core + JobService + RegistryCtl containers with hot reload
    deps: [require-docker, gen:private-key]
    cmds:
      - task: :build:gen-apis
      - docker compose -f {{.COMPOSE_FILE}} --profile core --profile jobservice --profile registryctl up -d --build
      - |
        echo ""
        echo "API: http://localhost:{{.PORT_CORE}}/api/v2.0"
        echo ""

  backend:down:
    desc: Stop Core + JobService + RegistryCtl containers
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop core jobservice registryctl
      - docker compose -f {{.COMPOSE_FILE}} rm -f core jobservice registryctl

  backend:logs:
    desc: View backend container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile core --profile jobservice --profile registryctl logs -f

  backend:logs:core:
    desc: View Core container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs -f core

  backend:logs:jobservice:
    desc: View JobService container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs -f jobservice

  backend:logs:registryctl:
    desc: View RegistryCtl container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs -f registryctl

  backend:restart:
    desc: Restart backend containers
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} restart core jobservice registryctl

  # ---------------------------------------------------------------------------
  # Frontend (Native - alternative to containerized portal)
  # ---------------------------------------------------------------------------
  frontend:install:
    internal: true
    dir: src/portal
    preconditions:
      - sh: command -v bun
        msg: "bun is required for native frontend dev. Install: https://bun.sh"
    sources:
      - package.json
      - bun.lock
    generates:
      - node_modules/.bun-integrity
    cmd: bun install --ignore-scripts

  frontend:native:
    desc: Start Portal natively (alternative to --profile portal)
    silent: true
    dir: src/portal
    deps: [frontend:install]
    cmds:
      - task: :build:gen-apis:frontend
      - exec ./node_modules/.bin/ng serve --host 0.0.0.0 --hmr --disable-host-check

  frontend:build:
    desc: Build frontend for production
    dir: src/portal
    cmds:
      - npm run build

  frontend:test:
    desc: Run frontend tests in watch mode
    dir: src/portal
    cmds:
      - npm run test -- --watch

  frontend:test:once:
    desc: Run frontend tests once
    dir: src/portal
    cmds:
      - npm run test -- --watch=false

  # ---------------------------------------------------------------------------
  # Database Operations
  # ---------------------------------------------------------------------------
  db:migrate:
    desc: Run incremental database migrations via golang-migrate
    dir: src
    cmds:
      - |
        echo "Running migrations..."
        POSTGRESQL_HOST=localhost \
        POSTGRESQL_PORT={{.PORT_POSTGRES}} \
        POSTGRESQL_USERNAME={{.POSTGRES_USER}} \
        POSTGRESQL_PASSWORD=root123 \
        POSTGRESQL_DATABASE={{.POSTGRES_DB}} \
        POSTGRESQL_SSLMODE=disable \
        POSTGRES_MIGRATION_SCRIPTS_PATH=../make/migrations/postgresql/ \
        go run ./cmd/standalone-db-migrator/main.go

  db:init-schema:
    desc: Apply all migration SQL files from scratch (use after db:reset)
    cmds:
      - |
        echo "Applying all migrations from scratch..."
        docker compose -f {{.COMPOSE_FILE}} exec -T postgresql sh -c '
          for f in /migrations/postgresql/*.up.sql; do
            echo "Applying: $(basename $f)"
            psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}} -f "$f" -q
          done
        '
      - echo "Schema init complete"

  db:reset:
    desc: Reset database to clean state
    cmds:
      - |
        echo "WARNING: This will delete all data. Continue? (Ctrl+C to cancel)"
        read -p "Press Enter to continue..."
      - docker compose -f {{.COMPOSE_FILE}} exec -T postgresql dropdb -U {{.POSTGRES_USER}} {{.POSTGRES_DB}} --if-exists
      - docker compose -f {{.COMPOSE_FILE}} exec -T postgresql createdb -U {{.POSTGRES_USER}} {{.POSTGRES_DB}}
      - task: db:init-schema
      - echo "Database reset complete"

  db:shell:
    desc: Open PostgreSQL shell
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} exec postgresql psql -U {{.POSTGRES_USER}} -d {{.POSTGRES_DB}}

  # ---------------------------------------------------------------------------
  # Utilities
  # ---------------------------------------------------------------------------
  clean:
    desc: Clean temporary files and all containers/volumes
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile registryctl --profile trivy down -v
      - pkill -f "ng serve" || true
      - rm -rf tmp/
      - rm -rf src/portal/node_modules
      - rm -f build-errors.log
      - rm -f {{.TOKEN_KEY_FILE}}
      - echo "Clean complete"

  status:
    desc: Show status of all development services
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile registryctl --profile trivy ps

  logs:
    desc: View all container logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --profile portal --profile core --profile jobservice --profile registryctl --profile trivy logs -f
