#!/usr/bin/env bash
# Local TLS setup for Harbor using mkcert
# Generates certificates, token key, secrets — everything needed to start Harbor locally.
#
# Usage:
#   ./setup.sh        # generate all files, then: docker compose up -d
#   ./setup.sh clean   # remove generated files
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- Clean ---
if [[ "${1:-}" == "clean" ]]; then
  rm -rf "$SCRIPT_DIR/certs" "$SCRIPT_DIR/.env"
  rm -f "$COMPOSE_DIR/config/token_service_key.pem"
  echo "Cleaned generated files."
  exit 0
fi

# --- Prerequisites ---
for cmd in mkcert openssl docker; do
  command -v "$cmd" >/dev/null || { echo "Required: $cmd not found."; exit 1; }
done

# --- mkcert CA ---
mkcert -install 2>/dev/null

# --- TLS certificates ---
mkdir -p "$SCRIPT_DIR/certs"
mkcert -cert-file "$SCRIPT_DIR/certs/tls.crt" \
       -key-file "$SCRIPT_DIR/certs/tls.key" \
       localhost harbor.localhost 127.0.0.1 ::1

# --- Token signing key (PKCS#1 required by Harbor) ---
openssl genrsa -traditional -out "$COMPOSE_DIR/config/token_service_key.pem" 4096 2>/dev/null

# --- Generate secrets ---
CORE_SECRET=$(openssl rand -hex 32)
JOBSERVICE_SECRET=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 16)

# --- .env ---
cat > "$SCRIPT_DIR/.env" <<EOF
# Generated by setup.sh — do not commit
COMPOSE_FILE=${COMPOSE_DIR}/docker-compose.yaml:${SCRIPT_DIR}/docker-compose.yaml

HARBOR_TAG=v2.15.0
EXT_ENDPOINT=https://localhost

HARBOR_ADMIN_PASSWORD=Harbor12345
CORE_SECRET=${CORE_SECRET}
JOBSERVICE_SECRET=${JOBSERVICE_SECRET}
DB_PASSWORD=${DB_PASSWORD}

PORT_HTTPS=443
LOG_LEVEL=info
EOF

echo ""
echo "Setup complete."
echo ""
echo "  cd $(basename "$SCRIPT_DIR")"
echo "  docker compose up -d"
echo "  docker compose ps"
echo ""
echo "  UI:    https://localhost"
echo "  Login: admin / Harbor12345"
echo ""
echo "  docker login localhost -u admin -p Harbor12345"
echo "  docker tag alpine localhost/library/alpine:test"
echo "  docker push localhost/library/alpine:test"
