// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package dao

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/repository/model"
)

// DAO is a mock implementation of dao.DAO.
//
//	func TestSomethingThatUsesDAO(t *testing.T) {
//
//		// make and configure a mocked dao.DAO
//		mockedDAO := &DAO{
//			AddPullCountFunc: func(ctx context.Context, id int64, count uint64) error {
//				panic("mock out the AddPullCount method")
//			},
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, repository *model.RepoRecord) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*model.RepoRecord, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*model.RepoRecord, error) {
//				panic("mock out the List method")
//			},
//			NonEmptyReposFunc: func(ctx context.Context) ([]*model.RepoRecord, error) {
//				panic("mock out the NonEmptyRepos method")
//			},
//			UpdateFunc: func(ctx context.Context, repository *model.RepoRecord, props ...string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedDAO in code that requires dao.DAO
//		// and then make assertions.
//
//	}
type DAO struct {
	// AddPullCountFunc mocks the AddPullCount method.
	AddPullCountFunc func(ctx context.Context, id int64, count uint64) error

	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, repository *model.RepoRecord) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*model.RepoRecord, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*model.RepoRecord, error)

	// NonEmptyReposFunc mocks the NonEmptyRepos method.
	NonEmptyReposFunc func(ctx context.Context) ([]*model.RepoRecord, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, repository *model.RepoRecord, props ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddPullCount holds details about calls to the AddPullCount method.
		AddPullCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count uint64
		}
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repository is the repository argument value.
			Repository *model.RepoRecord
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// NonEmptyRepos holds details about calls to the NonEmptyRepos method.
		NonEmptyRepos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repository is the repository argument value.
			Repository *model.RepoRecord
			// Props is the props argument value.
			Props []string
		}
	}
	lockAddPullCount  sync.RWMutex
	lockCount         sync.RWMutex
	lockCreate        sync.RWMutex
	lockDelete        sync.RWMutex
	lockGet           sync.RWMutex
	lockList          sync.RWMutex
	lockNonEmptyRepos sync.RWMutex
	lockUpdate        sync.RWMutex
}

// AddPullCount calls AddPullCountFunc.
func (mock *DAO) AddPullCount(ctx context.Context, id int64, count uint64) error {
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		Count uint64
	}{
		Ctx:   ctx,
		ID:    id,
		Count: count,
	}
	mock.lockAddPullCount.Lock()
	mock.calls.AddPullCount = append(mock.calls.AddPullCount, callInfo)
	mock.lockAddPullCount.Unlock()
	if mock.AddPullCountFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AddPullCountFunc(ctx, id, count)
}

// AddPullCountCalls gets all the calls that were made to AddPullCount.
// Check the length with:
//
//	len(mockedDAO.AddPullCountCalls())
func (mock *DAO) AddPullCountCalls() []struct {
	Ctx   context.Context
	ID    int64
	Count uint64
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		Count uint64
	}
	mock.lockAddPullCount.RLock()
	calls = mock.calls.AddPullCount
	mock.lockAddPullCount.RUnlock()
	return calls
}

// ResetAddPullCountCalls reset all the calls that were made to AddPullCount.
func (mock *DAO) ResetAddPullCountCalls() {
	mock.lockAddPullCount.Lock()
	mock.calls.AddPullCount = nil
	mock.lockAddPullCount.Unlock()
}

// Count calls CountFunc.
func (mock *DAO) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			count int64
			err   error
		)
		return count, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedDAO.CountCalls())
func (mock *DAO) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *DAO) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *DAO) Create(ctx context.Context, repository *model.RepoRecord) (int64, error) {
	callInfo := struct {
		Ctx        context.Context
		Repository *model.RepoRecord
	}{
		Ctx:        ctx,
		Repository: repository,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, repository)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedDAO.CreateCalls())
func (mock *DAO) CreateCalls() []struct {
	Ctx        context.Context
	Repository *model.RepoRecord
} {
	var calls []struct {
		Ctx        context.Context
		Repository *model.RepoRecord
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *DAO) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *DAO) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedDAO.DeleteCalls())
func (mock *DAO) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *DAO) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *DAO) Get(ctx context.Context, id int64) (*model.RepoRecord, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			repository *model.RepoRecord
			err        error
		)
		return repository, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedDAO.GetCalls())
func (mock *DAO) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *DAO) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *DAO) List(ctx context.Context, query *q.Query) ([]*model.RepoRecord, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			repositories []*model.RepoRecord
			err          error
		)
		return repositories, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedDAO.ListCalls())
func (mock *DAO) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *DAO) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// NonEmptyRepos calls NonEmptyReposFunc.
func (mock *DAO) NonEmptyRepos(ctx context.Context) ([]*model.RepoRecord, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNonEmptyRepos.Lock()
	mock.calls.NonEmptyRepos = append(mock.calls.NonEmptyRepos, callInfo)
	mock.lockNonEmptyRepos.Unlock()
	if mock.NonEmptyReposFunc == nil {
		var (
			repoRecords []*model.RepoRecord
			err         error
		)
		return repoRecords, err
	}
	return mock.NonEmptyReposFunc(ctx)
}

// NonEmptyReposCalls gets all the calls that were made to NonEmptyRepos.
// Check the length with:
//
//	len(mockedDAO.NonEmptyReposCalls())
func (mock *DAO) NonEmptyReposCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNonEmptyRepos.RLock()
	calls = mock.calls.NonEmptyRepos
	mock.lockNonEmptyRepos.RUnlock()
	return calls
}

// ResetNonEmptyReposCalls reset all the calls that were made to NonEmptyRepos.
func (mock *DAO) ResetNonEmptyReposCalls() {
	mock.lockNonEmptyRepos.Lock()
	mock.calls.NonEmptyRepos = nil
	mock.lockNonEmptyRepos.Unlock()
}

// Update calls UpdateFunc.
func (mock *DAO) Update(ctx context.Context, repository *model.RepoRecord, props ...string) error {
	callInfo := struct {
		Ctx        context.Context
		Repository *model.RepoRecord
		Props      []string
	}{
		Ctx:        ctx,
		Repository: repository,
		Props:      props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, repository, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedDAO.UpdateCalls())
func (mock *DAO) UpdateCalls() []struct {
	Ctx        context.Context
	Repository *model.RepoRecord
	Props      []string
} {
	var calls []struct {
		Ctx        context.Context
		Repository *model.RepoRecord
		Props      []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *DAO) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DAO) ResetCalls() {
	mock.lockAddPullCount.Lock()
	mock.calls.AddPullCount = nil
	mock.lockAddPullCount.Unlock()

	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockNonEmptyRepos.Lock()
	mock.calls.NonEmptyRepos = nil
	mock.lockNonEmptyRepos.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
