// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package processor

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/controller/artifact/processor"
	"github.com/goharbor/harbor/src/pkg/artifact"
)

// Processor is a mock implementation of processor.Processor.
//
//	func TestSomethingThatUsesProcessor(t *testing.T) {
//
//		// make and configure a mocked processor.Processor
//		mockedProcessor := &Processor{
//			AbstractAdditionFunc: func(ctx context.Context, artifact1 *artifact.Artifact, additionType string) (*processor.Addition, error) {
//				panic("mock out the AbstractAddition method")
//			},
//			AbstractMetadataFunc: func(ctx context.Context, artifact1 *artifact.Artifact, manifest []byte) error {
//				panic("mock out the AbstractMetadata method")
//			},
//			GetArtifactTypeFunc: func(ctx context.Context, artifact1 *artifact.Artifact) string {
//				panic("mock out the GetArtifactType method")
//			},
//			ListAdditionTypesFunc: func(ctx context.Context, artifact1 *artifact.Artifact) []string {
//				panic("mock out the ListAdditionTypes method")
//			},
//		}
//
//		// use mockedProcessor in code that requires processor.Processor
//		// and then make assertions.
//
//	}
type Processor struct {
	// AbstractAdditionFunc mocks the AbstractAddition method.
	AbstractAdditionFunc func(ctx context.Context, artifact1 *artifact.Artifact, additionType string) (*processor.Addition, error)

	// AbstractMetadataFunc mocks the AbstractMetadata method.
	AbstractMetadataFunc func(ctx context.Context, artifact1 *artifact.Artifact, manifest []byte) error

	// GetArtifactTypeFunc mocks the GetArtifactType method.
	GetArtifactTypeFunc func(ctx context.Context, artifact1 *artifact.Artifact) string

	// ListAdditionTypesFunc mocks the ListAdditionTypes method.
	ListAdditionTypesFunc func(ctx context.Context, artifact1 *artifact.Artifact) []string

	// calls tracks calls to the methods.
	calls struct {
		// AbstractAddition holds details about calls to the AbstractAddition method.
		AbstractAddition []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
			// AdditionType is the additionType argument value.
			AdditionType string
		}
		// AbstractMetadata holds details about calls to the AbstractMetadata method.
		AbstractMetadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
			// Manifest is the manifest argument value.
			Manifest []byte
		}
		// GetArtifactType holds details about calls to the GetArtifactType method.
		GetArtifactType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
		}
		// ListAdditionTypes holds details about calls to the ListAdditionTypes method.
		ListAdditionTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Artifact1 is the artifact1 argument value.
			Artifact1 *artifact.Artifact
		}
	}
	lockAbstractAddition  sync.RWMutex
	lockAbstractMetadata  sync.RWMutex
	lockGetArtifactType   sync.RWMutex
	lockListAdditionTypes sync.RWMutex
}

// AbstractAddition calls AbstractAdditionFunc.
func (mock *Processor) AbstractAddition(ctx context.Context, artifact1 *artifact.Artifact, additionType string) (*processor.Addition, error) {
	callInfo := struct {
		Ctx          context.Context
		Artifact1    *artifact.Artifact
		AdditionType string
	}{
		Ctx:          ctx,
		Artifact1:    artifact1,
		AdditionType: additionType,
	}
	mock.lockAbstractAddition.Lock()
	mock.calls.AbstractAddition = append(mock.calls.AbstractAddition, callInfo)
	mock.lockAbstractAddition.Unlock()
	if mock.AbstractAdditionFunc == nil {
		var (
			addition *processor.Addition
			err      error
		)
		return addition, err
	}
	return mock.AbstractAdditionFunc(ctx, artifact1, additionType)
}

// AbstractAdditionCalls gets all the calls that were made to AbstractAddition.
// Check the length with:
//
//	len(mockedProcessor.AbstractAdditionCalls())
func (mock *Processor) AbstractAdditionCalls() []struct {
	Ctx          context.Context
	Artifact1    *artifact.Artifact
	AdditionType string
} {
	var calls []struct {
		Ctx          context.Context
		Artifact1    *artifact.Artifact
		AdditionType string
	}
	mock.lockAbstractAddition.RLock()
	calls = mock.calls.AbstractAddition
	mock.lockAbstractAddition.RUnlock()
	return calls
}

// ResetAbstractAdditionCalls reset all the calls that were made to AbstractAddition.
func (mock *Processor) ResetAbstractAdditionCalls() {
	mock.lockAbstractAddition.Lock()
	mock.calls.AbstractAddition = nil
	mock.lockAbstractAddition.Unlock()
}

// AbstractMetadata calls AbstractMetadataFunc.
func (mock *Processor) AbstractMetadata(ctx context.Context, artifact1 *artifact.Artifact, manifest []byte) error {
	callInfo := struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
		Manifest  []byte
	}{
		Ctx:       ctx,
		Artifact1: artifact1,
		Manifest:  manifest,
	}
	mock.lockAbstractMetadata.Lock()
	mock.calls.AbstractMetadata = append(mock.calls.AbstractMetadata, callInfo)
	mock.lockAbstractMetadata.Unlock()
	if mock.AbstractMetadataFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AbstractMetadataFunc(ctx, artifact1, manifest)
}

// AbstractMetadataCalls gets all the calls that were made to AbstractMetadata.
// Check the length with:
//
//	len(mockedProcessor.AbstractMetadataCalls())
func (mock *Processor) AbstractMetadataCalls() []struct {
	Ctx       context.Context
	Artifact1 *artifact.Artifact
	Manifest  []byte
} {
	var calls []struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
		Manifest  []byte
	}
	mock.lockAbstractMetadata.RLock()
	calls = mock.calls.AbstractMetadata
	mock.lockAbstractMetadata.RUnlock()
	return calls
}

// ResetAbstractMetadataCalls reset all the calls that were made to AbstractMetadata.
func (mock *Processor) ResetAbstractMetadataCalls() {
	mock.lockAbstractMetadata.Lock()
	mock.calls.AbstractMetadata = nil
	mock.lockAbstractMetadata.Unlock()
}

// GetArtifactType calls GetArtifactTypeFunc.
func (mock *Processor) GetArtifactType(ctx context.Context, artifact1 *artifact.Artifact) string {
	callInfo := struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
	}{
		Ctx:       ctx,
		Artifact1: artifact1,
	}
	mock.lockGetArtifactType.Lock()
	mock.calls.GetArtifactType = append(mock.calls.GetArtifactType, callInfo)
	mock.lockGetArtifactType.Unlock()
	if mock.GetArtifactTypeFunc == nil {
		var (
			s string
		)
		return s
	}
	return mock.GetArtifactTypeFunc(ctx, artifact1)
}

// GetArtifactTypeCalls gets all the calls that were made to GetArtifactType.
// Check the length with:
//
//	len(mockedProcessor.GetArtifactTypeCalls())
func (mock *Processor) GetArtifactTypeCalls() []struct {
	Ctx       context.Context
	Artifact1 *artifact.Artifact
} {
	var calls []struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
	}
	mock.lockGetArtifactType.RLock()
	calls = mock.calls.GetArtifactType
	mock.lockGetArtifactType.RUnlock()
	return calls
}

// ResetGetArtifactTypeCalls reset all the calls that were made to GetArtifactType.
func (mock *Processor) ResetGetArtifactTypeCalls() {
	mock.lockGetArtifactType.Lock()
	mock.calls.GetArtifactType = nil
	mock.lockGetArtifactType.Unlock()
}

// ListAdditionTypes calls ListAdditionTypesFunc.
func (mock *Processor) ListAdditionTypes(ctx context.Context, artifact1 *artifact.Artifact) []string {
	callInfo := struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
	}{
		Ctx:       ctx,
		Artifact1: artifact1,
	}
	mock.lockListAdditionTypes.Lock()
	mock.calls.ListAdditionTypes = append(mock.calls.ListAdditionTypes, callInfo)
	mock.lockListAdditionTypes.Unlock()
	if mock.ListAdditionTypesFunc == nil {
		var (
			strings []string
		)
		return strings
	}
	return mock.ListAdditionTypesFunc(ctx, artifact1)
}

// ListAdditionTypesCalls gets all the calls that were made to ListAdditionTypes.
// Check the length with:
//
//	len(mockedProcessor.ListAdditionTypesCalls())
func (mock *Processor) ListAdditionTypesCalls() []struct {
	Ctx       context.Context
	Artifact1 *artifact.Artifact
} {
	var calls []struct {
		Ctx       context.Context
		Artifact1 *artifact.Artifact
	}
	mock.lockListAdditionTypes.RLock()
	calls = mock.calls.ListAdditionTypes
	mock.lockListAdditionTypes.RUnlock()
	return calls
}

// ResetListAdditionTypesCalls reset all the calls that were made to ListAdditionTypes.
func (mock *Processor) ResetListAdditionTypesCalls() {
	mock.lockListAdditionTypes.Lock()
	mock.calls.ListAdditionTypes = nil
	mock.lockListAdditionTypes.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Processor) ResetCalls() {
	mock.lockAbstractAddition.Lock()
	mock.calls.AbstractAddition = nil
	mock.lockAbstractAddition.Unlock()

	mock.lockAbstractMetadata.Lock()
	mock.calls.AbstractMetadata = nil
	mock.lockAbstractMetadata.Unlock()

	mock.lockGetArtifactType.Lock()
	mock.calls.GetArtifactType = nil
	mock.lockGetArtifactType.Unlock()

	mock.lockListAdditionTypes.Lock()
	mock.calls.ListAdditionTypes = nil
	mock.lockListAdditionTypes.Unlock()
}
