// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package task

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/task"
)

// ExecutionController is a mock implementation of task.ExecutionController.
//
//	func TestSomethingThatUsesExecutionController(t *testing.T) {
//
//		// make and configure a mocked task.ExecutionController
//		mockedExecutionController := &ExecutionController{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*task.Execution, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*task.Execution, error) {
//				panic("mock out the List method")
//			},
//			StopFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedExecutionController in code that requires task.ExecutionController
//		// and then make assertions.
//
//	}
type ExecutionController struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*task.Execution, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*task.Execution, error)

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context, id int64) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
	}
	lockCount  sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockStop   sync.RWMutex
}

// Count calls CountFunc.
func (mock *ExecutionController) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedExecutionController.CountCalls())
func (mock *ExecutionController) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *ExecutionController) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Delete calls DeleteFunc.
func (mock *ExecutionController) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedExecutionController.DeleteCalls())
func (mock *ExecutionController) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *ExecutionController) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *ExecutionController) Get(ctx context.Context, id int64) (*task.Execution, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			execution *task.Execution
			err       error
		)
		return execution, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedExecutionController.GetCalls())
func (mock *ExecutionController) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *ExecutionController) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *ExecutionController) List(ctx context.Context, query *q.Query) ([]*task.Execution, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			executions []*task.Execution
			err        error
		)
		return executions, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedExecutionController.ListCalls())
func (mock *ExecutionController) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *ExecutionController) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Stop calls StopFunc.
func (mock *ExecutionController) Stop(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	if mock.StopFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.StopFunc(ctx, id)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedExecutionController.StopCalls())
func (mock *ExecutionController) StopCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// ResetStopCalls reset all the calls that were made to Stop.
func (mock *ExecutionController) ResetStopCalls() {
	mock.lockStop.Lock()
	mock.calls.Stop = nil
	mock.lockStop.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ExecutionController) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockStop.Lock()
	mock.calls.Stop = nil
	mock.lockStop.Unlock()
}
