// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package robot

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/controller/robot"
	"github.com/goharbor/harbor/src/lib/q"
)

// Controller is a mock implementation of robot.Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked robot.Controller
//		mockedController := &Controller{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, r *robot.Robot) (int64, string, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64, option ...*robot.Option) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64, option *robot.Option) (*robot.Robot, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query, option *robot.Option) ([]*robot.Robot, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, r *robot.Robot, option *robot.Option) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedController in code that requires robot.Controller
//		// and then make assertions.
//
//	}
type Controller struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, r *robot.Robot) (int64, string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64, option ...*robot.Option) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64, option *robot.Option) (*robot.Robot, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query, option *robot.Option) ([]*robot.Robot, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, r *robot.Robot, option *robot.Option) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *robot.Robot
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Option is the option argument value.
			Option []*robot.Option
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Option is the option argument value.
			Option *robot.Option
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
			// Option is the option argument value.
			Option *robot.Option
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *robot.Robot
			// Option is the option argument value.
			Option *robot.Option
		}
	}
	lockCount  sync.RWMutex
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Count calls CountFunc.
func (mock *Controller) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedController.CountCalls())
func (mock *Controller) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *Controller) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *Controller) Create(ctx context.Context, r *robot.Robot) (int64, string, error) {
	callInfo := struct {
		Ctx context.Context
		R   *robot.Robot
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			n   int64
			s   string
			err error
		)
		return n, s, err
	}
	return mock.CreateFunc(ctx, r)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedController.CreateCalls())
func (mock *Controller) CreateCalls() []struct {
	Ctx context.Context
	R   *robot.Robot
} {
	var calls []struct {
		Ctx context.Context
		R   *robot.Robot
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Controller) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Controller) Delete(ctx context.Context, id int64, option ...*robot.Option) error {
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		Option []*robot.Option
	}{
		Ctx:    ctx,
		ID:     id,
		Option: option,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id, option...)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedController.DeleteCalls())
func (mock *Controller) DeleteCalls() []struct {
	Ctx    context.Context
	ID     int64
	Option []*robot.Option
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		Option []*robot.Option
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Controller) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *Controller) Get(ctx context.Context, id int64, option *robot.Option) (*robot.Robot, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		Option *robot.Option
	}{
		Ctx:    ctx,
		ID:     id,
		Option: option,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			robot1 *robot.Robot
			err    error
		)
		return robot1, err
	}
	return mock.GetFunc(ctx, id, option)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedController.GetCalls())
func (mock *Controller) GetCalls() []struct {
	Ctx    context.Context
	ID     int64
	Option *robot.Option
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		Option *robot.Option
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Controller) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *Controller) List(ctx context.Context, query *q.Query, option *robot.Option) ([]*robot.Robot, error) {
	callInfo := struct {
		Ctx    context.Context
		Query  *q.Query
		Option *robot.Option
	}{
		Ctx:    ctx,
		Query:  query,
		Option: option,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			robots []*robot.Robot
			err    error
		)
		return robots, err
	}
	return mock.ListFunc(ctx, query, option)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedController.ListCalls())
func (mock *Controller) ListCalls() []struct {
	Ctx    context.Context
	Query  *q.Query
	Option *robot.Option
} {
	var calls []struct {
		Ctx    context.Context
		Query  *q.Query
		Option *robot.Option
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Controller) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Update calls UpdateFunc.
func (mock *Controller) Update(ctx context.Context, r *robot.Robot, option *robot.Option) error {
	callInfo := struct {
		Ctx    context.Context
		R      *robot.Robot
		Option *robot.Option
	}{
		Ctx:    ctx,
		R:      r,
		Option: option,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, r, option)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedController.UpdateCalls())
func (mock *Controller) UpdateCalls() []struct {
	Ctx    context.Context
	R      *robot.Robot
	Option *robot.Option
} {
	var calls []struct {
		Ctx    context.Context
		R      *robot.Robot
		Option *robot.Option
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Controller) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Controller) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
