// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package member

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/member/models"
)

// Manager is a mock implementation of member.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked member.Manager
//		mockedManager := &Manager{
//			AddProjectMemberFunc: func(ctx context.Context, member models.Member) (int, error) {
//				panic("mock out the AddProjectMember method")
//			},
//			DeleteFunc: func(ctx context.Context, projectID int64, memberID int) error {
//				panic("mock out the Delete method")
//			},
//			DeleteMemberByProjectIDFunc: func(ctx context.Context, projectID int64) error {
//				panic("mock out the DeleteMemberByProjectID method")
//			},
//			DeleteMemberByUserIDFunc: func(ctx context.Context, uid int) error {
//				panic("mock out the DeleteMemberByUserID method")
//			},
//			GetFunc: func(ctx context.Context, projectID int64, memberID int) (*models.Member, error) {
//				panic("mock out the Get method")
//			},
//			GetTotalOfProjectMembersFunc: func(ctx context.Context, projectID int64, query *q.Query, roles ...int) (int, error) {
//				panic("mock out the GetTotalOfProjectMembers method")
//			},
//			ListFunc: func(ctx context.Context, queryMember models.Member, query *q.Query) ([]*models.Member, error) {
//				panic("mock out the List method")
//			},
//			ListRolesFunc: func(ctx context.Context, user *models.User, projectID int64) ([]int, error) {
//				panic("mock out the ListRoles method")
//			},
//			SearchMemberByNameFunc: func(ctx context.Context, projectID int64, entityName string) ([]*models.Member, error) {
//				panic("mock out the SearchMemberByName method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, projectID int64, pmID int, role int) error {
//				panic("mock out the UpdateRole method")
//			},
//		}
//
//		// use mockedManager in code that requires member.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// AddProjectMemberFunc mocks the AddProjectMember method.
	AddProjectMemberFunc func(ctx context.Context, member models.Member) (int, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, projectID int64, memberID int) error

	// DeleteMemberByProjectIDFunc mocks the DeleteMemberByProjectID method.
	DeleteMemberByProjectIDFunc func(ctx context.Context, projectID int64) error

	// DeleteMemberByUserIDFunc mocks the DeleteMemberByUserID method.
	DeleteMemberByUserIDFunc func(ctx context.Context, uid int) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, projectID int64, memberID int) (*models.Member, error)

	// GetTotalOfProjectMembersFunc mocks the GetTotalOfProjectMembers method.
	GetTotalOfProjectMembersFunc func(ctx context.Context, projectID int64, query *q.Query, roles ...int) (int, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, queryMember models.Member, query *q.Query) ([]*models.Member, error)

	// ListRolesFunc mocks the ListRoles method.
	ListRolesFunc func(ctx context.Context, user *models.User, projectID int64) ([]int, error)

	// SearchMemberByNameFunc mocks the SearchMemberByName method.
	SearchMemberByNameFunc func(ctx context.Context, projectID int64, entityName string) ([]*models.Member, error)

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, projectID int64, pmID int, role int) error

	// calls tracks calls to the methods.
	calls struct {
		// AddProjectMember holds details about calls to the AddProjectMember method.
		AddProjectMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Member is the member argument value.
			Member models.Member
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// MemberID is the memberID argument value.
			MemberID int
		}
		// DeleteMemberByProjectID holds details about calls to the DeleteMemberByProjectID method.
		DeleteMemberByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// DeleteMemberByUserID holds details about calls to the DeleteMemberByUserID method.
		DeleteMemberByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UID is the uid argument value.
			UID int
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// MemberID is the memberID argument value.
			MemberID int
		}
		// GetTotalOfProjectMembers holds details about calls to the GetTotalOfProjectMembers method.
		GetTotalOfProjectMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Query is the query argument value.
			Query *q.Query
			// Roles is the roles argument value.
			Roles []int
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueryMember is the queryMember argument value.
			QueryMember models.Member
			// Query is the query argument value.
			Query *q.Query
		}
		// ListRoles holds details about calls to the ListRoles method.
		ListRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *models.User
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// SearchMemberByName holds details about calls to the SearchMemberByName method.
		SearchMemberByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// EntityName is the entityName argument value.
			EntityName string
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
			// PmID is the pmID argument value.
			PmID int
			// Role is the role argument value.
			Role int
		}
	}
	lockAddProjectMember         sync.RWMutex
	lockDelete                   sync.RWMutex
	lockDeleteMemberByProjectID  sync.RWMutex
	lockDeleteMemberByUserID     sync.RWMutex
	lockGet                      sync.RWMutex
	lockGetTotalOfProjectMembers sync.RWMutex
	lockList                     sync.RWMutex
	lockListRoles                sync.RWMutex
	lockSearchMemberByName       sync.RWMutex
	lockUpdateRole               sync.RWMutex
}

// AddProjectMember calls AddProjectMemberFunc.
func (mock *Manager) AddProjectMember(ctx context.Context, member models.Member) (int, error) {
	callInfo := struct {
		Ctx    context.Context
		Member models.Member
	}{
		Ctx:    ctx,
		Member: member,
	}
	mock.lockAddProjectMember.Lock()
	mock.calls.AddProjectMember = append(mock.calls.AddProjectMember, callInfo)
	mock.lockAddProjectMember.Unlock()
	if mock.AddProjectMemberFunc == nil {
		var (
			n   int
			err error
		)
		return n, err
	}
	return mock.AddProjectMemberFunc(ctx, member)
}

// AddProjectMemberCalls gets all the calls that were made to AddProjectMember.
// Check the length with:
//
//	len(mockedManager.AddProjectMemberCalls())
func (mock *Manager) AddProjectMemberCalls() []struct {
	Ctx    context.Context
	Member models.Member
} {
	var calls []struct {
		Ctx    context.Context
		Member models.Member
	}
	mock.lockAddProjectMember.RLock()
	calls = mock.calls.AddProjectMember
	mock.lockAddProjectMember.RUnlock()
	return calls
}

// ResetAddProjectMemberCalls reset all the calls that were made to AddProjectMember.
func (mock *Manager) ResetAddProjectMemberCalls() {
	mock.lockAddProjectMember.Lock()
	mock.calls.AddProjectMember = nil
	mock.lockAddProjectMember.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, projectID int64, memberID int) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		MemberID  int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		MemberID:  memberID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, projectID, memberID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	MemberID  int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		MemberID  int
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// DeleteMemberByProjectID calls DeleteMemberByProjectIDFunc.
func (mock *Manager) DeleteMemberByProjectID(ctx context.Context, projectID int64) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockDeleteMemberByProjectID.Lock()
	mock.calls.DeleteMemberByProjectID = append(mock.calls.DeleteMemberByProjectID, callInfo)
	mock.lockDeleteMemberByProjectID.Unlock()
	if mock.DeleteMemberByProjectIDFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteMemberByProjectIDFunc(ctx, projectID)
}

// DeleteMemberByProjectIDCalls gets all the calls that were made to DeleteMemberByProjectID.
// Check the length with:
//
//	len(mockedManager.DeleteMemberByProjectIDCalls())
func (mock *Manager) DeleteMemberByProjectIDCalls() []struct {
	Ctx       context.Context
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
	}
	mock.lockDeleteMemberByProjectID.RLock()
	calls = mock.calls.DeleteMemberByProjectID
	mock.lockDeleteMemberByProjectID.RUnlock()
	return calls
}

// ResetDeleteMemberByProjectIDCalls reset all the calls that were made to DeleteMemberByProjectID.
func (mock *Manager) ResetDeleteMemberByProjectIDCalls() {
	mock.lockDeleteMemberByProjectID.Lock()
	mock.calls.DeleteMemberByProjectID = nil
	mock.lockDeleteMemberByProjectID.Unlock()
}

// DeleteMemberByUserID calls DeleteMemberByUserIDFunc.
func (mock *Manager) DeleteMemberByUserID(ctx context.Context, uid int) error {
	callInfo := struct {
		Ctx context.Context
		UID int
	}{
		Ctx: ctx,
		UID: uid,
	}
	mock.lockDeleteMemberByUserID.Lock()
	mock.calls.DeleteMemberByUserID = append(mock.calls.DeleteMemberByUserID, callInfo)
	mock.lockDeleteMemberByUserID.Unlock()
	if mock.DeleteMemberByUserIDFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteMemberByUserIDFunc(ctx, uid)
}

// DeleteMemberByUserIDCalls gets all the calls that were made to DeleteMemberByUserID.
// Check the length with:
//
//	len(mockedManager.DeleteMemberByUserIDCalls())
func (mock *Manager) DeleteMemberByUserIDCalls() []struct {
	Ctx context.Context
	UID int
} {
	var calls []struct {
		Ctx context.Context
		UID int
	}
	mock.lockDeleteMemberByUserID.RLock()
	calls = mock.calls.DeleteMemberByUserID
	mock.lockDeleteMemberByUserID.RUnlock()
	return calls
}

// ResetDeleteMemberByUserIDCalls reset all the calls that were made to DeleteMemberByUserID.
func (mock *Manager) ResetDeleteMemberByUserIDCalls() {
	mock.lockDeleteMemberByUserID.Lock()
	mock.calls.DeleteMemberByUserID = nil
	mock.lockDeleteMemberByUserID.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, projectID int64, memberID int) (*models.Member, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		MemberID  int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		MemberID:  memberID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			member *models.Member
			err    error
		)
		return member, err
	}
	return mock.GetFunc(ctx, projectID, memberID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	MemberID  int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		MemberID  int
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// GetTotalOfProjectMembers calls GetTotalOfProjectMembersFunc.
func (mock *Manager) GetTotalOfProjectMembers(ctx context.Context, projectID int64, query *q.Query, roles ...int) (int, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		Query     *q.Query
		Roles     []int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		Query:     query,
		Roles:     roles,
	}
	mock.lockGetTotalOfProjectMembers.Lock()
	mock.calls.GetTotalOfProjectMembers = append(mock.calls.GetTotalOfProjectMembers, callInfo)
	mock.lockGetTotalOfProjectMembers.Unlock()
	if mock.GetTotalOfProjectMembersFunc == nil {
		var (
			n   int
			err error
		)
		return n, err
	}
	return mock.GetTotalOfProjectMembersFunc(ctx, projectID, query, roles...)
}

// GetTotalOfProjectMembersCalls gets all the calls that were made to GetTotalOfProjectMembers.
// Check the length with:
//
//	len(mockedManager.GetTotalOfProjectMembersCalls())
func (mock *Manager) GetTotalOfProjectMembersCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	Query     *q.Query
	Roles     []int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		Query     *q.Query
		Roles     []int
	}
	mock.lockGetTotalOfProjectMembers.RLock()
	calls = mock.calls.GetTotalOfProjectMembers
	mock.lockGetTotalOfProjectMembers.RUnlock()
	return calls
}

// ResetGetTotalOfProjectMembersCalls reset all the calls that were made to GetTotalOfProjectMembers.
func (mock *Manager) ResetGetTotalOfProjectMembersCalls() {
	mock.lockGetTotalOfProjectMembers.Lock()
	mock.calls.GetTotalOfProjectMembers = nil
	mock.lockGetTotalOfProjectMembers.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, queryMember models.Member, query *q.Query) ([]*models.Member, error) {
	callInfo := struct {
		Ctx         context.Context
		QueryMember models.Member
		Query       *q.Query
	}{
		Ctx:         ctx,
		QueryMember: queryMember,
		Query:       query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			members []*models.Member
			err     error
		)
		return members, err
	}
	return mock.ListFunc(ctx, queryMember, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx         context.Context
	QueryMember models.Member
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		QueryMember models.Member
		Query       *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// ListRoles calls ListRolesFunc.
func (mock *Manager) ListRoles(ctx context.Context, user *models.User, projectID int64) ([]int, error) {
	callInfo := struct {
		Ctx       context.Context
		User      *models.User
		ProjectID int64
	}{
		Ctx:       ctx,
		User:      user,
		ProjectID: projectID,
	}
	mock.lockListRoles.Lock()
	mock.calls.ListRoles = append(mock.calls.ListRoles, callInfo)
	mock.lockListRoles.Unlock()
	if mock.ListRolesFunc == nil {
		var (
			ints []int
			err  error
		)
		return ints, err
	}
	return mock.ListRolesFunc(ctx, user, projectID)
}

// ListRolesCalls gets all the calls that were made to ListRoles.
// Check the length with:
//
//	len(mockedManager.ListRolesCalls())
func (mock *Manager) ListRolesCalls() []struct {
	Ctx       context.Context
	User      *models.User
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		User      *models.User
		ProjectID int64
	}
	mock.lockListRoles.RLock()
	calls = mock.calls.ListRoles
	mock.lockListRoles.RUnlock()
	return calls
}

// ResetListRolesCalls reset all the calls that were made to ListRoles.
func (mock *Manager) ResetListRolesCalls() {
	mock.lockListRoles.Lock()
	mock.calls.ListRoles = nil
	mock.lockListRoles.Unlock()
}

// SearchMemberByName calls SearchMemberByNameFunc.
func (mock *Manager) SearchMemberByName(ctx context.Context, projectID int64, entityName string) ([]*models.Member, error) {
	callInfo := struct {
		Ctx        context.Context
		ProjectID  int64
		EntityName string
	}{
		Ctx:        ctx,
		ProjectID:  projectID,
		EntityName: entityName,
	}
	mock.lockSearchMemberByName.Lock()
	mock.calls.SearchMemberByName = append(mock.calls.SearchMemberByName, callInfo)
	mock.lockSearchMemberByName.Unlock()
	if mock.SearchMemberByNameFunc == nil {
		var (
			members []*models.Member
			err     error
		)
		return members, err
	}
	return mock.SearchMemberByNameFunc(ctx, projectID, entityName)
}

// SearchMemberByNameCalls gets all the calls that were made to SearchMemberByName.
// Check the length with:
//
//	len(mockedManager.SearchMemberByNameCalls())
func (mock *Manager) SearchMemberByNameCalls() []struct {
	Ctx        context.Context
	ProjectID  int64
	EntityName string
} {
	var calls []struct {
		Ctx        context.Context
		ProjectID  int64
		EntityName string
	}
	mock.lockSearchMemberByName.RLock()
	calls = mock.calls.SearchMemberByName
	mock.lockSearchMemberByName.RUnlock()
	return calls
}

// ResetSearchMemberByNameCalls reset all the calls that were made to SearchMemberByName.
func (mock *Manager) ResetSearchMemberByNameCalls() {
	mock.lockSearchMemberByName.Lock()
	mock.calls.SearchMemberByName = nil
	mock.lockSearchMemberByName.Unlock()
}

// UpdateRole calls UpdateRoleFunc.
func (mock *Manager) UpdateRole(ctx context.Context, projectID int64, pmID int, role int) error {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
		PmID      int
		Role      int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		PmID:      pmID,
		Role:      role,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	if mock.UpdateRoleFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateRoleFunc(ctx, projectID, pmID, role)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockedManager.UpdateRoleCalls())
func (mock *Manager) UpdateRoleCalls() []struct {
	Ctx       context.Context
	ProjectID int64
	PmID      int
	Role      int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
		PmID      int
		Role      int
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}

// ResetUpdateRoleCalls reset all the calls that were made to UpdateRole.
func (mock *Manager) ResetUpdateRoleCalls() {
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = nil
	mock.lockUpdateRole.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockAddProjectMember.Lock()
	mock.calls.AddProjectMember = nil
	mock.lockAddProjectMember.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDeleteMemberByProjectID.Lock()
	mock.calls.DeleteMemberByProjectID = nil
	mock.lockDeleteMemberByProjectID.Unlock()

	mock.lockDeleteMemberByUserID.Lock()
	mock.calls.DeleteMemberByUserID = nil
	mock.lockDeleteMemberByUserID.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockGetTotalOfProjectMembers.Lock()
	mock.calls.GetTotalOfProjectMembers = nil
	mock.lockGetTotalOfProjectMembers.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockListRoles.Lock()
	mock.calls.ListRoles = nil
	mock.lockListRoles.Unlock()

	mock.lockSearchMemberByName.Lock()
	mock.calls.SearchMemberByName = nil
	mock.lockSearchMemberByName.Unlock()

	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = nil
	mock.lockUpdateRole.Unlock()
}
