// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package dao

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/audit/model"
)

// DAO is a mock implementation of dao.DAO.
//
//	func TestSomethingThatUsesDAO(t *testing.T) {
//
//		// make and configure a mocked dao.DAO
//		mockedDAO := &DAO{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, access *model.AuditLog) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*model.AuditLog, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*model.AuditLog, error) {
//				panic("mock out the List method")
//			},
//			PurgeFunc: func(ctx context.Context, retentionHour int, includeOperations []string, dryRun bool) (int64, error) {
//				panic("mock out the Purge method")
//			},
//			UpdateUsernameFunc: func(ctx context.Context, username string, usernameReplace string) error {
//				panic("mock out the UpdateUsername method")
//			},
//		}
//
//		// use mockedDAO in code that requires dao.DAO
//		// and then make assertions.
//
//	}
type DAO struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, access *model.AuditLog) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*model.AuditLog, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*model.AuditLog, error)

	// PurgeFunc mocks the Purge method.
	PurgeFunc func(ctx context.Context, retentionHour int, includeOperations []string, dryRun bool) (int64, error)

	// UpdateUsernameFunc mocks the UpdateUsername method.
	UpdateUsernameFunc func(ctx context.Context, username string, usernameReplace string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Access is the access argument value.
			Access *model.AuditLog
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Purge holds details about calls to the Purge method.
		Purge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RetentionHour is the retentionHour argument value.
			RetentionHour int
			// IncludeOperations is the includeOperations argument value.
			IncludeOperations []string
			// DryRun is the dryRun argument value.
			DryRun bool
		}
		// UpdateUsername holds details about calls to the UpdateUsername method.
		UpdateUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Username is the username argument value.
			Username string
			// UsernameReplace is the usernameReplace argument value.
			UsernameReplace string
		}
	}
	lockCount          sync.RWMutex
	lockCreate         sync.RWMutex
	lockDelete         sync.RWMutex
	lockGet            sync.RWMutex
	lockList           sync.RWMutex
	lockPurge          sync.RWMutex
	lockUpdateUsername sync.RWMutex
}

// Count calls CountFunc.
func (mock *DAO) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedDAO.CountCalls())
func (mock *DAO) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *DAO) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *DAO) Create(ctx context.Context, access *model.AuditLog) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		Access *model.AuditLog
	}{
		Ctx:    ctx,
		Access: access,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, access)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedDAO.CreateCalls())
func (mock *DAO) CreateCalls() []struct {
	Ctx    context.Context
	Access *model.AuditLog
} {
	var calls []struct {
		Ctx    context.Context
		Access *model.AuditLog
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *DAO) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *DAO) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedDAO.DeleteCalls())
func (mock *DAO) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *DAO) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// Get calls GetFunc.
func (mock *DAO) Get(ctx context.Context, id int64) (*model.AuditLog, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			access *model.AuditLog
			err    error
		)
		return access, err
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedDAO.GetCalls())
func (mock *DAO) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *DAO) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *DAO) List(ctx context.Context, query *q.Query) ([]*model.AuditLog, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			access []*model.AuditLog
			err    error
		)
		return access, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedDAO.ListCalls())
func (mock *DAO) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *DAO) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Purge calls PurgeFunc.
func (mock *DAO) Purge(ctx context.Context, retentionHour int, includeOperations []string, dryRun bool) (int64, error) {
	callInfo := struct {
		Ctx               context.Context
		RetentionHour     int
		IncludeOperations []string
		DryRun            bool
	}{
		Ctx:               ctx,
		RetentionHour:     retentionHour,
		IncludeOperations: includeOperations,
		DryRun:            dryRun,
	}
	mock.lockPurge.Lock()
	mock.calls.Purge = append(mock.calls.Purge, callInfo)
	mock.lockPurge.Unlock()
	if mock.PurgeFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.PurgeFunc(ctx, retentionHour, includeOperations, dryRun)
}

// PurgeCalls gets all the calls that were made to Purge.
// Check the length with:
//
//	len(mockedDAO.PurgeCalls())
func (mock *DAO) PurgeCalls() []struct {
	Ctx               context.Context
	RetentionHour     int
	IncludeOperations []string
	DryRun            bool
} {
	var calls []struct {
		Ctx               context.Context
		RetentionHour     int
		IncludeOperations []string
		DryRun            bool
	}
	mock.lockPurge.RLock()
	calls = mock.calls.Purge
	mock.lockPurge.RUnlock()
	return calls
}

// ResetPurgeCalls reset all the calls that were made to Purge.
func (mock *DAO) ResetPurgeCalls() {
	mock.lockPurge.Lock()
	mock.calls.Purge = nil
	mock.lockPurge.Unlock()
}

// UpdateUsername calls UpdateUsernameFunc.
func (mock *DAO) UpdateUsername(ctx context.Context, username string, usernameReplace string) error {
	callInfo := struct {
		Ctx             context.Context
		Username        string
		UsernameReplace string
	}{
		Ctx:             ctx,
		Username:        username,
		UsernameReplace: usernameReplace,
	}
	mock.lockUpdateUsername.Lock()
	mock.calls.UpdateUsername = append(mock.calls.UpdateUsername, callInfo)
	mock.lockUpdateUsername.Unlock()
	if mock.UpdateUsernameFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateUsernameFunc(ctx, username, usernameReplace)
}

// UpdateUsernameCalls gets all the calls that were made to UpdateUsername.
// Check the length with:
//
//	len(mockedDAO.UpdateUsernameCalls())
func (mock *DAO) UpdateUsernameCalls() []struct {
	Ctx             context.Context
	Username        string
	UsernameReplace string
} {
	var calls []struct {
		Ctx             context.Context
		Username        string
		UsernameReplace string
	}
	mock.lockUpdateUsername.RLock()
	calls = mock.calls.UpdateUsername
	mock.lockUpdateUsername.RUnlock()
	return calls
}

// ResetUpdateUsernameCalls reset all the calls that were made to UpdateUsername.
func (mock *DAO) ResetUpdateUsernameCalls() {
	mock.lockUpdateUsername.Lock()
	mock.calls.UpdateUsername = nil
	mock.lockUpdateUsername.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DAO) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockPurge.Lock()
	mock.calls.Purge = nil
	mock.lockPurge.Unlock()

	mock.lockUpdateUsername.Lock()
	mock.calls.UpdateUsername = nil
	mock.lockUpdateUsername.Unlock()
}
