// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package purge

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/controller/purge"
)

// Controller is a mock implementation of purge.Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked purge.Controller
//		mockedController := &Controller{
//			StartFunc: func(ctx context.Context, policy purge.JobPolicy, trigger string) (int64, error) {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedController in code that requires purge.Controller
//		// and then make assertions.
//
//	}
type Controller struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, policy purge.JobPolicy, trigger string) (int64, error)

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context, id int64) error

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Policy is the policy argument value.
			Policy purge.JobPolicy
			// Trigger is the trigger argument value.
			Trigger string
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
	}
	lockStart sync.RWMutex
	lockStop  sync.RWMutex
}

// Start calls StartFunc.
func (mock *Controller) Start(ctx context.Context, policy purge.JobPolicy, trigger string) (int64, error) {
	callInfo := struct {
		Ctx     context.Context
		Policy  purge.JobPolicy
		Trigger string
	}{
		Ctx:     ctx,
		Policy:  policy,
		Trigger: trigger,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	if mock.StartFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.StartFunc(ctx, policy, trigger)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedController.StartCalls())
func (mock *Controller) StartCalls() []struct {
	Ctx     context.Context
	Policy  purge.JobPolicy
	Trigger string
} {
	var calls []struct {
		Ctx     context.Context
		Policy  purge.JobPolicy
		Trigger string
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// ResetStartCalls reset all the calls that were made to Start.
func (mock *Controller) ResetStartCalls() {
	mock.lockStart.Lock()
	mock.calls.Start = nil
	mock.lockStart.Unlock()
}

// Stop calls StopFunc.
func (mock *Controller) Stop(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	if mock.StopFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.StopFunc(ctx, id)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedController.StopCalls())
func (mock *Controller) StopCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// ResetStopCalls reset all the calls that were made to Stop.
func (mock *Controller) ResetStopCalls() {
	mock.lockStop.Lock()
	mock.calls.Stop = nil
	mock.lockStop.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Controller) ResetCalls() {
	mock.lockStart.Lock()
	mock.calls.Start = nil
	mock.lockStart.Unlock()

	mock.lockStop.Lock()
	mock.calls.Stop = nil
	mock.lockStop.Unlock()
}
