// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package securityhub

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/scan/dao/scan"
	"github.com/goharbor/harbor/src/pkg/securityhub/model"
)

// Manager is a mock implementation of securityhub.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked securityhub.Manager
//		mockedManager := &Manager{
//			DangerousArtifactsFunc: func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*model.DangerousArtifact, error) {
//				panic("mock out the DangerousArtifacts method")
//			},
//			DangerousCVEsFunc: func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*scan.VulnerabilityRecord, error) {
//				panic("mock out the DangerousCVEs method")
//			},
//			ListVulsFunc: func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*model.VulnerabilityItem, error) {
//				panic("mock out the ListVuls method")
//			},
//			ScannedArtifactsCountFunc: func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) (int64, error) {
//				panic("mock out the ScannedArtifactsCount method")
//			},
//			SummaryFunc: func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) (*model.Summary, error) {
//				panic("mock out the Summary method")
//			},
//			TotalArtifactsCountFunc: func(ctx context.Context, projectID int64) (int64, error) {
//				panic("mock out the TotalArtifactsCount method")
//			},
//			TotalVulsFunc: func(ctx context.Context, scannerUUID string, projectID int64, tuneCount bool, query *q.Query) (int64, error) {
//				panic("mock out the TotalVuls method")
//			},
//		}
//
//		// use mockedManager in code that requires securityhub.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// DangerousArtifactsFunc mocks the DangerousArtifacts method.
	DangerousArtifactsFunc func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*model.DangerousArtifact, error)

	// DangerousCVEsFunc mocks the DangerousCVEs method.
	DangerousCVEsFunc func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*scan.VulnerabilityRecord, error)

	// ListVulsFunc mocks the ListVuls method.
	ListVulsFunc func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*model.VulnerabilityItem, error)

	// ScannedArtifactsCountFunc mocks the ScannedArtifactsCount method.
	ScannedArtifactsCountFunc func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) (int64, error)

	// SummaryFunc mocks the Summary method.
	SummaryFunc func(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) (*model.Summary, error)

	// TotalArtifactsCountFunc mocks the TotalArtifactsCount method.
	TotalArtifactsCountFunc func(ctx context.Context, projectID int64) (int64, error)

	// TotalVulsFunc mocks the TotalVuls method.
	TotalVulsFunc func(ctx context.Context, scannerUUID string, projectID int64, tuneCount bool, query *q.Query) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// DangerousArtifacts holds details about calls to the DangerousArtifacts method.
		DangerousArtifacts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ScannerUUID is the scannerUUID argument value.
			ScannerUUID string
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// DangerousCVEs holds details about calls to the DangerousCVEs method.
		DangerousCVEs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ScannerUUID is the scannerUUID argument value.
			ScannerUUID string
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// ListVuls holds details about calls to the ListVuls method.
		ListVuls []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ScannerUUID is the scannerUUID argument value.
			ScannerUUID string
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// ScannedArtifactsCount holds details about calls to the ScannedArtifactsCount method.
		ScannedArtifactsCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ScannerUUID is the scannerUUID argument value.
			ScannerUUID string
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// Summary holds details about calls to the Summary method.
		Summary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ScannerUUID is the scannerUUID argument value.
			ScannerUUID string
			// ProjectID is the projectID argument value.
			ProjectID int64
			// Query is the query argument value.
			Query *q.Query
		}
		// TotalArtifactsCount holds details about calls to the TotalArtifactsCount method.
		TotalArtifactsCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID int64
		}
		// TotalVuls holds details about calls to the TotalVuls method.
		TotalVuls []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ScannerUUID is the scannerUUID argument value.
			ScannerUUID string
			// ProjectID is the projectID argument value.
			ProjectID int64
			// TuneCount is the tuneCount argument value.
			TuneCount bool
			// Query is the query argument value.
			Query *q.Query
		}
	}
	lockDangerousArtifacts    sync.RWMutex
	lockDangerousCVEs         sync.RWMutex
	lockListVuls              sync.RWMutex
	lockScannedArtifactsCount sync.RWMutex
	lockSummary               sync.RWMutex
	lockTotalArtifactsCount   sync.RWMutex
	lockTotalVuls             sync.RWMutex
}

// DangerousArtifacts calls DangerousArtifactsFunc.
func (mock *Manager) DangerousArtifacts(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*model.DangerousArtifact, error) {
	callInfo := struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}{
		Ctx:         ctx,
		ScannerUUID: scannerUUID,
		ProjectID:   projectID,
		Query:       query,
	}
	mock.lockDangerousArtifacts.Lock()
	mock.calls.DangerousArtifacts = append(mock.calls.DangerousArtifacts, callInfo)
	mock.lockDangerousArtifacts.Unlock()
	if mock.DangerousArtifactsFunc == nil {
		var (
			dangerousArtifacts []*model.DangerousArtifact
			err                error
		)
		return dangerousArtifacts, err
	}
	return mock.DangerousArtifactsFunc(ctx, scannerUUID, projectID, query)
}

// DangerousArtifactsCalls gets all the calls that were made to DangerousArtifacts.
// Check the length with:
//
//	len(mockedManager.DangerousArtifactsCalls())
func (mock *Manager) DangerousArtifactsCalls() []struct {
	Ctx         context.Context
	ScannerUUID string
	ProjectID   int64
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}
	mock.lockDangerousArtifacts.RLock()
	calls = mock.calls.DangerousArtifacts
	mock.lockDangerousArtifacts.RUnlock()
	return calls
}

// ResetDangerousArtifactsCalls reset all the calls that were made to DangerousArtifacts.
func (mock *Manager) ResetDangerousArtifactsCalls() {
	mock.lockDangerousArtifacts.Lock()
	mock.calls.DangerousArtifacts = nil
	mock.lockDangerousArtifacts.Unlock()
}

// DangerousCVEs calls DangerousCVEsFunc.
func (mock *Manager) DangerousCVEs(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*scan.VulnerabilityRecord, error) {
	callInfo := struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}{
		Ctx:         ctx,
		ScannerUUID: scannerUUID,
		ProjectID:   projectID,
		Query:       query,
	}
	mock.lockDangerousCVEs.Lock()
	mock.calls.DangerousCVEs = append(mock.calls.DangerousCVEs, callInfo)
	mock.lockDangerousCVEs.Unlock()
	if mock.DangerousCVEsFunc == nil {
		var (
			vulnerabilityRecords []*scan.VulnerabilityRecord
			err                  error
		)
		return vulnerabilityRecords, err
	}
	return mock.DangerousCVEsFunc(ctx, scannerUUID, projectID, query)
}

// DangerousCVEsCalls gets all the calls that were made to DangerousCVEs.
// Check the length with:
//
//	len(mockedManager.DangerousCVEsCalls())
func (mock *Manager) DangerousCVEsCalls() []struct {
	Ctx         context.Context
	ScannerUUID string
	ProjectID   int64
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}
	mock.lockDangerousCVEs.RLock()
	calls = mock.calls.DangerousCVEs
	mock.lockDangerousCVEs.RUnlock()
	return calls
}

// ResetDangerousCVEsCalls reset all the calls that were made to DangerousCVEs.
func (mock *Manager) ResetDangerousCVEsCalls() {
	mock.lockDangerousCVEs.Lock()
	mock.calls.DangerousCVEs = nil
	mock.lockDangerousCVEs.Unlock()
}

// ListVuls calls ListVulsFunc.
func (mock *Manager) ListVuls(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) ([]*model.VulnerabilityItem, error) {
	callInfo := struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}{
		Ctx:         ctx,
		ScannerUUID: scannerUUID,
		ProjectID:   projectID,
		Query:       query,
	}
	mock.lockListVuls.Lock()
	mock.calls.ListVuls = append(mock.calls.ListVuls, callInfo)
	mock.lockListVuls.Unlock()
	if mock.ListVulsFunc == nil {
		var (
			vulnerabilityItems []*model.VulnerabilityItem
			err                error
		)
		return vulnerabilityItems, err
	}
	return mock.ListVulsFunc(ctx, scannerUUID, projectID, query)
}

// ListVulsCalls gets all the calls that were made to ListVuls.
// Check the length with:
//
//	len(mockedManager.ListVulsCalls())
func (mock *Manager) ListVulsCalls() []struct {
	Ctx         context.Context
	ScannerUUID string
	ProjectID   int64
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}
	mock.lockListVuls.RLock()
	calls = mock.calls.ListVuls
	mock.lockListVuls.RUnlock()
	return calls
}

// ResetListVulsCalls reset all the calls that were made to ListVuls.
func (mock *Manager) ResetListVulsCalls() {
	mock.lockListVuls.Lock()
	mock.calls.ListVuls = nil
	mock.lockListVuls.Unlock()
}

// ScannedArtifactsCount calls ScannedArtifactsCountFunc.
func (mock *Manager) ScannedArtifactsCount(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}{
		Ctx:         ctx,
		ScannerUUID: scannerUUID,
		ProjectID:   projectID,
		Query:       query,
	}
	mock.lockScannedArtifactsCount.Lock()
	mock.calls.ScannedArtifactsCount = append(mock.calls.ScannedArtifactsCount, callInfo)
	mock.lockScannedArtifactsCount.Unlock()
	if mock.ScannedArtifactsCountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.ScannedArtifactsCountFunc(ctx, scannerUUID, projectID, query)
}

// ScannedArtifactsCountCalls gets all the calls that were made to ScannedArtifactsCount.
// Check the length with:
//
//	len(mockedManager.ScannedArtifactsCountCalls())
func (mock *Manager) ScannedArtifactsCountCalls() []struct {
	Ctx         context.Context
	ScannerUUID string
	ProjectID   int64
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}
	mock.lockScannedArtifactsCount.RLock()
	calls = mock.calls.ScannedArtifactsCount
	mock.lockScannedArtifactsCount.RUnlock()
	return calls
}

// ResetScannedArtifactsCountCalls reset all the calls that were made to ScannedArtifactsCount.
func (mock *Manager) ResetScannedArtifactsCountCalls() {
	mock.lockScannedArtifactsCount.Lock()
	mock.calls.ScannedArtifactsCount = nil
	mock.lockScannedArtifactsCount.Unlock()
}

// Summary calls SummaryFunc.
func (mock *Manager) Summary(ctx context.Context, scannerUUID string, projectID int64, query *q.Query) (*model.Summary, error) {
	callInfo := struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}{
		Ctx:         ctx,
		ScannerUUID: scannerUUID,
		ProjectID:   projectID,
		Query:       query,
	}
	mock.lockSummary.Lock()
	mock.calls.Summary = append(mock.calls.Summary, callInfo)
	mock.lockSummary.Unlock()
	if mock.SummaryFunc == nil {
		var (
			summary *model.Summary
			err     error
		)
		return summary, err
	}
	return mock.SummaryFunc(ctx, scannerUUID, projectID, query)
}

// SummaryCalls gets all the calls that were made to Summary.
// Check the length with:
//
//	len(mockedManager.SummaryCalls())
func (mock *Manager) SummaryCalls() []struct {
	Ctx         context.Context
	ScannerUUID string
	ProjectID   int64
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		Query       *q.Query
	}
	mock.lockSummary.RLock()
	calls = mock.calls.Summary
	mock.lockSummary.RUnlock()
	return calls
}

// ResetSummaryCalls reset all the calls that were made to Summary.
func (mock *Manager) ResetSummaryCalls() {
	mock.lockSummary.Lock()
	mock.calls.Summary = nil
	mock.lockSummary.Unlock()
}

// TotalArtifactsCount calls TotalArtifactsCountFunc.
func (mock *Manager) TotalArtifactsCount(ctx context.Context, projectID int64) (int64, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID int64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
	}
	mock.lockTotalArtifactsCount.Lock()
	mock.calls.TotalArtifactsCount = append(mock.calls.TotalArtifactsCount, callInfo)
	mock.lockTotalArtifactsCount.Unlock()
	if mock.TotalArtifactsCountFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.TotalArtifactsCountFunc(ctx, projectID)
}

// TotalArtifactsCountCalls gets all the calls that were made to TotalArtifactsCount.
// Check the length with:
//
//	len(mockedManager.TotalArtifactsCountCalls())
func (mock *Manager) TotalArtifactsCountCalls() []struct {
	Ctx       context.Context
	ProjectID int64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID int64
	}
	mock.lockTotalArtifactsCount.RLock()
	calls = mock.calls.TotalArtifactsCount
	mock.lockTotalArtifactsCount.RUnlock()
	return calls
}

// ResetTotalArtifactsCountCalls reset all the calls that were made to TotalArtifactsCount.
func (mock *Manager) ResetTotalArtifactsCountCalls() {
	mock.lockTotalArtifactsCount.Lock()
	mock.calls.TotalArtifactsCount = nil
	mock.lockTotalArtifactsCount.Unlock()
}

// TotalVuls calls TotalVulsFunc.
func (mock *Manager) TotalVuls(ctx context.Context, scannerUUID string, projectID int64, tuneCount bool, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		TuneCount   bool
		Query       *q.Query
	}{
		Ctx:         ctx,
		ScannerUUID: scannerUUID,
		ProjectID:   projectID,
		TuneCount:   tuneCount,
		Query:       query,
	}
	mock.lockTotalVuls.Lock()
	mock.calls.TotalVuls = append(mock.calls.TotalVuls, callInfo)
	mock.lockTotalVuls.Unlock()
	if mock.TotalVulsFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.TotalVulsFunc(ctx, scannerUUID, projectID, tuneCount, query)
}

// TotalVulsCalls gets all the calls that were made to TotalVuls.
// Check the length with:
//
//	len(mockedManager.TotalVulsCalls())
func (mock *Manager) TotalVulsCalls() []struct {
	Ctx         context.Context
	ScannerUUID string
	ProjectID   int64
	TuneCount   bool
	Query       *q.Query
} {
	var calls []struct {
		Ctx         context.Context
		ScannerUUID string
		ProjectID   int64
		TuneCount   bool
		Query       *q.Query
	}
	mock.lockTotalVuls.RLock()
	calls = mock.calls.TotalVuls
	mock.lockTotalVuls.RUnlock()
	return calls
}

// ResetTotalVulsCalls reset all the calls that were made to TotalVuls.
func (mock *Manager) ResetTotalVulsCalls() {
	mock.lockTotalVuls.Lock()
	mock.calls.TotalVuls = nil
	mock.lockTotalVuls.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockDangerousArtifacts.Lock()
	mock.calls.DangerousArtifacts = nil
	mock.lockDangerousArtifacts.Unlock()

	mock.lockDangerousCVEs.Lock()
	mock.calls.DangerousCVEs = nil
	mock.lockDangerousCVEs.Unlock()

	mock.lockListVuls.Lock()
	mock.calls.ListVuls = nil
	mock.lockListVuls.Unlock()

	mock.lockScannedArtifactsCount.Lock()
	mock.calls.ScannedArtifactsCount = nil
	mock.lockScannedArtifactsCount.Unlock()

	mock.lockSummary.Lock()
	mock.calls.Summary = nil
	mock.lockSummary.Unlock()

	mock.lockTotalArtifactsCount.Lock()
	mock.calls.TotalArtifactsCount = nil
	mock.lockTotalArtifactsCount.Unlock()

	mock.lockTotalVuls.Lock()
	mock.calls.TotalVuls = nil
	mock.lockTotalVuls.Unlock()
}
