// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package scheduler

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/scheduler"
)

// Scheduler is a mock implementation of scheduler.Scheduler.
//
//	func TestSomethingThatUsesScheduler(t *testing.T) {
//
//		// make and configure a mocked scheduler.Scheduler
//		mockedScheduler := &Scheduler{
//			CountSchedulesFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the CountSchedules method")
//			},
//			GetScheduleFunc: func(ctx context.Context, id int64) (*scheduler.Schedule, error) {
//				panic("mock out the GetSchedule method")
//			},
//			ListSchedulesFunc: func(ctx context.Context, query *q.Query) ([]*scheduler.Schedule, error) {
//				panic("mock out the ListSchedules method")
//			},
//			ScheduleFunc: func(ctx context.Context, vendorType string, vendorID int64, cronType string, cron string, callbackFuncName string, callbackFuncParams any, extraAttrs map[string]any) (int64, error) {
//				panic("mock out the Schedule method")
//			},
//			UnScheduleByIDFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the UnScheduleByID method")
//			},
//			UnScheduleByVendorFunc: func(ctx context.Context, vendorType string, vendorID int64) error {
//				panic("mock out the UnScheduleByVendor method")
//			},
//		}
//
//		// use mockedScheduler in code that requires scheduler.Scheduler
//		// and then make assertions.
//
//	}
type Scheduler struct {
	// CountSchedulesFunc mocks the CountSchedules method.
	CountSchedulesFunc func(ctx context.Context, query *q.Query) (int64, error)

	// GetScheduleFunc mocks the GetSchedule method.
	GetScheduleFunc func(ctx context.Context, id int64) (*scheduler.Schedule, error)

	// ListSchedulesFunc mocks the ListSchedules method.
	ListSchedulesFunc func(ctx context.Context, query *q.Query) ([]*scheduler.Schedule, error)

	// ScheduleFunc mocks the Schedule method.
	ScheduleFunc func(ctx context.Context, vendorType string, vendorID int64, cronType string, cron string, callbackFuncName string, callbackFuncParams any, extraAttrs map[string]any) (int64, error)

	// UnScheduleByIDFunc mocks the UnScheduleByID method.
	UnScheduleByIDFunc func(ctx context.Context, id int64) error

	// UnScheduleByVendorFunc mocks the UnScheduleByVendor method.
	UnScheduleByVendorFunc func(ctx context.Context, vendorType string, vendorID int64) error

	// calls tracks calls to the methods.
	calls struct {
		// CountSchedules holds details about calls to the CountSchedules method.
		CountSchedules []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// GetSchedule holds details about calls to the GetSchedule method.
		GetSchedule []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// ListSchedules holds details about calls to the ListSchedules method.
		ListSchedules []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Schedule holds details about calls to the Schedule method.
		Schedule []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VendorType is the vendorType argument value.
			VendorType string
			// VendorID is the vendorID argument value.
			VendorID int64
			// CronType is the cronType argument value.
			CronType string
			// Cron is the cron argument value.
			Cron string
			// CallbackFuncName is the callbackFuncName argument value.
			CallbackFuncName string
			// CallbackFuncParams is the callbackFuncParams argument value.
			CallbackFuncParams any
			// ExtraAttrs is the extraAttrs argument value.
			ExtraAttrs map[string]any
		}
		// UnScheduleByID holds details about calls to the UnScheduleByID method.
		UnScheduleByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// UnScheduleByVendor holds details about calls to the UnScheduleByVendor method.
		UnScheduleByVendor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VendorType is the vendorType argument value.
			VendorType string
			// VendorID is the vendorID argument value.
			VendorID int64
		}
	}
	lockCountSchedules     sync.RWMutex
	lockGetSchedule        sync.RWMutex
	lockListSchedules      sync.RWMutex
	lockSchedule           sync.RWMutex
	lockUnScheduleByID     sync.RWMutex
	lockUnScheduleByVendor sync.RWMutex
}

// CountSchedules calls CountSchedulesFunc.
func (mock *Scheduler) CountSchedules(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCountSchedules.Lock()
	mock.calls.CountSchedules = append(mock.calls.CountSchedules, callInfo)
	mock.lockCountSchedules.Unlock()
	if mock.CountSchedulesFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CountSchedulesFunc(ctx, query)
}

// CountSchedulesCalls gets all the calls that were made to CountSchedules.
// Check the length with:
//
//	len(mockedScheduler.CountSchedulesCalls())
func (mock *Scheduler) CountSchedulesCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCountSchedules.RLock()
	calls = mock.calls.CountSchedules
	mock.lockCountSchedules.RUnlock()
	return calls
}

// ResetCountSchedulesCalls reset all the calls that were made to CountSchedules.
func (mock *Scheduler) ResetCountSchedulesCalls() {
	mock.lockCountSchedules.Lock()
	mock.calls.CountSchedules = nil
	mock.lockCountSchedules.Unlock()
}

// GetSchedule calls GetScheduleFunc.
func (mock *Scheduler) GetSchedule(ctx context.Context, id int64) (*scheduler.Schedule, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSchedule.Lock()
	mock.calls.GetSchedule = append(mock.calls.GetSchedule, callInfo)
	mock.lockGetSchedule.Unlock()
	if mock.GetScheduleFunc == nil {
		var (
			schedule *scheduler.Schedule
			err      error
		)
		return schedule, err
	}
	return mock.GetScheduleFunc(ctx, id)
}

// GetScheduleCalls gets all the calls that were made to GetSchedule.
// Check the length with:
//
//	len(mockedScheduler.GetScheduleCalls())
func (mock *Scheduler) GetScheduleCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetSchedule.RLock()
	calls = mock.calls.GetSchedule
	mock.lockGetSchedule.RUnlock()
	return calls
}

// ResetGetScheduleCalls reset all the calls that were made to GetSchedule.
func (mock *Scheduler) ResetGetScheduleCalls() {
	mock.lockGetSchedule.Lock()
	mock.calls.GetSchedule = nil
	mock.lockGetSchedule.Unlock()
}

// ListSchedules calls ListSchedulesFunc.
func (mock *Scheduler) ListSchedules(ctx context.Context, query *q.Query) ([]*scheduler.Schedule, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockListSchedules.Lock()
	mock.calls.ListSchedules = append(mock.calls.ListSchedules, callInfo)
	mock.lockListSchedules.Unlock()
	if mock.ListSchedulesFunc == nil {
		var (
			schedules []*scheduler.Schedule
			err       error
		)
		return schedules, err
	}
	return mock.ListSchedulesFunc(ctx, query)
}

// ListSchedulesCalls gets all the calls that were made to ListSchedules.
// Check the length with:
//
//	len(mockedScheduler.ListSchedulesCalls())
func (mock *Scheduler) ListSchedulesCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockListSchedules.RLock()
	calls = mock.calls.ListSchedules
	mock.lockListSchedules.RUnlock()
	return calls
}

// ResetListSchedulesCalls reset all the calls that were made to ListSchedules.
func (mock *Scheduler) ResetListSchedulesCalls() {
	mock.lockListSchedules.Lock()
	mock.calls.ListSchedules = nil
	mock.lockListSchedules.Unlock()
}

// Schedule calls ScheduleFunc.
func (mock *Scheduler) Schedule(ctx context.Context, vendorType string, vendorID int64, cronType string, cron string, callbackFuncName string, callbackFuncParams any, extraAttrs map[string]any) (int64, error) {
	callInfo := struct {
		Ctx                context.Context
		VendorType         string
		VendorID           int64
		CronType           string
		Cron               string
		CallbackFuncName   string
		CallbackFuncParams any
		ExtraAttrs         map[string]any
	}{
		Ctx:                ctx,
		VendorType:         vendorType,
		VendorID:           vendorID,
		CronType:           cronType,
		Cron:               cron,
		CallbackFuncName:   callbackFuncName,
		CallbackFuncParams: callbackFuncParams,
		ExtraAttrs:         extraAttrs,
	}
	mock.lockSchedule.Lock()
	mock.calls.Schedule = append(mock.calls.Schedule, callInfo)
	mock.lockSchedule.Unlock()
	if mock.ScheduleFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.ScheduleFunc(ctx, vendorType, vendorID, cronType, cron, callbackFuncName, callbackFuncParams, extraAttrs)
}

// ScheduleCalls gets all the calls that were made to Schedule.
// Check the length with:
//
//	len(mockedScheduler.ScheduleCalls())
func (mock *Scheduler) ScheduleCalls() []struct {
	Ctx                context.Context
	VendorType         string
	VendorID           int64
	CronType           string
	Cron               string
	CallbackFuncName   string
	CallbackFuncParams any
	ExtraAttrs         map[string]any
} {
	var calls []struct {
		Ctx                context.Context
		VendorType         string
		VendorID           int64
		CronType           string
		Cron               string
		CallbackFuncName   string
		CallbackFuncParams any
		ExtraAttrs         map[string]any
	}
	mock.lockSchedule.RLock()
	calls = mock.calls.Schedule
	mock.lockSchedule.RUnlock()
	return calls
}

// ResetScheduleCalls reset all the calls that were made to Schedule.
func (mock *Scheduler) ResetScheduleCalls() {
	mock.lockSchedule.Lock()
	mock.calls.Schedule = nil
	mock.lockSchedule.Unlock()
}

// UnScheduleByID calls UnScheduleByIDFunc.
func (mock *Scheduler) UnScheduleByID(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockUnScheduleByID.Lock()
	mock.calls.UnScheduleByID = append(mock.calls.UnScheduleByID, callInfo)
	mock.lockUnScheduleByID.Unlock()
	if mock.UnScheduleByIDFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UnScheduleByIDFunc(ctx, id)
}

// UnScheduleByIDCalls gets all the calls that were made to UnScheduleByID.
// Check the length with:
//
//	len(mockedScheduler.UnScheduleByIDCalls())
func (mock *Scheduler) UnScheduleByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockUnScheduleByID.RLock()
	calls = mock.calls.UnScheduleByID
	mock.lockUnScheduleByID.RUnlock()
	return calls
}

// ResetUnScheduleByIDCalls reset all the calls that were made to UnScheduleByID.
func (mock *Scheduler) ResetUnScheduleByIDCalls() {
	mock.lockUnScheduleByID.Lock()
	mock.calls.UnScheduleByID = nil
	mock.lockUnScheduleByID.Unlock()
}

// UnScheduleByVendor calls UnScheduleByVendorFunc.
func (mock *Scheduler) UnScheduleByVendor(ctx context.Context, vendorType string, vendorID int64) error {
	callInfo := struct {
		Ctx        context.Context
		VendorType string
		VendorID   int64
	}{
		Ctx:        ctx,
		VendorType: vendorType,
		VendorID:   vendorID,
	}
	mock.lockUnScheduleByVendor.Lock()
	mock.calls.UnScheduleByVendor = append(mock.calls.UnScheduleByVendor, callInfo)
	mock.lockUnScheduleByVendor.Unlock()
	if mock.UnScheduleByVendorFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UnScheduleByVendorFunc(ctx, vendorType, vendorID)
}

// UnScheduleByVendorCalls gets all the calls that were made to UnScheduleByVendor.
// Check the length with:
//
//	len(mockedScheduler.UnScheduleByVendorCalls())
func (mock *Scheduler) UnScheduleByVendorCalls() []struct {
	Ctx        context.Context
	VendorType string
	VendorID   int64
} {
	var calls []struct {
		Ctx        context.Context
		VendorType string
		VendorID   int64
	}
	mock.lockUnScheduleByVendor.RLock()
	calls = mock.calls.UnScheduleByVendor
	mock.lockUnScheduleByVendor.RUnlock()
	return calls
}

// ResetUnScheduleByVendorCalls reset all the calls that were made to UnScheduleByVendor.
func (mock *Scheduler) ResetUnScheduleByVendorCalls() {
	mock.lockUnScheduleByVendor.Lock()
	mock.calls.UnScheduleByVendor = nil
	mock.lockUnScheduleByVendor.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Scheduler) ResetCalls() {
	mock.lockCountSchedules.Lock()
	mock.calls.CountSchedules = nil
	mock.lockCountSchedules.Unlock()

	mock.lockGetSchedule.Lock()
	mock.calls.GetSchedule = nil
	mock.lockGetSchedule.Unlock()

	mock.lockListSchedules.Lock()
	mock.calls.ListSchedules = nil
	mock.lockListSchedules.Unlock()

	mock.lockSchedule.Lock()
	mock.calls.Schedule = nil
	mock.lockSchedule.Unlock()

	mock.lockUnScheduleByID.Lock()
	mock.calls.UnScheduleByID = nil
	mock.lockUnScheduleByID.Unlock()

	mock.lockUnScheduleByVendor.Lock()
	mock.calls.UnScheduleByVendor = nil
	mock.lockUnScheduleByVendor.Unlock()
}
