// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package queuestatus

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/pkg/queuestatus/model"
)

// Manager is a mock implementation of queuestatus.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked queuestatus.Manager
//		mockedManager := &Manager{
//			AllJobTypeStatusFunc: func(ctx context.Context) (map[string]bool, error) {
//				panic("mock out the AllJobTypeStatus method")
//			},
//			CreateOrUpdateFunc: func(ctx context.Context, status *model.JobQueueStatus) (int64, error) {
//				panic("mock out the CreateOrUpdate method")
//			},
//			GetFunc: func(ctx context.Context, jobType string) (*model.JobQueueStatus, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]*model.JobQueueStatus, error) {
//				panic("mock out the List method")
//			},
//			UpdateStatusFunc: func(ctx context.Context, jobType string, paused bool) error {
//				panic("mock out the UpdateStatus method")
//			},
//		}
//
//		// use mockedManager in code that requires queuestatus.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// AllJobTypeStatusFunc mocks the AllJobTypeStatus method.
	AllJobTypeStatusFunc func(ctx context.Context) (map[string]bool, error)

	// CreateOrUpdateFunc mocks the CreateOrUpdate method.
	CreateOrUpdateFunc func(ctx context.Context, status *model.JobQueueStatus) (int64, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, jobType string) (*model.JobQueueStatus, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]*model.JobQueueStatus, error)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, jobType string, paused bool) error

	// calls tracks calls to the methods.
	calls struct {
		// AllJobTypeStatus holds details about calls to the AllJobTypeStatus method.
		AllJobTypeStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateOrUpdate holds details about calls to the CreateOrUpdate method.
		CreateOrUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status *model.JobQueueStatus
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobType is the jobType argument value.
			JobType string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobType is the jobType argument value.
			JobType string
			// Paused is the paused argument value.
			Paused bool
		}
	}
	lockAllJobTypeStatus sync.RWMutex
	lockCreateOrUpdate   sync.RWMutex
	lockGet              sync.RWMutex
	lockList             sync.RWMutex
	lockUpdateStatus     sync.RWMutex
}

// AllJobTypeStatus calls AllJobTypeStatusFunc.
func (mock *Manager) AllJobTypeStatus(ctx context.Context) (map[string]bool, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAllJobTypeStatus.Lock()
	mock.calls.AllJobTypeStatus = append(mock.calls.AllJobTypeStatus, callInfo)
	mock.lockAllJobTypeStatus.Unlock()
	if mock.AllJobTypeStatusFunc == nil {
		var (
			stringToBool map[string]bool
			err          error
		)
		return stringToBool, err
	}
	return mock.AllJobTypeStatusFunc(ctx)
}

// AllJobTypeStatusCalls gets all the calls that were made to AllJobTypeStatus.
// Check the length with:
//
//	len(mockedManager.AllJobTypeStatusCalls())
func (mock *Manager) AllJobTypeStatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAllJobTypeStatus.RLock()
	calls = mock.calls.AllJobTypeStatus
	mock.lockAllJobTypeStatus.RUnlock()
	return calls
}

// ResetAllJobTypeStatusCalls reset all the calls that were made to AllJobTypeStatus.
func (mock *Manager) ResetAllJobTypeStatusCalls() {
	mock.lockAllJobTypeStatus.Lock()
	mock.calls.AllJobTypeStatus = nil
	mock.lockAllJobTypeStatus.Unlock()
}

// CreateOrUpdate calls CreateOrUpdateFunc.
func (mock *Manager) CreateOrUpdate(ctx context.Context, status *model.JobQueueStatus) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		Status *model.JobQueueStatus
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockCreateOrUpdate.Lock()
	mock.calls.CreateOrUpdate = append(mock.calls.CreateOrUpdate, callInfo)
	mock.lockCreateOrUpdate.Unlock()
	if mock.CreateOrUpdateFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.CreateOrUpdateFunc(ctx, status)
}

// CreateOrUpdateCalls gets all the calls that were made to CreateOrUpdate.
// Check the length with:
//
//	len(mockedManager.CreateOrUpdateCalls())
func (mock *Manager) CreateOrUpdateCalls() []struct {
	Ctx    context.Context
	Status *model.JobQueueStatus
} {
	var calls []struct {
		Ctx    context.Context
		Status *model.JobQueueStatus
	}
	mock.lockCreateOrUpdate.RLock()
	calls = mock.calls.CreateOrUpdate
	mock.lockCreateOrUpdate.RUnlock()
	return calls
}

// ResetCreateOrUpdateCalls reset all the calls that were made to CreateOrUpdate.
func (mock *Manager) ResetCreateOrUpdateCalls() {
	mock.lockCreateOrUpdate.Lock()
	mock.calls.CreateOrUpdate = nil
	mock.lockCreateOrUpdate.Unlock()
}

// Get calls GetFunc.
func (mock *Manager) Get(ctx context.Context, jobType string) (*model.JobQueueStatus, error) {
	callInfo := struct {
		Ctx     context.Context
		JobType string
	}{
		Ctx:     ctx,
		JobType: jobType,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			jobQueueStatus *model.JobQueueStatus
			err            error
		)
		return jobQueueStatus, err
	}
	return mock.GetFunc(ctx, jobType)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *Manager) GetCalls() []struct {
	Ctx     context.Context
	JobType string
} {
	var calls []struct {
		Ctx     context.Context
		JobType string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *Manager) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context) ([]*model.JobQueueStatus, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			jobQueueStatuss []*model.JobQueueStatus
			err             error
		)
		return jobQueueStatuss, err
	}
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *Manager) UpdateStatus(ctx context.Context, jobType string, paused bool) error {
	callInfo := struct {
		Ctx     context.Context
		JobType string
		Paused  bool
	}{
		Ctx:     ctx,
		JobType: jobType,
		Paused:  paused,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	if mock.UpdateStatusFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateStatusFunc(ctx, jobType, paused)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//
//	len(mockedManager.UpdateStatusCalls())
func (mock *Manager) UpdateStatusCalls() []struct {
	Ctx     context.Context
	JobType string
	Paused  bool
} {
	var calls []struct {
		Ctx     context.Context
		JobType string
		Paused  bool
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// ResetUpdateStatusCalls reset all the calls that were made to UpdateStatus.
func (mock *Manager) ResetUpdateStatusCalls() {
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = nil
	mock.lockUpdateStatus.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockAllJobTypeStatus.Lock()
	mock.calls.AllJobTypeStatus = nil
	mock.lockAllJobTypeStatus.Unlock()

	mock.lockCreateOrUpdate.Lock()
	mock.calls.CreateOrUpdate = nil
	mock.lockCreateOrUpdate.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = nil
	mock.lockUpdateStatus.Unlock()
}
