// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package report

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/lib/q"
	"github.com/goharbor/harbor/src/pkg/scan/dao/scan"
)

// Manager is a mock implementation of report.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked report.Manager
//		mockedManager := &Manager{
//			CreateFunc: func(ctx context.Context, r *scan.Report) (string, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, uuid string) error {
//				panic("mock out the Delete method")
//			},
//			DeleteByDigestsFunc: func(ctx context.Context, digests ...string) error {
//				panic("mock out the DeleteByDigests method")
//			},
//			DeleteByExtraAttrFunc: func(ctx context.Context, mimeType string, attrName string, attrValue string) error {
//				panic("mock out the DeleteByExtraAttr method")
//			},
//			GetByFunc: func(ctx context.Context, digest string, registrationUUID string, mimeTypes []string) ([]*scan.Report, error) {
//				panic("mock out the GetBy method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query) ([]*scan.Report, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, r *scan.Report, cols ...string) error {
//				panic("mock out the Update method")
//			},
//			UpdateReportDataFunc: func(ctx context.Context, uuid string, report string) error {
//				panic("mock out the UpdateReportData method")
//			},
//		}
//
//		// use mockedManager in code that requires report.Manager
//		// and then make assertions.
//
//	}
type Manager struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, r *scan.Report) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, uuid string) error

	// DeleteByDigestsFunc mocks the DeleteByDigests method.
	DeleteByDigestsFunc func(ctx context.Context, digests ...string) error

	// DeleteByExtraAttrFunc mocks the DeleteByExtraAttr method.
	DeleteByExtraAttrFunc func(ctx context.Context, mimeType string, attrName string, attrValue string) error

	// GetByFunc mocks the GetBy method.
	GetByFunc func(ctx context.Context, digest string, registrationUUID string, mimeTypes []string) ([]*scan.Report, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query) ([]*scan.Report, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, r *scan.Report, cols ...string) error

	// UpdateReportDataFunc mocks the UpdateReportData method.
	UpdateReportDataFunc func(ctx context.Context, uuid string, report string) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *scan.Report
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UUID is the uuid argument value.
			UUID string
		}
		// DeleteByDigests holds details about calls to the DeleteByDigests method.
		DeleteByDigests []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Digests is the digests argument value.
			Digests []string
		}
		// DeleteByExtraAttr holds details about calls to the DeleteByExtraAttr method.
		DeleteByExtraAttr []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MimeType is the mimeType argument value.
			MimeType string
			// AttrName is the attrName argument value.
			AttrName string
			// AttrValue is the attrValue argument value.
			AttrValue string
		}
		// GetBy holds details about calls to the GetBy method.
		GetBy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Digest is the digest argument value.
			Digest string
			// RegistrationUUID is the registrationUUID argument value.
			RegistrationUUID string
			// MimeTypes is the mimeTypes argument value.
			MimeTypes []string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *scan.Report
			// Cols is the cols argument value.
			Cols []string
		}
		// UpdateReportData holds details about calls to the UpdateReportData method.
		UpdateReportData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UUID is the uuid argument value.
			UUID string
			// Report is the report argument value.
			Report string
		}
	}
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockDeleteByDigests   sync.RWMutex
	lockDeleteByExtraAttr sync.RWMutex
	lockGetBy             sync.RWMutex
	lockList              sync.RWMutex
	lockUpdate            sync.RWMutex
	lockUpdateReportData  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *Manager) Create(ctx context.Context, r *scan.Report) (string, error) {
	callInfo := struct {
		Ctx context.Context
		R   *scan.Report
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			s   string
			err error
		)
		return s, err
	}
	return mock.CreateFunc(ctx, r)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedManager.CreateCalls())
func (mock *Manager) CreateCalls() []struct {
	Ctx context.Context
	R   *scan.Report
} {
	var calls []struct {
		Ctx context.Context
		R   *scan.Report
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *Manager) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *Manager) Delete(ctx context.Context, uuid string) error {
	callInfo := struct {
		Ctx  context.Context
		UUID string
	}{
		Ctx:  ctx,
		UUID: uuid,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, uuid)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedManager.DeleteCalls())
func (mock *Manager) DeleteCalls() []struct {
	Ctx  context.Context
	UUID string
} {
	var calls []struct {
		Ctx  context.Context
		UUID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *Manager) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// DeleteByDigests calls DeleteByDigestsFunc.
func (mock *Manager) DeleteByDigests(ctx context.Context, digests ...string) error {
	callInfo := struct {
		Ctx     context.Context
		Digests []string
	}{
		Ctx:     ctx,
		Digests: digests,
	}
	mock.lockDeleteByDigests.Lock()
	mock.calls.DeleteByDigests = append(mock.calls.DeleteByDigests, callInfo)
	mock.lockDeleteByDigests.Unlock()
	if mock.DeleteByDigestsFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteByDigestsFunc(ctx, digests...)
}

// DeleteByDigestsCalls gets all the calls that were made to DeleteByDigests.
// Check the length with:
//
//	len(mockedManager.DeleteByDigestsCalls())
func (mock *Manager) DeleteByDigestsCalls() []struct {
	Ctx     context.Context
	Digests []string
} {
	var calls []struct {
		Ctx     context.Context
		Digests []string
	}
	mock.lockDeleteByDigests.RLock()
	calls = mock.calls.DeleteByDigests
	mock.lockDeleteByDigests.RUnlock()
	return calls
}

// ResetDeleteByDigestsCalls reset all the calls that were made to DeleteByDigests.
func (mock *Manager) ResetDeleteByDigestsCalls() {
	mock.lockDeleteByDigests.Lock()
	mock.calls.DeleteByDigests = nil
	mock.lockDeleteByDigests.Unlock()
}

// DeleteByExtraAttr calls DeleteByExtraAttrFunc.
func (mock *Manager) DeleteByExtraAttr(ctx context.Context, mimeType string, attrName string, attrValue string) error {
	callInfo := struct {
		Ctx       context.Context
		MimeType  string
		AttrName  string
		AttrValue string
	}{
		Ctx:       ctx,
		MimeType:  mimeType,
		AttrName:  attrName,
		AttrValue: attrValue,
	}
	mock.lockDeleteByExtraAttr.Lock()
	mock.calls.DeleteByExtraAttr = append(mock.calls.DeleteByExtraAttr, callInfo)
	mock.lockDeleteByExtraAttr.Unlock()
	if mock.DeleteByExtraAttrFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteByExtraAttrFunc(ctx, mimeType, attrName, attrValue)
}

// DeleteByExtraAttrCalls gets all the calls that were made to DeleteByExtraAttr.
// Check the length with:
//
//	len(mockedManager.DeleteByExtraAttrCalls())
func (mock *Manager) DeleteByExtraAttrCalls() []struct {
	Ctx       context.Context
	MimeType  string
	AttrName  string
	AttrValue string
} {
	var calls []struct {
		Ctx       context.Context
		MimeType  string
		AttrName  string
		AttrValue string
	}
	mock.lockDeleteByExtraAttr.RLock()
	calls = mock.calls.DeleteByExtraAttr
	mock.lockDeleteByExtraAttr.RUnlock()
	return calls
}

// ResetDeleteByExtraAttrCalls reset all the calls that were made to DeleteByExtraAttr.
func (mock *Manager) ResetDeleteByExtraAttrCalls() {
	mock.lockDeleteByExtraAttr.Lock()
	mock.calls.DeleteByExtraAttr = nil
	mock.lockDeleteByExtraAttr.Unlock()
}

// GetBy calls GetByFunc.
func (mock *Manager) GetBy(ctx context.Context, digest string, registrationUUID string, mimeTypes []string) ([]*scan.Report, error) {
	callInfo := struct {
		Ctx              context.Context
		Digest           string
		RegistrationUUID string
		MimeTypes        []string
	}{
		Ctx:              ctx,
		Digest:           digest,
		RegistrationUUID: registrationUUID,
		MimeTypes:        mimeTypes,
	}
	mock.lockGetBy.Lock()
	mock.calls.GetBy = append(mock.calls.GetBy, callInfo)
	mock.lockGetBy.Unlock()
	if mock.GetByFunc == nil {
		var (
			reports []*scan.Report
			err     error
		)
		return reports, err
	}
	return mock.GetByFunc(ctx, digest, registrationUUID, mimeTypes)
}

// GetByCalls gets all the calls that were made to GetBy.
// Check the length with:
//
//	len(mockedManager.GetByCalls())
func (mock *Manager) GetByCalls() []struct {
	Ctx              context.Context
	Digest           string
	RegistrationUUID string
	MimeTypes        []string
} {
	var calls []struct {
		Ctx              context.Context
		Digest           string
		RegistrationUUID string
		MimeTypes        []string
	}
	mock.lockGetBy.RLock()
	calls = mock.calls.GetBy
	mock.lockGetBy.RUnlock()
	return calls
}

// ResetGetByCalls reset all the calls that were made to GetBy.
func (mock *Manager) ResetGetByCalls() {
	mock.lockGetBy.Lock()
	mock.calls.GetBy = nil
	mock.lockGetBy.Unlock()
}

// List calls ListFunc.
func (mock *Manager) List(ctx context.Context, query *q.Query) ([]*scan.Report, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			reports []*scan.Report
			err     error
		)
		return reports, err
	}
	return mock.ListFunc(ctx, query)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManager.ListCalls())
func (mock *Manager) ListCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *Manager) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Update calls UpdateFunc.
func (mock *Manager) Update(ctx context.Context, r *scan.Report, cols ...string) error {
	callInfo := struct {
		Ctx  context.Context
		R    *scan.Report
		Cols []string
	}{
		Ctx:  ctx,
		R:    r,
		Cols: cols,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, r, cols...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedManager.UpdateCalls())
func (mock *Manager) UpdateCalls() []struct {
	Ctx  context.Context
	R    *scan.Report
	Cols []string
} {
	var calls []struct {
		Ctx  context.Context
		R    *scan.Report
		Cols []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *Manager) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// UpdateReportData calls UpdateReportDataFunc.
func (mock *Manager) UpdateReportData(ctx context.Context, uuid string, report string) error {
	callInfo := struct {
		Ctx    context.Context
		UUID   string
		Report string
	}{
		Ctx:    ctx,
		UUID:   uuid,
		Report: report,
	}
	mock.lockUpdateReportData.Lock()
	mock.calls.UpdateReportData = append(mock.calls.UpdateReportData, callInfo)
	mock.lockUpdateReportData.Unlock()
	if mock.UpdateReportDataFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateReportDataFunc(ctx, uuid, report)
}

// UpdateReportDataCalls gets all the calls that were made to UpdateReportData.
// Check the length with:
//
//	len(mockedManager.UpdateReportDataCalls())
func (mock *Manager) UpdateReportDataCalls() []struct {
	Ctx    context.Context
	UUID   string
	Report string
} {
	var calls []struct {
		Ctx    context.Context
		UUID   string
		Report string
	}
	mock.lockUpdateReportData.RLock()
	calls = mock.calls.UpdateReportData
	mock.lockUpdateReportData.RUnlock()
	return calls
}

// ResetUpdateReportDataCalls reset all the calls that were made to UpdateReportData.
func (mock *Manager) ResetUpdateReportDataCalls() {
	mock.lockUpdateReportData.Lock()
	mock.calls.UpdateReportData = nil
	mock.lockUpdateReportData.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *Manager) ResetCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDeleteByDigests.Lock()
	mock.calls.DeleteByDigests = nil
	mock.lockDeleteByDigests.Unlock()

	mock.lockDeleteByExtraAttr.Lock()
	mock.calls.DeleteByExtraAttr = nil
	mock.lockDeleteByExtraAttr.Unlock()

	mock.lockGetBy.Lock()
	mock.calls.GetBy = nil
	mock.lockGetBy.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()

	mock.lockUpdateReportData.Lock()
	mock.calls.UpdateReportData = nil
	mock.lockUpdateReportData.Unlock()
}
