// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package tag

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/controller/tag"
	"github.com/goharbor/harbor/src/lib/q"
)

// FakeController is a mock implementation of tag.Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked tag.Controller
//		mockedController := &FakeController{
//			CountFunc: func(ctx context.Context, query *q.Query) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, tag1 *tag.Tag) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			DeleteTagsFunc: func(ctx context.Context, ids []int64) error {
//				panic("mock out the DeleteTags method")
//			},
//			EnsureFunc: func(ctx context.Context, repositoryID int64, artifactID int64, name string) (int64, error) {
//				panic("mock out the Ensure method")
//			},
//			GetFunc: func(ctx context.Context, id int64, option *tag.Option) (*tag.Tag, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, query *q.Query, option *tag.Option) ([]*tag.Tag, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, tag1 *tag.Tag, props ...string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedController in code that requires tag.Controller
//		// and then make assertions.
//
//	}
type FakeController struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, query *q.Query) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, tag1 *tag.Tag) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// DeleteTagsFunc mocks the DeleteTags method.
	DeleteTagsFunc func(ctx context.Context, ids []int64) error

	// EnsureFunc mocks the Ensure method.
	EnsureFunc func(ctx context.Context, repositoryID int64, artifactID int64, name string) (int64, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64, option *tag.Option) (*tag.Tag, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, query *q.Query, option *tag.Option) ([]*tag.Tag, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, tag1 *tag.Tag, props ...string) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tag1 is the tag1 argument value.
			Tag1 *tag.Tag
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DeleteTags holds details about calls to the DeleteTags method.
		DeleteTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []int64
		}
		// Ensure holds details about calls to the Ensure method.
		Ensure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepositoryID is the repositoryID argument value.
			RepositoryID int64
			// ArtifactID is the artifactID argument value.
			ArtifactID int64
			// Name is the name argument value.
			Name string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Option is the option argument value.
			Option *tag.Option
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query *q.Query
			// Option is the option argument value.
			Option *tag.Option
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tag1 is the tag1 argument value.
			Tag1 *tag.Tag
			// Props is the props argument value.
			Props []string
		}
	}
	lockCount      sync.RWMutex
	lockCreate     sync.RWMutex
	lockDelete     sync.RWMutex
	lockDeleteTags sync.RWMutex
	lockEnsure     sync.RWMutex
	lockGet        sync.RWMutex
	lockList       sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Count calls CountFunc.
func (mock *FakeController) Count(ctx context.Context, query *q.Query) (int64, error) {
	callInfo := struct {
		Ctx   context.Context
		Query *q.Query
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			total int64
			err   error
		)
		return total, err
	}
	return mock.CountFunc(ctx, query)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedController.CountCalls())
func (mock *FakeController) CountCalls() []struct {
	Ctx   context.Context
	Query *q.Query
} {
	var calls []struct {
		Ctx   context.Context
		Query *q.Query
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// ResetCountCalls reset all the calls that were made to Count.
func (mock *FakeController) ResetCountCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()
}

// Create calls CreateFunc.
func (mock *FakeController) Create(ctx context.Context, tag1 *tag.Tag) (int64, error) {
	callInfo := struct {
		Ctx  context.Context
		Tag1 *tag.Tag
	}{
		Ctx:  ctx,
		Tag1: tag1,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			id  int64
			err error
		)
		return id, err
	}
	return mock.CreateFunc(ctx, tag1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedController.CreateCalls())
func (mock *FakeController) CreateCalls() []struct {
	Ctx  context.Context
	Tag1 *tag.Tag
} {
	var calls []struct {
		Ctx  context.Context
		Tag1 *tag.Tag
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *FakeController) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Delete calls DeleteFunc.
func (mock *FakeController) Delete(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedController.DeleteCalls())
func (mock *FakeController) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *FakeController) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// DeleteTags calls DeleteTagsFunc.
func (mock *FakeController) DeleteTags(ctx context.Context, ids []int64) error {
	callInfo := struct {
		Ctx context.Context
		Ids []int64
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockDeleteTags.Lock()
	mock.calls.DeleteTags = append(mock.calls.DeleteTags, callInfo)
	mock.lockDeleteTags.Unlock()
	if mock.DeleteTagsFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.DeleteTagsFunc(ctx, ids)
}

// DeleteTagsCalls gets all the calls that were made to DeleteTags.
// Check the length with:
//
//	len(mockedController.DeleteTagsCalls())
func (mock *FakeController) DeleteTagsCalls() []struct {
	Ctx context.Context
	Ids []int64
} {
	var calls []struct {
		Ctx context.Context
		Ids []int64
	}
	mock.lockDeleteTags.RLock()
	calls = mock.calls.DeleteTags
	mock.lockDeleteTags.RUnlock()
	return calls
}

// ResetDeleteTagsCalls reset all the calls that were made to DeleteTags.
func (mock *FakeController) ResetDeleteTagsCalls() {
	mock.lockDeleteTags.Lock()
	mock.calls.DeleteTags = nil
	mock.lockDeleteTags.Unlock()
}

// Ensure calls EnsureFunc.
func (mock *FakeController) Ensure(ctx context.Context, repositoryID int64, artifactID int64, name string) (int64, error) {
	callInfo := struct {
		Ctx          context.Context
		RepositoryID int64
		ArtifactID   int64
		Name         string
	}{
		Ctx:          ctx,
		RepositoryID: repositoryID,
		ArtifactID:   artifactID,
		Name:         name,
	}
	mock.lockEnsure.Lock()
	mock.calls.Ensure = append(mock.calls.Ensure, callInfo)
	mock.lockEnsure.Unlock()
	if mock.EnsureFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.EnsureFunc(ctx, repositoryID, artifactID, name)
}

// EnsureCalls gets all the calls that were made to Ensure.
// Check the length with:
//
//	len(mockedController.EnsureCalls())
func (mock *FakeController) EnsureCalls() []struct {
	Ctx          context.Context
	RepositoryID int64
	ArtifactID   int64
	Name         string
} {
	var calls []struct {
		Ctx          context.Context
		RepositoryID int64
		ArtifactID   int64
		Name         string
	}
	mock.lockEnsure.RLock()
	calls = mock.calls.Ensure
	mock.lockEnsure.RUnlock()
	return calls
}

// ResetEnsureCalls reset all the calls that were made to Ensure.
func (mock *FakeController) ResetEnsureCalls() {
	mock.lockEnsure.Lock()
	mock.calls.Ensure = nil
	mock.lockEnsure.Unlock()
}

// Get calls GetFunc.
func (mock *FakeController) Get(ctx context.Context, id int64, option *tag.Option) (*tag.Tag, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     int64
		Option *tag.Option
	}{
		Ctx:    ctx,
		ID:     id,
		Option: option,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			tag1 *tag.Tag
			err  error
		)
		return tag1, err
	}
	return mock.GetFunc(ctx, id, option)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedController.GetCalls())
func (mock *FakeController) GetCalls() []struct {
	Ctx    context.Context
	ID     int64
	Option *tag.Option
} {
	var calls []struct {
		Ctx    context.Context
		ID     int64
		Option *tag.Option
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *FakeController) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// List calls ListFunc.
func (mock *FakeController) List(ctx context.Context, query *q.Query, option *tag.Option) ([]*tag.Tag, error) {
	callInfo := struct {
		Ctx    context.Context
		Query  *q.Query
		Option *tag.Option
	}{
		Ctx:    ctx,
		Query:  query,
		Option: option,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	if mock.ListFunc == nil {
		var (
			tags []*tag.Tag
			err  error
		)
		return tags, err
	}
	return mock.ListFunc(ctx, query, option)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedController.ListCalls())
func (mock *FakeController) ListCalls() []struct {
	Ctx    context.Context
	Query  *q.Query
	Option *tag.Option
} {
	var calls []struct {
		Ctx    context.Context
		Query  *q.Query
		Option *tag.Option
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ResetListCalls reset all the calls that were made to List.
func (mock *FakeController) ResetListCalls() {
	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()
}

// Update calls UpdateFunc.
func (mock *FakeController) Update(ctx context.Context, tag1 *tag.Tag, props ...string) error {
	callInfo := struct {
		Ctx   context.Context
		Tag1  *tag.Tag
		Props []string
	}{
		Ctx:   ctx,
		Tag1:  tag1,
		Props: props,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.UpdateFunc(ctx, tag1, props...)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedController.UpdateCalls())
func (mock *FakeController) UpdateCalls() []struct {
	Ctx   context.Context
	Tag1  *tag.Tag
	Props []string
} {
	var calls []struct {
		Ctx   context.Context
		Tag1  *tag.Tag
		Props []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// ResetUpdateCalls reset all the calls that were made to Update.
func (mock *FakeController) ResetUpdateCalls() {
	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *FakeController) ResetCalls() {
	mock.lockCount.Lock()
	mock.calls.Count = nil
	mock.lockCount.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()

	mock.lockDeleteTags.Lock()
	mock.calls.DeleteTags = nil
	mock.lockDeleteTags.Unlock()

	mock.lockEnsure.Lock()
	mock.calls.Ensure = nil
	mock.lockEnsure.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockList.Lock()
	mock.calls.List = nil
	mock.lockList.Unlock()

	mock.lockUpdate.Lock()
	mock.calls.Update = nil
	mock.lockUpdate.Unlock()
}
