// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package dao

import (
	"context"
	"sync"

	"github.com/goharbor/harbor/src/pkg/allowlist/models"
)

// DAO is a mock implementation of dao.DAO.
//
//	func TestSomethingThatUsesDAO(t *testing.T) {
//
//		// make and configure a mocked dao.DAO
//		mockedDAO := &DAO{
//			QueryByProjectIDFunc: func(ctx context.Context, pid int64) (*models.CVEAllowlist, error) {
//				panic("mock out the QueryByProjectID method")
//			},
//			SetFunc: func(ctx context.Context, l models.CVEAllowlist) (int64, error) {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedDAO in code that requires dao.DAO
//		// and then make assertions.
//
//	}
type DAO struct {
	// QueryByProjectIDFunc mocks the QueryByProjectID method.
	QueryByProjectIDFunc func(ctx context.Context, pid int64) (*models.CVEAllowlist, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, l models.CVEAllowlist) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// QueryByProjectID holds details about calls to the QueryByProjectID method.
		QueryByProjectID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pid is the pid argument value.
			Pid int64
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// L is the l argument value.
			L models.CVEAllowlist
		}
	}
	lockQueryByProjectID sync.RWMutex
	lockSet              sync.RWMutex
}

// QueryByProjectID calls QueryByProjectIDFunc.
func (mock *DAO) QueryByProjectID(ctx context.Context, pid int64) (*models.CVEAllowlist, error) {
	callInfo := struct {
		Ctx context.Context
		Pid int64
	}{
		Ctx: ctx,
		Pid: pid,
	}
	mock.lockQueryByProjectID.Lock()
	mock.calls.QueryByProjectID = append(mock.calls.QueryByProjectID, callInfo)
	mock.lockQueryByProjectID.Unlock()
	if mock.QueryByProjectIDFunc == nil {
		var (
			cVEAllowlist *models.CVEAllowlist
			err          error
		)
		return cVEAllowlist, err
	}
	return mock.QueryByProjectIDFunc(ctx, pid)
}

// QueryByProjectIDCalls gets all the calls that were made to QueryByProjectID.
// Check the length with:
//
//	len(mockedDAO.QueryByProjectIDCalls())
func (mock *DAO) QueryByProjectIDCalls() []struct {
	Ctx context.Context
	Pid int64
} {
	var calls []struct {
		Ctx context.Context
		Pid int64
	}
	mock.lockQueryByProjectID.RLock()
	calls = mock.calls.QueryByProjectID
	mock.lockQueryByProjectID.RUnlock()
	return calls
}

// ResetQueryByProjectIDCalls reset all the calls that were made to QueryByProjectID.
func (mock *DAO) ResetQueryByProjectIDCalls() {
	mock.lockQueryByProjectID.Lock()
	mock.calls.QueryByProjectID = nil
	mock.lockQueryByProjectID.Unlock()
}

// Set calls SetFunc.
func (mock *DAO) Set(ctx context.Context, l models.CVEAllowlist) (int64, error) {
	callInfo := struct {
		Ctx context.Context
		L   models.CVEAllowlist
	}{
		Ctx: ctx,
		L:   l,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	if mock.SetFunc == nil {
		var (
			n   int64
			err error
		)
		return n, err
	}
	return mock.SetFunc(ctx, l)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedDAO.SetCalls())
func (mock *DAO) SetCalls() []struct {
	Ctx context.Context
	L   models.CVEAllowlist
} {
	var calls []struct {
		Ctx context.Context
		L   models.CVEAllowlist
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// ResetSetCalls reset all the calls that were made to Set.
func (mock *DAO) ResetSetCalls() {
	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DAO) ResetCalls() {
	mock.lockQueryByProjectID.Lock()
	mock.calls.QueryByProjectID = nil
	mock.lockQueryByProjectID.Unlock()

	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}
